### ISSUE TITLE
Need to convert LS-codebase to TS - best option?

### ISSUE THREAD

**Issue by ozra** [gkz/LiveScript#1004]
So here's the scenario, I've written a shitload of LS, as part of technical systemizing, planned to later be JS'ified when more people, aside from myselves, are brought into the team. Now we're at that point.

I currently just transpile it with async-livescript@1.5.2 and rewrite the mangled ES5-output into TypeScript, file by file as someone else needs to touch it. ...Which leaves me with a lot of manual rewriting of _primarily class-defs_. 

So... anyone have a recommendation for a fork/branch of LS that generates "EcmaishScript6+" closest to my needs (_primarily classes "intact"_)? The transpiled code doesn't even have to work 100%, as long as the manual touch-ups required are deterministic enough (and less work than current rewriting), and given it will manually be no-implicit-nulls typed, step by step.

**Comment by vendethiel** [comment]
Have you looked into livescript-next?

**Comment by ozra** [comment]
Not that I remember XD, I'll check it out!

**Comment by ozra** [comment]
Quick try online: classes doesn't seem to work at all? For async: after replacing `(x, y, z) ->> stuff` with `async (x, y, z) -> stuff` that works. Weirdly, it adds double `async` when it figures a function should be async... Hmm.

**Comment by rhendric** [comment]
🙁 I don't know of anyone who's attempted LS class to ES class conversion yet. This is just speculation, but I suspect part of the reason is that LS classes can be instantiated without `new` and ES classes can't, so no fully general ‘your LS code just works’ solution would be possible, which probably discourages people from writing even a partial solution for public consumption.

**Comment by vendethiel** [comment]
You can omit the new only for bound constructors. I suppose people don't use them in all of their classes.

**Comment by rhendric** [comment]
Ah, yes, fair enough. All right then, I retract the speculation.

**Comment by ozra** [comment]
Yeah, I'm just interested in a purely lexical transform, so to speak, to minimize the amounts of actual edits, copying, pasting, moving around — the plain and simple grunt-work — not in a semantically intact transform.

**Comment by determin1st** [comment]
Isn't that stated, that TS will convert/compile JS code? I mean, they say it will do this with native JS without problems.

**Comment by ozra** [comment]
The generated js is pretty far off the mark. Anyway I made a small prog running a bunch of hideous regexes that produced fairly good bases for manual touchup, so it all worked out. Thanks for all tips!
