### ISSUE TITLE
The tag 1.5.0 is assigned to a wrong commit, resulting in having v1.4.0 on CDNJS

### ISSUE THREAD

**Issue by pepkin88** [gkz/LiveScript#1005]
As a result of an incorrect tag assignment, CDNJS downloaded version 1.4.0 as 1.5.0. I opened an issue (https://github.com/cdnjs/cdnjs/issues/12459) and a PR (https://github.com/cdnjs/cdnjs/pull/12461) there, but it might be easier to retag the commit here.

I don't know what consequences are for changing a tag, so that might be one of the reasons to push 1.6.0 (or different number) earlier.

Thoughts?

**Comment by vendethiel** [comment]
I'm not sure I understand what's wrong.

[1.5.0 seems correct](https://github.com/gkz/LiveScript/tree/1.5.0)

**Comment by pepkin88** [comment]
CDNJS hosts libraries for browsers. The browser version under the 1.5.0. tag is the prevoius one:
https://github.com/gkz/LiveScript/blob/1.5.0/browser/livescript.js

The commit, which finally fixed this is here: https://github.com/gkz/LiveScript/commit/87daae63c4e988eb5c5d0ab599654f58af6c8d0a

**Comment by sufuf3** [comment]
Just a memo
The file https://github.com/gkz/LiveScript/blob/1.5.0/browser/livescript.js on CDNJS is the same with https://github.com/gkz/LiveScript/blob/1.5.0/browser/livescript.js (git tag v1.5.0)

CDNJS host files related on git tag.
Thank you.

**Comment by rhendric** [comment]
Yikes, that's not great. I think I agree that the simplest solution is to start planning for a 1.6 release.

**Comment by pepkin88** [comment]
As the 1.6.0 version has been released (on GitHub at least), the newest version of LiveScript is now correctly loaded onto CDNJS. Therefore I'll close this issue.
