### ISSUE TITLE
Array with variables

### ISSUE THREAD

**Issue by askucher** [gkz/LiveScript#1006]
Some point of improvement . Please consider the case

statement
```livescript
v = "123"
test = <[ test #v ]>
```

desired implementation:
```livescript
v = "123"
test = "test #v".split(" ") #=> ["test", "123"]
```

given implementation: 
```livescript
v = "123"
test = 'test #v'.split(" ") #=> ["test", "#v"]
```

**Comment by vendethiel** [comment]
This is `%"test#v"`

**Comment by rhendric** [comment]
(That's a cute hack, @vendethiel, but not quite what he seems to be asking for.)

Yeah, so while this isn't quite an insta-close, I'm pretty disinclined to support this without substantial demand from others. Like with the last conversation we had, this would be a breaking change, and I can imagine someone who's written `css-selectors = <[ .borderless #root ]>` being pretty upset if that stopped working the way they expect it to. There's also consistency with other literal constructs to consider—should `\foo#bar` also interpolate?

**Comment by vendethiel** [comment]
Aso, if v has multiple words, are those a single array elem or many?

**Comment by determin1st** [comment]
`<[ test #v ]>` looks very "cryptic" to me... better let symbols to mean one thing, it will be remembered better and when you dont touch scripting for a month for example.. you will not be cornered with your own code, imo.

**Comment by askucher** [comment]
`to-arr "test #v"` where `to-arr = -> it.split(" ")` works for me

**Comment by vendethiel** [comment]
Depends what behavior you want if `v` contains a space

**Comment by rhendric** [comment]
Closing until there are others who think this is a good idea.
