### ISSUE TITLE
Arrays / ranges / better compile?

### ISSUE THREAD

**Issue by log69** [gkz/LiveScript#1007]

**Comment by log69** [comment]
Hi, thanks fro your works. (Sorry about the changes in this issue, I had some problem with github.)

I'd like to inquire whether you are planning for the future to compile the negative ranges for arrays in a better way? What I mean is that when I use negative ranges like this:

    [til 100][-5 to -1]

It compiles to this:

    slice$.call([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], -3, -1 + 1 || 9e9)

If I use bigger arrays then each and every item in the array will be included in the result. What is the reason behind this? Thanks.

**Comment by rhendric** [comment]
LiveScript only expands the array if the range used to create it involves only literals. You can avoid the explosion with
```ls
limit = 100
[til limit][-5 to -1]
```
or, more obtusely,
```ls
[til (100)][-5 to -1]
```


Broadly, while it does seem like constructing a 100-element array is too big, I don't know what a natural cutoff for ‘too big’ would be—it's the paradox of the heap. That's probably why the language is the way it is right now: programmers have the control over what the compiler does, by using literal-only syntax or adding a variable or parentheses or something.

**Comment by log69** [comment]
That seems super cool :) Thanks for the explanation. I started off with Coffee and then found LS and it is just awesome. Thanks.

**Comment by rhendric** [comment]
You're welcome, and welcome to our little community!
