### ISSUE TITLE
Add documentation how to bundle livescript with webpack

### ISSUE THREAD

**Issue by bartosz-m** [gkz/LiveScript#1008]
Long story short I've needed to bundle livescript, but webpack was complaining with some errors, so I came up with this piece of code:
```livescript
# webpack.config.ls
add-livescript-requirements = (module-exports) ->
    module-exports
        ..node <<<
            fs: "empty"
            net: "mock"
            module: "empty"
        ..[]plugins.push do
            new webpack.DefinePlugin do
                "require.extensions": {}


... # rest of config file

add-livescript-requirements module.exports

```
Some information in docs about how to configure webpack for bundling livescript would be nice.

**Comment by rhendric** [comment]
Cool! I think this would be better off on the wiki rather than in the formal LiveScript documentation. This is not, after all, information about LiveScript, either the language or the tool; it's information about how to integrate LiveScript with a different tool. I don't want to have to worry about updating LiveScript's docs if webpack ever changes; the community using webpack and LS together should be responsible for that. Would you create the wiki page for this?

**Comment by bartosz-m** [comment]
I don't mind writing wiki page, but I'm quite puzzled where it should be put. If not in livescript repo then where would be a right place?

**Comment by rhendric** [comment]
Oh no, I meant in the [LiveScript repo wiki](https://github.com/gkz/LiveScript/wiki)! (As opposed to the formal livescript.net docs.)

**Comment by bartosz-m** [comment]
Ok. Then I'll double check with minimal project if my snippet works without problem, and I'll create new page that describes how to make livescript and webpack play nice together.  
Would it be ok add some more pages about different tools? Recently I stater using livescript with [yadda](https://github.com/acuminous/yadda) and [mocha](https://github.com/mochajs/mocha) so I can write about them.

**Comment by rhendric** [comment]
Absolutely, that would be very welcome!

**Comment by bartosz-m** [comment]
Added wiki [page](https://github.com/gkz/LiveScript/wiki/Bundling-Livescript-with-Webpack) for bundling livescript with webpack. If its content is ok, this issue can be closed

**Comment by rhendric** [comment]
That looks great, thank you!
