### ISSUE TITLE
Executing via `lsc -w` renders runtime error unusable

### ISSUE THREAD

**Issue by vendethiel** [gkz/LiveScript#1015]
```livescript
➜  LiveScript git:(master) ✗ cat ~/err.ls
throw new Error
➜  LiveScript git:(master) ✗ ./bin/lsc -w ~/err.ls
Failed at: ~/err.ls
undefined
```

**Comment by vendethiel** [comment]
Without `-w`:

```
./bin/lsc ~/err.ls
Failed at: ~/err.ls
Error
    at Object.<anonymous> (~/err.ls:1:7)
    at Module._compile (module.js:643:30)
    at Module._compile (~/LiveScript/node_modules/source-map-support/source-map-support.js:492:25)
    at Object.LiveScript.run (~/LiveScript/lib/node.js:33:19)
    at compileScript (~/LiveScript/lib/command.js:186:31)
    at ~/LiveScript/lib/command.js:112:11
    at ~/LiveScript/lib/command.js:102:7
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
```

**Comment by rhendric** [comment]
It looks like this might have been caused by the fix for #900, but @vendethiel, you said that #900 may not be actually fixed? Should we revert #901 (which I think fixes this) and do something else about #900? Or double down on that change and rewrite it to take `o.watch` into consideration?

**Comment by vendethiel** [comment]
Did we try bumping jison to ..18?

**Comment by vendethiel** [comment]
Do note: this one issue is about *runtime errors*. #900 is something I hit with compile ones.

**Comment by rhendric** [comment]
Bumping jison makes sense to me, but I personally haven't tried anything; all I know about these bugs is what's in the bug reports. Maybe @summivox can weigh in? Otherwise, I'd be inclined to do that (remove the `.message` and bump jison) if it weren't for your report of lingering issues with #900, which makes me worry that I wouldn't notice if there were a regression here.

**Comment by summivox** [comment]
I haven't been following the development on either projects, but I'd recommend bumping dependency.
