### ISSUE TITLE
1.6.0 release planning

### ISSUE THREAD

**Issue by rhendric** [gkz/LiveScript#1016]
Particularly in light of #1005, but also given that a major language feature has landed in the form of #978, I think it's time to plan for an official minor version release.

The idea is to close out a small number of minor issues that are in flight, and then undertake a large update and cleanup of the documentation, which will take place on branch [gh-pages-next](/gkz/LiveScript/tree/gh-pages-next). When documentation is ready and a 1.6.0 tag is prepared, I'll ask @gkz to publish that to npm—assuming he likes what he sees, of course—after which I'll merge gh-pages-next to gh-pages.

I'm tracking in-flight issues [here](https://github.com/gkz/LiveScript/projects/1), but this issue is the place to add comments if you think there's something that really needs to be in 1.6 that hasn't been addressed yet. I will prioritize fixing things that have been broken either by the 1.5.0 release or since then, although I will also consider very small, backward-compatible improvements that are likely to benefit a large proportion of users.

**Comment by vendethiel** [comment]
The only thing I'd like to see for 1.6.0 would be fixes to error messages. I still need to do a bit of digging.

**Comment by willin** [comment]
pls prerelease a beta version

**Comment by rhendric** [comment]
@willin, why?

**Comment by rhendric** [comment]
I'm not very confident that I understand that comment, but if you're trying to say that you want access now to the new async/await support that will be released in 1.6, you can get that with `npm install github:gkz/LiveScript`. (Off the top of my head, I don't recall any other significant ES6-related features added to LiveScript since 1.5.)

**Comment by determin1st** [comment]
Is there any problems, add to livescript constructs like:

continue 2
break 2

to exit several (current and parent) `for` loops or `while`s?

**Comment by vendethiel** [comment]
I don't think any language other than PHP has it. Just use a label:

```livescript
:outer for b
  for c
    break outer if ..
````

**Comment by determin1st** [comment]
It is from procedural languages. It would be handy. No need to know label declaration and any conditions.

**Comment by vendethiel** [comment]
> It is from procedural languages

Pascal, C, C++, C# only have goto, not even labeled breaks. Java has labeled breaks.
What "procedural languages" are you speaking of?

**Comment by determin1st** [comment]
Oh, I don't remember. Maybe, yes, PHP only. I just encountered recently some case, where it can "eat" one comparison (if check). I think it is handy, less variables, less checks.

Here is the code:
```
        _getCssRuleProps = function(el, names) {
            var a, b, c, d = [], $i,$j,$k;
            ////
            // RULES
            // iterate css sheets
            a = document.styleSheets;
            for ($i = 0; $i < a.length; $i++) {
                // iterate sheet rules (security problems on Chrome)
                b = a[$i].cssRules;
                for ($j = 0; $j < b.length; $j++) {
                    // match rule
                    c = b[$j].selectorText;
                    if (el.matches(c)) {
                        // match rule classes
                        for ($k = 0; $k < names.length; $k++) {
                            if (c.indexOf('.'+names[$k]) < 0) {
                                break;
                            }
                        }
                        // add rule to the result
                        ($k >= names.length) && d.push(b[$j]);
                    }
                }
            }
...
```

It's in JS because i have to (making some GSAP modification). So.. you see that `break` and cycle check afterwards? that's what i mean.

**Comment by vendethiel** [comment]
I think with labels it is clearer. Anyway this should be a separate issue :).

**Comment by pepkin88** [comment]
Regarding the documentation, from what I remember, unary spread still presents the syntax from <=1.4, not the new one from 1.5.

**Comment by rhendric** [comment]
@pepkin88, yup, that's #866 and it's on the To Do list for this release.

**Comment by nazar-pc** [comment]
Am I correct that besides a few documentation updates nothing substantial code-wise stops 1.6.0 from shipping?

**Comment by rhendric** [comment]
Last call! I'm preparing to make a release tag in a week or so.

**Comment by determin1st** [comment]
hats off! :)

**Comment by pepkin88** [comment]
@rhendric just one more thing to consider, please: #1068 :)

**Comment by rhendric** [comment]
Soon! I unfortunately picked a week when gkz was on vacation to make the release tag, but he emailed me yesterday to let me know he'll take a look when he gets back.

**Comment by gkz** [comment]
It's published on npm!

Thank you to @rhendric and everyone who has contributed!

**Comment by rhendric** [comment]
Website is now updated; that should be everything that needed doing!
