### ISSUE TITLE
Documentation for `do` doesn't seem to explain the block case

### ISSUE THREAD

**Issue by vendethiel** [gkz/LiveScript#1018]
There's documentation for `do ->`, but the only mention of `f do...` is in the "CoffeeScript to LiveScript Conversion Guide". We should probably document it.

Preferably with a title like "operator do" or "do operator" (or both) so that it's easier to ^F-search.

**Comment by rhendric** [comment]
There's this in the [Functions](http://livescript.net/#functions) section:

> `do` allows you to do many things without adding extra parentheses.
>```ls
>pow do
>  1
>  2
>
>h 1 do
>  a: 2
>  b: 5
>```

Did you miss that, or do you mean something else?

**Comment by vendethiel** [comment]
I mean it should be made easier to search for. It's currently ungreppable.

**Comment by bartosz-m** [comment]
I second that.  In plugin for atom I want to make it easier for newcomers to understand LiveScript code. Because of the way documentation is written, right now I'm copy-pasting achieve this
![](https://raw.githubusercontent.com/bartosz-m/atom-ide-livescript/master/doc/assets/hover-screen.gif)
It would be rely useful to give `do` and every other livescript feature its own section in documentation that could be easily grepable.

**Comment by rhendric** [comment]
I don't want to embark on a total reordering of the docs, for a few reasons (time investment, lack of real expertise in writing excellent documentation, fear of overstepping my very informal collaborator mandate). I would consider doing something like adding a glossary or index section of keywords and symbols, with entries like:

* `default` — see [`switch`](#fake-link)
* [`delete`](#fake-link)
* [`delete!`](#fake-link)
* `do`
  * [before a function (`do -> ...`)](#fake-link)
  * [in the arguments to a function (`fn do ...`)](#fake-link)
* `else`
  * after loops — see [`while`/`until`](#fake-link)
  * alias for `default` — see [`switch`](#fake-link)
  * see [`if`/`unless`](#fake-link)

Would that be an acceptable substitute?

**Comment by bartosz-m** [comment]
any kind of index/glossary would be good and for current needs totally sufficient
