### ISSUE TITLE
We broke `lsc -c package.json.ls`

### ISSUE THREAD

**Issue by rhendric** [gkz/LiveScript#1022]
Now it compiles to stdout instead of `package.json`. I think this was caused by #995?

**Comment by vendethiel** [comment]
Probably. It doesn't help that we don't have any tests at all.

**Comment by rhendric** [comment]
We have some, in `test/cli.ls`. I'm adding more in a PR arriving shortly (in retrospect, this probably wasn't worth creating an issue for).
