### ISSUE TITLE
Expressions starting from `_` are treated as placeholders in `match` cases

### ISSUE THREAD

**Issue by pepkin88** [gkz/LiveScript#1025]
Example:
```LiveScript
match a
| _.isString => 1
| (_.isString) => 1
```

Result:
```js
var ref$;
switch (ref$ = [a], false) {
case !true:
  1;
  break;
case !_.isString(ref$[0]):
  1;
}
```

Expected result:
```js
var ref$;
switch (ref$ = [a], false) {
case !_.isString(ref$[0]):
  1;
  break;
case !_.isString(ref$[0]):
  1;
}
```

The example shows, that wrapping the expression in parentheses is enough to bypass this bug.

**Comment by rhendric** [comment]
Oh, `match`. The undocumented, largely untested, experimental feature that somehow people keep discovering anyway.

This sure does look like a bug, but I don't know whether this should be an error, your expected result, or something else. `_` has special meaning inside `match`, which is complicated by the fact that `_` is also used to create a partial-application function and as far as I know, every case of a `match` expression should be interpreted as a function (unless it isn't, like with constants).

I don't really intend to do anything to improve the state of `match`, unless someone feels like fully and properly specifying its behavior. The good news is, as an experimental undocumented feature, I also wouldn't feel even a tiny bit bad about ripping it out and replacing it with something else. You were all warned. :slightly_smiling_face:

**Comment by pepkin88** [comment]
OK, fair enough.

I drew an analogy to the partial application or switch's default, where only a standalone underscore has a special meaning. In those cases using `_.toString` wouldn't trigger anything special.

I might fix it later. For now, let this issue be a walk-around suggestion.

**Comment by pepkin88** [comment]
Related issue with a plausible use case scenario:

This:
```LiveScript
(_.isPlainObject || _.isArray) value
```
compiles to:
```js
true || true;
```
instead of:
```js
_.isPlainObject(value) || _.isArray(value);
```

Although I think this feature is a real gotcha and makes sense only in the context of `match`, it actually is documented.

**Comment by rhendric** [comment]
Ha, okay, you got me! This should be fixed.

**Comment by pepkin88** [comment]
This looks like an easy one I could tackle, but only from next week.

**Comment by rhendric** [comment]
I'll hold it for you then.

**Comment by anant-svc** [comment]
Hi, tried to get expected result @pepkin88 needed using below:
```
u = _
match a
| u.isString => 1
| (u.isString) => 1
```

Result:
```
var u, ref$;
u = _;
switch (ref$ = [a], false) {
case !u.isString(ref$[0]):
  1;
  break;
case !u.isString(ref$[0]):
  1;
}
```
