### ISSUE TITLE
Semiautovivification with a concat assignment produces an erroneous code

### ISSUE THREAD

**Issue by pepkin88** [gkz/LiveScript#1028]
Example:
```LiveScript
a[]b ++= [1 2]
```

Result:
```js
a.b || (a.b = []) = (a.b = []).concat([1, 2]);
```

Expected result:
```js
a.b = (a.b || (a.b = [])).concat([1, 2]);
```

The current behavior produces a code, which gives a runtime error `ReferenceError: Invalid left-hand side in assignment`.

---

The "expected result" block is a result of compiling:
(after merging #1026)
```LiveScript
a.b = a[]b ++ [1 2]
```
which is a simplification of (currently uncompilable):
```LiveScript
a[]b = a[]b ++ [1 2]
```
because the effects of semiautovivification are canceled by an assign.

**Comment by pepkin88** [comment]
The issue also applies to other assignments, but this one has a practical use case.

**Comment by determin1st** [comment]
that's the craziest syntax i've ever seen 8)
