### ISSUE TITLE
Better shebang support needed

### ISSUE THREAD

**Issue by nazar-pc** [gkz/LiveScript#1030]
Currently
```livescript
``#!/usr/bin/env node``
```
compiles to
```javascript
// Generated by LiveScript 1.5.0
#!/usr/bin/env node
(function(){

}).call(this);
```
I know there are options that allow to remove `Generated by` line as well as function wrapper, but I believe this should work properly even if those are not used.

Ideally, LiveScript should blindly preserve anything that is on the first line and starts with `#!`, without any need for backticks or additional CLI options.

TL;DR:
```livescript
#!/usr/bin/env node
console.log 'Hello'
```
should compile to
```javascript
#!/usr/bin/env node
// Generated by LiveScript 1.5.0
(function(){
  console.log('Hello');
}).call(this);
```
by default.

**Comment by rhendric** [comment]
Reopened due to [regression](/gkz/LiveScript/pull/1032#issuecomment-381212282).
