### ISSUE TITLE
Operator of modification

### ISSUE THREAD

**Issue by pier-bezuhoff** [gkz/LiveScript#1049]
I suggest to add the handy operator
`x %~ f`  === `x = f x`
like `over` in haskell lens library.
It somehow generalizes the `.=` to be more flexible

**Comment by rhendric** [comment]
Try `x |>= f`; does that do what you want? (In LiveScript, `x |> f` is `f x`, so `x |>= f` is `x = x |> f` is `x = f x`.)

**Comment by pier-bezuhoff** [comment]
Exactly, thanks!
