### ISSUE TITLE
Weird in optimization for arrays

### ISSUE THREAD

**Issue by danielo515** [gkz/LiveScript#1053]
Hello,

I know the code I'm going to poste does not makes much sense, but it's something that could happen.

I noticed that when you use `in` directly with an inline array it gets turned into a series of or comparisons, which is fairly good in my opinion. However, if the array is a single element then the helper function `$in` is injected and it's used instead. Just take a look at this input and the two different outputs:

```ls
name in ['Joe','John']
name in ['George']
```

```js
name === 'Joe' || name === 'John';
in$(name, ['George']);
function in$(x, xs){
  var i = -1, l = xs.length >>> 0;
  while (++i < l) if (x === xs[i]) return true;
  return false;
}
```

**Comment by rhendric** [comment]
Indeed, this should be fixed on master.

**Comment by danielo515** [comment]
Master is not yet published, right?

**Comment by rhendric** [comment]
Right, master is the bleeding edge of development. It's easy to use in your package.json file by depending on `gkz/LiveScript`.
