### ISSUE TITLE
Make parenthesis optional on lambdas

### ISSUE THREAD

**Issue by danielo515** [gkz/LiveScript#1056]
There was a time when lambda on livescript were much more succinct than on javascript. That is no longer the case :

```
(A, B) => A+B
(a, b) -> a + b
```

In the case of curried functions javascript is even shorter
```
A => B  => A+B
(a) - > (b) -> a + b
```

I was wondering how hard would be to make parentheses optional on function declarations, at the end you must add an equals sign before and am arow after

**Comment by rhendric** [comment]
Sorry, I don't think removing the parameter parentheses can work in LiveScript, because `a -> b` is already an expression that means `a(function () { return b; })`. Changing that would break a *lot* of code.

**Comment by danielo515** [comment]
What if you do only for function declarations ?

**Comment by rhendric** [comment]
`f = a -> b` has the same problem; it already means `f = a(function () { return b; })`. For [named function declarations](http://livescript.net/#functions-named), the parentheses are already optional.
