### ISSUE TITLE
bracket spacing threw unexpected error in function invocation

### ISSUE THREAD

**Issue by sourcevault** [gkz/LiveScript#1058]
```livescript

a = 1
b = 2

f = (x,y) -> x + y

f (a,b) # throws error :(

```

I was quite surprised that this caused parse error :|

```
Function {
  message: 'Parse error on line 1: Unexpected \',\'',
  hash:
   { text: undefined,
     token: ',',
     line: 0,
     loc: { first_line: 0, first_column: 3, last_line: 0, last_column: 4 },
     expected:
      [ '\'BIOP\'',
        '\')\'',
        '\'BIOPR\'',
        '\'BACKTICK\'',
        '\'NEWLINE\'',
        '\'INDENT\'',
        '\'IMPORT\'',
        '\'+-\'',
        '\'COMPARE\'',
        '\'LOGIC\'',
        '\'MATH\'',
        '\'POWER\'',
        '\'SHIFT\'',
        '\'BITWISE\'',
        '\'CONCAT\'',
        '\'COMPOSE\'',
        '\'RELATION\'',
        '\'PIPE\'',
        '\'BACKPIPE\'',
        '\'POST_IF\'' ] } }
```

**Comment by sourcevault** [comment]
I am trying to do a normal function call like so :

```
f a,b # no error 
```

**Comment by rhendric** [comment]
Welcome to LiveScript! It's true, `f (a, b)` is not valid and is not intended to be so. LiveScript is a very whitespace-sensitive language. For example, there is a big difference between `a[b, c]` and `a [b, c]`—the former will compile to `[a[b], a[c]]`, while the latter will compile to `a([b, c])`. By analogy, `f (a, b)` would mean to apply `f` to whatever `(a, b)` means, but as ven observes, the expression `(a, b)` doesn't mean anything in LiveScript, so this is an error, whereas `f(a, b)` is valid (as is `f a, b`, as you observe).
