### ISSUE TITLE
Deprecate `^` operator

### ISSUE THREAD

**Issue by pepkin88** [gkz/LiveScript#1068]
Why:
- it's an alias for `**`, which is now a part of ECMAScript and therefore suits more the JS ecosystem
- refactoring the code to change to `**` is easy, in most of the cases simple search/replace is enough
- exponentiation isn't that common, doesn't need 2 operators for the same thing
- `^` could be more useful for other things, especially when it's only 1 character long

Examples of future usage of `^`:
- type annotation? (although ` :: ` seems to be more popular option)
- [private](https://github.com/tc39/proposal-private-methods) [field](https://github.com/tc39/proposal-class-fields#private-fields) [sigil](https://github.com/tc39/proposal-static-class-features/)? Private fields, methods and accessors are already on [stage 3](https://github.com/tc39/proposals#stage-3), people seem to be interested in those features; JS proposes `#`, which wouldn't work in LS, for obvious reason. Of course JS class support is required for it.
- something different?

I'm not sure what for and when it will be used, but I think it's better to prepare for it by deprecating it first. The earlier, the better, that's why I think maybe even for v1.6.0. I have prepared code for a PR with a deprecation warning, in case it's needed.

Thoughts?

**Comment by rhendric** [comment]
If this were rhendric/LiveScript, I would consider doing this. But having `^` as an alias for `**` was advertised by gkz as one of the earliest changes differentiating LiveScript from Coco. He's seen fit to remove features from that era, but as a guy who is just stewarding someone else's language, I don't feel right doing so unless there's an obvious flaw in the feature that needs correcting—gkz liked having `^`, and maybe some other early adopters of LiveScript did too, and I'm not going to mess with that on a speculative basis.

**Comment by determin1st** [comment]
future of pseudo-classical inheritance? no, please, lets deprecate classes)

**Comment by pepkin88** [comment]
We could ask him, right? Nope? I know he's busy, so I don't know if it's "worthy" enough issue to mention him.

Regarding pseudo-classical inheritance - it's just an example, and you don't need to use any inheritance related features to make use of private fields. Classes can be used without inheritance.

**Comment by rhendric** [comment]
I do think, if I were to get only one get-a-gkz-opinion-free card, I would definitely use it on [some](983) [other](1000) [issue](1038) than this one. But as far as I know that isn't the case, and I haven't really tried summoning him since he gave me collab bits, so suuure, why not I guess? Let's see if he feels like weighing in!

&lt;stands before mirror&gt; gkz, gkz, @gkz?

**Comment by vendethiel** [comment]
I don't see a point of keeping `^`. Of course we'd need a deprecation period.
