### ISSUE TITLE
How to start repl during runtime?

### ISSUE THREAD

**Issue by anhnhoktvn** [gkz/LiveScript#1092]
How do I start new REPL session by code during runtime?

**Comment by ceremcem** [comment]
In browser or in a server side script?

**Comment by rhendric** [comment]
The LiveScript programmatic API is documented [here (scroll past the CLI sections)](http://livescript.net/#usage). In Node.js or in the browser, it's pretty easy to build a simple REPL from that API, and this is what the livescript.net website does.

The REPL that you get when you run `lsc` is not publicly exposed; its implementation is coupled to the Node.js REPL module and several other bits of Node.js functionality, and its interface is not stable. You can technically figure out how to run it in Node.js by reading the LiveScript code, but I wouldn't advise it. You probably can't run it in the browser, at least without doing some fussy module shimming.
