### ISSUE TITLE
Destructuring optional object in array produces invalid javascript

### ISSUE THREAD

**Issue by LeXofLeviafan** [gkz/LiveScript#1096]
The code `([{foo}?]) ->` produces following output:
```js
(function(arg$){
  var ref$, foo;
  (ref$ = arg$[0]) != null && foo = ref$.foo;
});
```
Which fails to evaluate because of `&&` before assignment.

At the same time, `([{foo, bar}?]) ->` doesn't fail, because resulting output is taken in parens:
```js
(function(arg$){
  var ref$, foo, bar;
  (ref$ = arg$[0]) != null && (foo = ref$.foo, bar = ref$.bar);
});
```
More to the point, optional object _with alternative_ (`([{foo}={}]) ->`) doesn't fail either, because there's no right-side assignment:
```js
(function(arg$){
  var ref$, foo;
  foo = ((ref$ = arg$[0]) != null
    ? ref$
    : {}).foo;
});
```
And adding more fields (`([{foo, bar}={}]) ->`) results in a comma chain, as usual:
```js
(function(arg$){
  var ref$, foo, bar;
  ref$ = (ref$ = arg$[0]) != null
    ? ref$
    : {}, foo = ref$.foo, bar = ref$.bar;
});
```

**Comment by rhendric** [comment]
Looks like a valid bug to me, although there's a small possibility I'll change my mind after a closer read of the docs.

**Comment by pervert160** [comment]
#1115 #1115
