### ISSUE TITLE
Incorrect if JavaScript depending on context

### ISSUE THREAD

**Issue by LeXofLeviafan** [gkz/LiveScript#1098]
When compiling the code `x = (if foo! then bar(that) or baz(that))` (that is, relying on if-let to locally bind result of the first subexpression), the resulting JavaScript looks like this:
```js
x = (that = foo()) ? bar(that) || baz(that) : void 8;
```
Which works pretty straightforwardly, as one would expect. If, however, you pass the same exact expression to, say, `while` loop, the output will have different structure:
```livescript
while (if foo! then bar(that) or baz(that))
  console.log 42
```
```js
while ((that = foo()) && bar(that) || baz(that)) {
  console.log(42);
}
```
Which deviates from expected behaviour, because now `baz` will be executed even when `that` is falsey (due to JavaScript operator precedence).
It _is_ possible to reproduce structure from the first example in second case, but only by providing an explicit `else` branch:
```livescript
while (if foo! then bar(that) or baz(that) else void)
  console.log 42
```
```js
while ((that = foo()) ? bar(that) || baz(that) : void 8) {
  console.log(42);
}
```

**Comment by rhendric** [comment]
I'm really glad you reported this. I remember when I was investigating #1096, I noticed the code that caused this issue and idly wondered how it was that it worked. _It can't be broken,_ I thought; _surely someone would have reported that bug!_ So much for that flawless reasoning. :grimacing:
