### ISSUE TITLE
Bitwise "xor" is ditched

### ISSUE THREAD

**Issue by punund** [gkz/LiveScript#1100]
The JavaScript operator `^` has got another, unrelated meaning.

JavaScript:
```js
0x10 ^ 0x1A // 10
```

LiveScript:
```js
0x10 ^ 0x1A // 2.028240960365167e+31
```

I have three problems with this.

1. Obviously, this is quite confusing.
2. `^` is an alias for another operator (`**`) and is not necessary (and there is `Math.pow()` too).
3. We are left without bitwise `xor`.

**Comment by gkz** [comment]
Lookup "Bitwise and shift operators" under http://livescript.net/#operators

```
0x10 .^. 0x1A
```
