### ISSUE TITLE
`/` operator for nodejs's path.join

### ISSUE THREAD

**Issue by bung87** [gkz/LiveScript#1106]
the current implementation is spliting string, I think path.join is more often than split, also for path.join reduce more charactors than split which more usefull.

**Comment by rhendric** [comment]
At this point, backward-incompatible changes like this would need very strong justifications to be considered (basically, the existing feature to be broken has to be seriously flawed). I'm not sure either of these idiosyncratic overloads of `/` is objectively better than the other (although your proposal has the disadvantage that it has no use outside of Node.js), but certainly this is not *so* much better to justify breaking existing code. So sorry, but this isn't something that will happen.
