### ISSUE TITLE
How can we generate simple "for loop"s when iterating through lists?

### ISSUE THREAD

**Issue by ceremcem** [gkz/LiveScript#1119]
I need to generate the following output, wher `i` is from `[0 to 5]`: 

```js
demo = async function() {
  for (let i = 0; i < 5; i++) {
    console.log(`Waited ${i} seconds...`);
    await sleep(1000);
  }
  console.log('Done');
}
```

What is the Livescript equivalent of above Js code?

**Comment by ceremcem** [comment]
Thanks for the answer.

Is there any use case where `for i in [x to y]` form is preferable over `for i from x to y` form? If there isn't any, can I explicitly forbid the `i in [x to y]` form in my applications?

**Comment by rhendric** [comment]
I can't think of any case where the former is better, no.

**Comment by ceremcem** [comment]
FYI: 

For those who wants to refactor the entire project to get rid of `for i in [x to y]` like usages:

```sh
find . -name "*.ls" -and -not -path "*/node_modules/*" | xargs grep -PHn 'for\s+\w+\s+in\s+\[(?!(\d+\s+(to|til)\s+\d+)).*\]'
```

The regex and its test cases are here: https://regex101.com/r/Bj9pZE/1

**Comment by sourcevault** [comment]
> FYI:
> 
> For those who wants to refactor the entire project to get rid of `for i in [x to y]` like usages:
> 
> ```shell
> find . -name "*.ls" -and -not -path "*/node_modules/*" | xargs grep -PHn 'for\b.*\s\[(?!(\d+\s+(to|til)\s+\d+)).*\]'
> ```
> 
> The regex and its test cases are here: https://regex101.com/r/Bj9pZE/3

better to do it manually, no ?

**Comment by ceremcem** [comment]
> better to do it manually, no ?

Yes. The Regex pattern is quite basic, but it works for me. I decided to integrate it into my build tool, so a warning message can be displayed via a popup as the project is saved.
