### ISSUE TITLE
"it 'test', -> ..." does not compile as expected, because it gets shadowed

### ISSUE THREAD

**Issue by markmarijnissen** [gkz/LiveScript#133]
``` CoffeeScript
describe 'Testing with Mocha or Jasmine', ->
    it 'should be possible to run this code', ->
        expect true .to.be true  # test should pass
```

JavaScript:

```
describe('Testing with Mocha or Jasmine', function(it){
  return it('should be possible to run this code', function(){
    return expect(true).to.be(true);
  });
});
```

`it` cannot be called because it now refers to the function argument, instead of the (globally) defined function.

possible work-a-round to prevent the automatic insertion of `it` as default argument:

``` CoffeeScript
describe 'Testing with Mocha or Jasmine',(x) ->
    it 'should be possible to run this code',  ->
        expect true .to.be true  # test should pass
```

Just define the function with a dummy argument.

I don't have any solution in mind, but I'd just wanted to inform you about this issue, and give a solution for people who stumble on the same problem.

**Comment by chrisvfritz** [comment]
Another workaround that I use in my tests:

``` livescript
describe '...' (_) !->
```

This way, the implicit `it` is never assigned.

**Comment by igl** [comment]
or simply use another interface `mocha --ui tdd` instead of the default bdd interface. 

    The TDD interface provides suite(), test(), suiteSetup(), suiteTeardown(), setup(), and teardown():
