### ISSUE TITLE
Allow sub array destructuring within object comprehension

### ISSUE THREAD

**Issue by vendethiel** [gkz/LiveScript#145]
Nothing important - got this little idea editing prelude's source :

`{x[0 1] for x in xs}`
`{e<[key value]> for e in elements}`

**Comment by LeXofLeviafan** [comment]
…There's no object comprehension syntax in the first place, though?

**Comment by vendethiel** [comment]
What's `{[.., ..] for <[a b c]>}` then?

**Comment by LeXofLeviafan** [comment]
…Oooh, I see what happened here.
I tried to make a simple comprehension based on presented syntax and it failed.
Turns out, `{x for x in xs}` (and `{.. for xs}`) also don't work.
