### ISSUE TITLE
Idea: Improve typeof

### ISSUE THREAD

**Issue by jasonkuhrt** [gkz/LiveScript#178]
Question:

Why does `typeof! [1,2,3]` return 'Number'?

Idea:

Can we interchange `typeof` and `typeof!` so that the operator we know and hate can become the operator we know and love? The lesser of the two should be hidden behind alt syntax.

My only concern is not being able to `typeof` arrays as questioned above.

**Comment by rhendric** [comment]
After (the still undocumented, alas) #863, it doesn't seem like there are any outstanding needs here, so I'll reclose.

**Comment by determin1st** [comment]
it's not well documented what typeof! returns
