### ISSUE TITLE
Embedding JavaScript inside livescript similar to coffeescript option

### ISSUE THREAD

**Issue by cocodrino** [gkz/LiveScript#214]
coffeescript let Embedding javascript using backcuotes:

```
`function greet(name) {
  return "Hello "+name;
}`

#Back to CoffeeScript
greet "Coffee"
# => "Hello Coffee"
```

is it possible with livescript
thanks!!...

**Comment by JoyKrishnaMondal** [comment]
![untitled](https://cloud.githubusercontent.com/assets/3383928/6091022/577e59b2-ae8e-11e4-8895-4e78d97ea87c.jpg)

I really like LiveScript, but sometimes you need to write code for canvas that needs to be really fast.

**Comment by vendethiel** [comment]
That's the code LS would generate with `for x to 640*480`, though.

**Comment by blvz** [comment]
Call me old fashioned but, what's wrong with `require`?

**Comment by vendethiel** [comment]
@JoyKrishnaMondal we have `while COND; STEP` in LS as well.
