### ISSUE TITLE
Allow binding of partially applied operator functions

### ISSUE THREAD

**Issue by quarterto** [gkz/LiveScript#269]
I keep finding myself wanting to use ```(.a is @b)``` but of course it doesn't work. I have to fall back on ```~>it.a is @b``` (or ```(.a is this$.b)```, *shudder*). Can we have something like ```~(.a is @b)```?

**Comment by vendethiel** [comment]
@gkz should every section be this-bound (we'd need to traverse the body to conditionally add it, maybe)

**Comment by vendethiel** [comment]
I know this is the oldest, but the other one got more reactions, so #634.
