### ISSUE TITLE
Idea: Type Inference

### ISSUE THREAD

**Issue by goatslacker** [gkz/LiveScript#30]
Have you thought about adding some sort of optional type system along with type inference?

[Roy](http://roy.readthedocs.org/en/latest/index.html) has types.

This can also be something similar to [contracts.coffee](http://disnetdev.com/contracts.coffee/), except the type checking happens at compile time instead of runtime so you don't get the performance hit.

**Comment by ozra** [comment]
I'm longing for types. Now that it really is starting to popup both here and there in the JS community, compatibility of type system become something to have in mind - for cross-module type-checking. I do like what I've seen so far in the Flow concept. If say Flow was to take on, and an eco system of modules would grow, it would be nice to be compat with that. 
In any event I'd prefer a type system that does static checking only by default, and optionally has RTTI as an option for dev/debug-builds.

**Comment by robotlolita** [comment]
You don't need to reify type information unless you want to make that available for reflection.

**Comment by ozra** [comment]
@robotlolita - think "non type aware foreign modules that may or may not behave" and own 'smart dynamic code' that may or may not behave in dev. phase.
@igl - afaiu FlowType also has type unions

Some of my loose opinions:

#### FlowType
- pros: Primitive types (also strings in this context) are not considered descendants of `Object`. `mixed` or `any` takes primitives or objs. 
- cons: Too lenient, the same identifer is allowed to change type, even implicitly, in the same context:
```
a = 4
a += 43
a = "4"
a += "7"
```

#### TypeScript
- pros: allowing widening or change of type must be explictly stated, the "narrower path" is the implicit one
- cons: Sticking with JS native ideology of all types being descendants of Object, which in the type-checking situation is not the primary want imo. That types `Object`, `{}`, `any` all practically mean the same thing doesn't tick with me.

Just my 2 mBTC.

**Comment by jwinnie** [comment]
What's the status of this now?

**Comment by igl** [comment]
![image](https://user-images.githubusercontent.com/293519/44019834-3ce43a54-9ee0-11e8-8f53-8c39277ad6bb.png)
