### ISSUE TITLE
FR: Allow property setting shorthand (for objects literals) with 'multiple dots' access

### ISSUE THREAD

**Issue by ymeine** [gkz/LiveScript#301]
Hi all,

I like the property setting shorthand feature for object literals, which is (to remind you): 

``` livescript
{
    a
    b
    c.x
    c.y
}
```

compiling to 

``` javascript
{
  a: a,
  b: b,
  x: c.x,
  y: c.y
}
```

However, I've been surprised not being able to do something like: 

``` livescript
{
    a.b.c
    x.y.z
}
```

to compile to

``` javascript
{
    c: a.b.c,
    z: x.y.z
}
```

as this however seems intuitive: simply take the last part of the property access as the property name, like `(whatever-I-do-to-reach-the-value).property`, giving `property: (whatever-I-do-to-reach-the-value).property`.

With a real example: 

``` livescript
{
    JSON.parse input .property
}
```

would give: 

``` javascript
{
    property: JSON.parse(input).property
}
```

FYI, the first non-working example I gave you (with simple _multiple dots_ access) triggers the following error: `Parse error on line 2: Unexpected 'DOT'`

While the last one gives: `Parse error on line 2: Unexpected 'CALL('`

Best regards

**Comment by rhendric** [comment]
Implemented in #958.
