### ISSUE TITLE
Erlang-like function notation

### ISSUE THREAD

**Issue by dfcreative** [gkz/LiveScript#312]
```livescript
add(a, b) ->
		a + b
```

Now it compiles to dubious:
```js
add(a, b)(function(){
  return a + b;
});
```

It would be better to have named function instead:
```js
function add(a, b){
 return a + b
}
```
Just suggestion.

Another idea: function clauses & guards. It would be super-useful to write clauses that way:
```livescript
color: ->
 @get 'color'

color: (el) when el instanceof "element"  ->
 @set 'color', @parse window.getComputedStyle(prop)['background-color']

color: (prop) ->
 @set 'color', @parse prop
```
It complies to current syntax of guards.

**Comment by vendethiel** [comment]
I'll go ahead and close this, since this would require a "sealed"-like keyword for our functions.
