### ISSUE TITLE
Splat for object desctructuring

### ISSUE THREAD

**Issue by dfcreative** [gkz/LiveScript#315]
Splat in the object destructuring could work in the same manner as in list:

``` ls
# List destructuring
[head, ...tail] = [1 to 5]
head #=> 1
tail #=> [2,3,4,5]

# Object destructuring proposal
{a, b, ...rest} = {a:1, b:2, c:3, d:4}
a #=> 1
b #=> 2
c #=> {c:3, d:4}; Now => {}
```

**Comment by Sod-Almighty** [comment]
Almost three years later......any chance of this feature? I have a current need for it.

**Comment by rhendric** [comment]
This has been implemented on master already (but not released yet).

```ls
{a, b, ...rest} = {a:1, b:2, c:3, d:4}
```
becomes
```js
var ref$, a, b, rest;
ref$ = {
  a: 1,
  b: 2,
  c: 3,
  d: 4
}, a = ref$.a, b = ref$.b, rest = copyWithout$(ref$, {
  a: 0,
  b: 0
});
function copyWithout$(src, ex){
  var obj = {}, own = {}.hasOwnProperty;
  for (var key in src) if (own.call(src, key) && !own.call(ex, key)) obj[key] = src[key];
  return obj;
}
```

**Comment by Sod-Almighty** [comment]
Pardon me, but it doesn't seem to be implemented. When I use the current master [livescript.js](https://github.com/gkz/LiveScript/blob/master/browser/livescript.js) file (via [livescript-source](https://github.com/Roonin-mx/livescript-source), via [livescript-ruby](https://github.com/Roonin-mx/livescript-ruby)), I get the following:
```
!~function perform-post-action {success-fn, error-fn, ...args} = {}
  ...code...
```
```
function performPostAction(arg$){
  var ref$, successFn, errorFn, args, x$;
  ref$ = arg$ != null
    ? arg$
    : {}, successFn = ref$.successFn, errorFn = ref$.errorFn, args = import$({}, ref$.args);
  ...code...
```

**Comment by rhendric** [comment]
The `browser/livescript.js` file only gets rebuilt when there's about to be a release, I'm afraid. If you clone this repository, you can rebuild it yourself with `make build-browser`.

**Comment by Sod-Almighty** [comment]
Thanks, but that doesn't work:
```
# make build-browser
{ ./scripts/preroll ; node_modules/.bin/browserify -r ./lib/browser.js:livescript ; } > browser/livescript.js

/root/LiveScript/lib/index.js:8
parser.yy = ast;
          ^
TypeError: Cannot set property 'yy' of undefined
    at Object.<anonymous> (/root/LiveScript/lib/index.js:8:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/LiveScript/scripts/preroll:3:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
/bin/sh: 1: node_modules/.bin/browserify: not found
Makefile:23: recipe for target 'browser/livescript.js' failed
make: *** [browser/livescript.js] Error 127
```

**Comment by rhendric** [comment]
It looks like you may have screwed up your checkout (LiveScript compiles itself from itself, so if your `lib` directory ever gets garbage in it, you need to check it out fresh again). Also, it looks like you might be new to Node.js.

Try cloning a new repository, running `npm i` first this time (that installs all the Node.js package you need), and then running `make build-browser`.

**Comment by Sod-Almighty** [comment]
Awesome, thank you.

Yeah, I'm using Livescript via Ruby, so my experience with `node` is pretty much non-existent.
