### ISSUE TITLE
Feature Request: map, filter, fold, zip and other functional operators

### ISSUE THREAD

**Issue by viclib** [gkz/LiveScript#319]
Considering how those are recurrent functions in FP, I propose we could have operators for them.

`[1 to 5] :> (^2)` => [1 4 9 16 25]
`[1 to 5] ?> (>3)` => [4 5]
`[1 to 5] <> (+)` => 15
`[1 2 3] &> [4 5]` => [[1 4] [1 5] [2 4] [2 5] [3 4] [3 5]]
`[dog1, dog2] .> bark!` => [dog1.bark(), dog2.bark()]

This way, 

`[1 to 5] |> map (^2) |> filter even |> fold (+), 0`
becomes
`[1 to 5] :> (^2) ?> even <> (+)`

`strs |> map (.toUpperCase!)`
becomes
`strs.>toUpperCase!`

**Comment by rightfold** [comment]
Speaking of APL programmers, I propose allowing embedding of APL code in LiveScript:

    sort←{1≥⍴⍵:⍵⋄p←⊃⍵⋄r←1↓⍵⋄(∇r/⍨r≤p),p,(∇r/⍨r>p)}
    [1 to 10] |> shuffle |> map (* 10) |> sort |> console.log

**Comment by phanimahesh** [comment]
I could never program in APL, but just for the lulz, APL in ls sounds great! :P

**Comment by ozra** [comment]
Yaeh, I'd loove to debug that code!

2015-05-02 16:25 GMT+02:00 J Phani Mahesh <notifications@github.com>:
