### ISSUE TITLE
Livescript supports piping |> but doesn't support multiple args

### ISSUE THREAD

**Issue by askucher** [gkz/LiveScript#376]
Hi 

Are you going to add 2,3 arguments piping  ||> and |||> ?

**Comment by vendethiel** [comment]
@gkz, let's close this?

**Comment by gkz** [comment]
Actually, I'm not sure about this one. I don't want to add a new operator - but this once seems like a nice one.

**Comment by hrobeers** [comment]
Any update on this?
I started using LiveScript for it's pipe operator, but apparently it doesn't work :(

**Comment by vendethiel** [comment]
it works. it just doesn't have multiple arguments versions.

**Comment by hrobeers** [comment]
Exactly my point, it's useless without multiple argument support.

**Comment by vendethiel** [comment]
YMMV :).

**Comment by hrobeers** [comment]
Currying will do, but it's more verbose.
Multiple from arguments aren't needed I agree.

**Comment by JoyKrishnaMondal** [comment]
Piping will get confusing if you are passing multiple arguments - that case its better either to define some type or use use a function.

**Comment by hrobeers** [comment]
Coming from elixir, I never found multiple arguments confusing as long as you name you functions properly.

Just a simple example:
```
4 |> MultiplyBy 2
8
```

In LiveScript, this would require you to curry the function to become:
```
4 |> MultiplyBy2
8

```

Like you see there is no real difference in readability but LiveScript would require more code because of the currying.

**Comment by vendethiel** [comment]
You can just use `foo |> bar 2, _`

**Comment by hrobeers** [comment]
Hmm, so you mean that
```
4 |> MultiplyBy 2, _
```
will just work?

That's good, I might be to new to LiveScript to have realized this.
Thanks

**Comment by vendethiel** [comment]
yes

**Comment by WreckedAvent** [comment]
You can also use an eta conversion, like in other languages with piping. Therefore, all of the following forms are functionally equivalent: 

    4 |> -> MultiplyBy 2 it
    4 |> (x) -> MultiplyBy 2 x
    4 |> MultiplyBy 2 _

Personally, not too crazy about multiple-arg piping. Languages like F# get along just fine without it, while thoroughly relying upon it.

**Comment by vendethiel** [comment]
Eta-conversion is broken in JS (`a.b`)

**Comment by hrobeers** [comment]
Thanks guys, I guess I misunderstood the whole issue.
It's working perfect for me now. I'm really enjoying it!
Thanks for creating this wonderful project.

**Comment by WreckedAvent** [comment]
@vendethiel Eta *reductions* are broken in JS, but lifting works fine, like my examples
