### ISSUE TITLE
Cannot import 'livescript' with newer versions of node.js due to package name mismatch.

### ISSUE THREAD

**Issue by naturalethic** [gkz/LiveScript#379]
As the module name is 'livescript', and the npm package name is 'LiveScript', it is no longer being found when require('livescript') is invoked.  If the package installed in node_modules is renamed from 'LiveScript' to 'livescript', it works.

Suggest renaming the npm package to 'livescript'.

**Comment by mnn** [comment]
Years passed and it is still an issue. Your [page says](http://livescript.net/#installation) `var LiveScript = require("livescript");` yet only `require("LiveScript")` works. This could discourage a lot of potential users, because it looks just bad when you can't even run first thing from official site you try. If you don't plan to change it soon then I suggest making a note with alternative (currently working) snippet.

**Comment by naturalethic** [comment]
Make sure to `npm install livescript`  -- lowercase.

**Comment by mnn** [comment]
Oh, thank you for your response. But I forgot to mention that I am trying the web version (served from [cdnjs](https://cdnjs.com/libraries/livescript) in version 1.4 which seems to be the most recent one). From your comment I assume the issue only remained in the web version.

**Comment by naturalethic** [comment]
Ok, I'm not familiar with `require` libraries on the client.  The exported value from the module is essentially anonymous, is it not?  On the server, the imported name is the same as the module directory name.  Someone else perhaps can help.

**Comment by vendethiel** [comment]
We might need to update the bundled version.

It's a bad idea in general to use the cdn version, unless you need users to input LS code.

**Comment by mnn** [comment]
> It's a bad idea in general to use the cdn version

Yeah, I know. I only wanted quickly hack together some prototype in plunker and I just found out that they no longer support LiveScript natively :disappointed:.

**Comment by rhendric** [comment]
The browser module name was lowercased in b8ff683, which unfortunately hasn't been released yet.

**Comment by vendethiel** [comment]
Ah, I knew I remembered such an issue, but couldn't find it on mobile.

**Comment by naturalethic** [comment]
@mnn codepen.io supports livescript

**Comment by mnn** [comment]
Glad to hear it's fixed. @naturalethic Thanks for tip, I'll definitely try it.
