### ISSUE TITLE
--no-header option to prevent lsc -c from generating header comment

### ISSUE THREAD

**Issue by clkao** [gkz/LiveScript#404]
use case:

```
``#!/usr/bin/env node``
```

in cmd.ls which is to be compiled to cmd.js for npm package.

how about lsc -c --no-header for this?

**Comment by gabeio** [comment]
why was this closed and yet available:
```bash
lsc -wbc --no-header *.ls
```

**Comment by quarterto** [comment]
@gabeio there's a workaround, see @robotlolita's comment. Not every feature request has to be implemented.

**Comment by gabeio** [comment]
I stated that it was available unless I am misunderstanding something... @clkao was just asking for no `// Generated by ` when using 
```LiveScript
  ``#!/usr/bin/env node``
```
by using `$ lsc -c --no-header *.ls` but it does that already correct?

**Comment by quarterto** [comment]
Right, sorry, I misread. If `--no-header` is available, and this issue is asking for `--no-header` to be implemented, what's the problem?

**Comment by gkz** [comment]
@gabeio, this feature works as of LS 1.3

**Comment by gabeio** [comment]
I was just double checking and when it was closed I was wondering why without a real ending but never mind I was just being tired this morning :zzz:
