### ISSUE TITLE
Livescript to Typescript

### ISSUE THREAD

**Issue by askucher** [gkz/LiveScript#408]
Hi. 

It is good to have such possibility to obtain instead of JavaScript an TypeScript after compilation for checking types

example 

``` Livescript
const i@int = 1

const fun@int = (i@string, t@int)->


```

Converts to 

``` Typescript
var i:int = 1

function fun(i:string, t:int):int { }

```

It will help to solve huge amount of issues during development process.

**Comment by Neftedollar** [comment]
@gkz  will you add type checking to livescript? so many people  forced  to use typescript but it so oop.
