### ISSUE TITLE
Source maps?

### ISSUE THREAD

**Issue by drozzy** [gkz/LiveScript#452]
Forgive me if this is a repeat but I didn't find any issues about this.

Does LiveScript compiler support generating source maps?
The reason I ask is because both coffeescript and TypeScript seem to [support](http://net.tutsplus.com/tutorials/tools-and-tips/source-maps-101/) it.

**Comment by fuzzthink** [comment]
+1

**Comment by demux** [comment]
+1

**Comment by modo-lv** [comment]
+1

**Comment by vendethiel** [comment]
"+1"s are not helping, really.

**Comment by blvz** [comment]
It's hard to express how "+1"s are a annoying and disrespectful, without sounding rude.
GitHub already have a "+1 button". It's on the right side of the Star/Unstar button.

**Comment by Diggsey** [comment]
Well with the lack of a voting system for issues, there's no other way to express community interest in a particular issue. Forking is not a solution.

Regardless, I'm going to take a stab at implementing this, since it's about time LiveScript got sourcemaps...

**Comment by vendethiel** [comment]
If there's no developer interest in a specific feature, then community interest is a bit moot.

**Comment by seanstrom** [comment]
I believe this feature has been road mapped already. #260 
I think part of the hold up is that LiveScript is/was meant to be re-written on top of CoffeeScript-Redux compiler which has source map support already. If anyone is interested in helping with source maps, looking into that would be helpful.

**Comment by vendethiel** [comment]
> f CoffeeScript-Redux compiler which has source map support already

If you have the energy to work on both, do it

**Comment by seanstrom** [comment]
I thinks thats fair to feel that way, and I hear where you're coming from.
So what would be the best way for me to help the project?

We all keep asking for this feature, but there's all this underlining work that needs to be done before that can happen. What areas would ideally be addressed first before Source Map support?

I would be willing to work on various things if it meant we would eventually be able to add this.

**Comment by am11** [comment]
My two cents here: Sweet.js is another superset language of JavaScript, which makes use of an npm module called `source-map`, which has all the mechanics to generate source-maps. If you want to consume to keep concerns separated, you would probably just need to hook it with your complier internals.

Sweet.js: https://github.com/mozilla/sweet.js.
source-map: https://github.com/mozilla/source-map.

**Comment by vendethiel** [comment]
#481

**Comment by gkz** [comment]
I don't mind the `+1`s.
I don't have the time to commit the working on this complicated feature, however, I think I'm pretty good at merging in pull requests and if anyone would like to work on it and submit a pull request that would be great. The `+1` just signify to any potential contributor that their work in creating a pull request would greatly be appreciated.

**Comment by igl** [comment]
Isn't it about time to start on LS2 now that CSR is somewhat stable and ES6 is coming up?
Many breaking changes could be made. I am thinking about es6 modules, let and native const support.
Would it be clever to make such a heavy investment in 1.3 now?

**Comment by Diggsey** [comment]
As you can see, I've just submitted a PR which adds basic source-map support. It could do with a lot more testing though (hint hint, everyone who +1ed this!) and it's only fairly rough at the moment.

**Comment by demux** [comment]
:+1: Suddenly this is all happening so fast! :D

**Comment by blvz** [comment]
> :+1: Suddenly this is all happening so fast! :D

That's why I think a fork is useful while +1s are just noise: They get things moving.

**Comment by demux** [comment]
Bitching about +1s is noise...

**Comment by blvz** [comment]
@demux No. Explaining why people should contribute more, with no fear, instead of just asking for things. You've missed my whole point.

**Comment by demux** [comment]
@blvz So you think that people are afraid to contribute? If that's the case at least some of the time, then obviously they shouldn't be afraid.
But I'm saying; asking for something isn't a bad thing. I believe that many of the people asking for features are them selves active, contributing members of the open source community.

**Comment by blvz** [comment]
@demux I think *most people* are. But maybe "fear" wasn't the right word to describe it. Most people in user-land don't have the **motivation** to give it a go. While I agree that asking isn't a bad thing, there are better ways to do it.

But hey, that's just my opinion, which I've thought it was worth sharing (while I do "bitch" about every +1s, in silence). Anyone's welcome to disagree and even **gkz** said he's ok with the +1s, so this discussion already did more noise than the +1s themselves.
