### ISSUE TITLE
If/else with empty block

### ISSUE THREAD

**Issue by wallverb** [gkz/LiveScript#488]
Would it be possible to make compiler work with the following input?:
```
if a?
 # empty block
else
 # empty block
```

Sometimes for testing I will comment out entire block and if I forget to leave at least one statement/expression the compiler will throw an error.

It's possible to do empty function:
```
->
  # Empty
```

So I was hoping it would be easy to make it also work with if/else.

Thanks a lot

**Comment by gkz** [comment]
You can use `void`

```
if a?
    void
else
    void
```

compiles to

```
// Generated by LiveScript 1.3.2
if (typeof a != 'undefined' && a !== null) {} else {}
```
