### ISSUE TITLE
LiveScript fork for ES6 and traceur

### ISSUE THREAD

**Issue by kristianmandrup** [gkz/LiveScript#492]
I have started a fork at https://github.com/kristianmandrup/LiveScript/tree/ES6

The goal is to make it much easier to develop for ES6 and traceur. 

Using ES6 and traceur is already "best practice" for projects such as Angular.js and Ember.js moving forward. The future is here!

Angular.js 2.0 (under development) is being developed for ES6 currently using traceur.
It would be nice if Angular and Ember developers (and many others) could "win" by switching away from javascript and learn the beauty of writing the same code in LiveScript.

Personally I would "hate" having to go back to javascript... why I want to provide this option. Cheers!

First goal is to default variables to use `let` and only create var contstructs if specifically declared to be a `var` variable. Please let me know if you have any ideas how to implement this simple feature. Thanks!

**Comment by pmros** [comment]
Any news about livescript to compile to ES6 (instead ES5)?
I think it would be useful lsc command give the option to compile to ES6 (not only ES5).
