### ISSUE TITLE
Make backcalls hushed by default?

### ISSUE THREAD

**Issue by Daiz** [gkz/LiveScript#504]
It occured to me that it doesn't really make sense for backcalls to return by default, since generally speaking there's little to no reason to ever have an (async) callback return (unless we're talking about early termination, but you'd still have to write an explicit `return` in LiveScript for that). Sure, the LS website has this example:
```livescript
x <- map _, [1 to 3]
x * 2
```
But it feels rather contrived to me, plus if you really wanted to do something like that you could still explicitly return. Or am I missing some real usecases on backcalls where returns are actually useful?

**Comment by gkz** [comment]
They have non-async purposes as mentioned, so I think they should be left as-is for consistency.
