### ISSUE TITLE
Incorrect compilation of pipe + return-suppressing backcall

### ISSUE THREAD

**Issue by kriomant** [gkz/LiveScript#524]
a <- b |> c
    a
is compiled to

    c(b)(function(a){ return a; });

as expected.

But

    a <-! b |> c
    a

is compiled to

    c(!b)(function(a){ return a; });

while expected is

    c(b)(function(a) { a; })

**Comment by gkz** [comment]
Fixed with 5f9608238ae4848ba1d6af4ddc477cf3e0eeeb42
