### ISSUE TITLE
livescript eats all argv flags

### ISSUE THREAD

**Issue by appedemic** [gkz/LiveScript#610]
Similar to #569 the livescript binary eats all flags in 1.3.1:

``
[~]$ mytool run --debug
``
results in:

``
Invalid option '--debug' - perhaps you meant '--help'?
``

and 
``
[~]$ mytool run --help
``

prints the help for lsc.

**Comment by clkao** [comment]
This seems breaking backward compatibility pretty badly.  There should either be a deprecation cycle (and notes in changelog) or restoring the old behaviour.

**Comment by gkz** [comment]
I agree, I will add an option in the optionator library and fix the behaviour in the next version

**Comment by gkz** [comment]
The functionality has been added to optionator, and the fix will be in the next version of LS
