### ISSUE TITLE
Broken Object Comprehensions

### ISSUE THREAD

**Issue by igl** [gkz/LiveScript#614]
Case 1:
Correct.

    {[key, val] for key, val of obj when (val > 1)}

    // Generated by LiveScript 1.3.1
    var key, ref$, val;
    for (key in ref$ = obj) {
      val = ref$[key];
      if (val > 1) {
        [key, val];
      }
    }

Case 2:
Double `if` generated by when.
Results are saved correctly `res$[key] = val;`

    x = {[key, val] for key, val of obj when (val > 1)}

    // Generated by LiveScript 1.3.1
    var x, res$, key, ref$, val;
    res$ = {};
    for (key in ref$ = obj) {
      val = ref$[key];
    if (val > 1) {
        if (val > 1) {
          res$[key] = val;
        }
      }
    }
    x = res$;

Case 3:
Inside of a function it is now processed as an array comprehension?
Double `if` and `resultObj$ = {}` -> `resultObj$.push(...)`.

    function foo
      x = {[key, val] for key, val of obj when (val > 1)}

    // Generated by LiveScript 1.3.1
    function foo(){
      var x, key, val;
      return x = (function(){
        var ref$, resultObj$ = {};
        for (key in ref$ = obj) {
          val = ref$[key];
    if (val > 1) {
            if (val > 1) {
              resultObj$.push(resultObj$[key] = val);
            }
          }
        }
        return resultObj$;
      }());
    }

Surprisingly i did not find any tickets on that arleady.
Any word on object/array comprehension? Will they be dropped?

In 1.3.0 they seem to work alright.

**Comment by igl** [comment]
:heart:  :+1:

**Comment by vendethiel** [comment]
:cake:

**Comment by unclechu** [comment]
In v1.5.0 I still can reproduce the issue: `{[k, v * 2] for k, v of var-name where k in <[a b]>}`
Compiles to:
```livescript
var k, ref$, v;
for (k in ref$ = varName(where(k === 'a' || k === 'b'))) {
  v = ref$[k];
  [k, v * 2];
}
```
And this next example fails on compilation:
```livescript
{[k, v * 2] for k, v of {a: 1, b: 2, c: 3} where k in <[a b]>}
```
With error:
```text
Parse error on line 1: Unexpected ','
```
