### ISSUE TITLE
ES6 module support?

### ISSUE THREAD

**Issue by impinball** [gkz/LiveScript#619]
Many frameworks are changing to exclusively using ES6 modules, such as Ember (already has) and Angular (will for 2.0). Currently, the only way to do a proper ES6 import is via wrapping it in double backticks like so:

```ls
``import foo from './bar'``
# do stuff with foo
```

This is very ugly on multiple levels. Could there be support added for ES6 module syntax?

One potential issue may be reserving/replacing the `import` operator, but getting people to shift to the current equivalent to `<<` (or `import all` to `<<<`) could be a start.

*(Note: apparently this even has some traction in making it into CoffeeScript, whose implementors have historically put web-compat as first priority)*

**Comment by vendethiel** [comment]
I'll reopen this, because I think we want this. We just need somebody who actually uses them to get some time for them :-).

**Comment by impinball** [comment]
Good point. I was just closing a seemingly stale issue (that I don't have the time to devote to).

**Comment by gkz** [comment]
Continue discussion at #705
