### ISSUE TITLE
The assignment operator := doesn't behave correctly in the REPL

### ISSUE THREAD

**Issue by gkovacs** [gkz/LiveScript#630]
Works correctly when executing via lsc: the variable a gets changed to value 3:

  geza$ cat foo2.ls
  a = 5
  f = -> a := 3
  f()
  console.log a
  geza$ lsc foo2.ls 
  3

However, if executing these same lines in the REPL, the variable a keeps its original value of 5:

  geza$ lsc
  LiveScript 1.2.0 - use 'lsc --help' for more information
  ls> a = 5
  5
  ls> f = -> a := 3
  [Function]
  function (){
    return a = 3;
  }
  ls> f()
  3
  ls> console.log a
  5
  undefined

**Comment by pepkin88** [comment]
Can be closed.
