### ISSUE TITLE
Returning backcall-defined function

### ISSUE THREAD

**Issue by wallverb** [gkz/LiveScript#638]
Should the 3rd example work ?
Right now it throws an error

-------

Since

```ls
a = ->
  b, c <- f
  ...
```

is equivalent to:

```ls
a = -> 
  f (b,c) ->
    ...
```

----

So should this (throws Unexpected 'NEWLINE'):
```ls
a = ->
  b, c <-
  ...
```

compile to the same thing as this:

```ls
a = ->
  (b, c) ->
    ...
```

**Comment by impinball** [comment]
I agreee with @vendethiel here. What's the use case for this? I can't think of any.

**Comment by wallverb** [comment]
Use case: declaring function that returns the function
Benefit: Just looks nicer instead of double nesting

But not a big deal and I agree about "opening the door", so I'm gonna close, unless its easy change to make it work - I would use it :)
