### ISSUE TITLE
Remove dash to camelCase, or camelCase only for function/class names.

### ISSUE THREAD

**Issue by gabeio** [gkz/LiveScript#644]
This is seriously an irritating functionality to realize LiveScript has. It is not straightforward.
`asdf-jkl` is not straightforward thinking that it will become `asdfJkl` in what other language does this do this in Closure? is that really the only other place it does it, probably for a reason.
This was denied in coffeescript for a reasonable [reason](https://github.com/jashkenas/coffeescript/issues/2345#issuecomment-5876294).

How is this straight forward?:
```
asdf-jkl === asdfJkl
```

Where now you have to add more code randomly.
Really not intuitive.
Example:
```LiveScript
list = 
	express: '~4.10.x'
	"express-session": '~1.10.x'
	swig: '~1.4.x'
	csurf: '~1.6.x'
	"cookie-parser": '~1.3.3'
	multer: '~0.1.7'
	async: '~0.9.0'
	"body-parser": '~1.10.1'
	levelup: '~0.19.0'
	leveldown: '~1.0.0'
	"express-partial-response": '~0.3.4'
	"serve-static": '~1.8.0'
```
VS
```LiveScript
list =
	express: '~4.10.x'
	express-session: '~1.10.x'
	swig: '~1.4.x'
	csurf: '~1.6.x'
	cookie-parser: '~1.3.3'
	multer: '~0.1.7'
	async: '~0.9.0'
	levelup: '~0.19.0'
	leveldown: '~1.0.0'
	body-parser: '~1.10.1'
	express-partial-response: '~0.3.4'
	serve-static: '~1.8.0'
```

It's just not intuitive programming to remember to add quotes around anything that has a `-`

**Comment by michaelficarra** [comment]
> It's just not intuitive programming to remember to add quotes around anything that has a `-`

Are you kidding? You have to do this in JS. If this feature were removed, as you ask, you would still have to do this, since `-` would not be a valid identifier character.

**Comment by gabeio** [comment]
Instead in all of these cases the items in question would be automatically surrounded by quotes and handled just fine.

**Comment by gabeio** [comment]
> You have to do this in JS.
This is not JS for a reason.

**Comment by gabeio** [comment]
It would be better for it to break than for it to just change it to something unexpected. I didn't know that the dash did this until I had a bug in a piece of code that should have just thrown an error, instead it changed the variable completely. How is that intuitive to you? Please do tell.

**Comment by michaelficarra** [comment]
So you want `-` handling in property names to be different from identifier names? That seems harder to deal with.

**Comment by gabeio** [comment]
Or have a way to turn that feature off. like `--no-camel-from-dash`

**Comment by gabeio** [comment]
I just mean in all cases except function/class names dash names are just going to be surrounded by quotes anyway. like in dictionaries and lists.

**Comment by gabeio** [comment]
okay I am wrong I didn't know it doesn't add quotes but I don't get why it doesn't it's just safer.

**Comment by michaelficarra** [comment]
@gabeio: Please stop with the back-to-back posts. Each of the 120 watchers gets an email every time you do that. If you must, edit your last post or think about your words more carefully before posting them.

I'm :-1: on this because the argument for it is anything but convincing.

**Comment by gabeio** [comment]
You already made your case on [coffeescript](https://github.com/jashkenas/coffeescript/issues/2345#issuecomment-5864036) and it was [turned down](https://github.com/jashkenas/coffeescript/issues/2345#issuecomment-5876294) for the same reason I'm stating it should be removed here.

I'm suggesting it be removed from here as it's safer to just fail than to change a variable completely and mess with code that *looks* correct.

**Comment by robotlolita** [comment]
LiveScript is not CoffeeScript, nor JavaScript, nor any other language. It has its own syntax and semantics. You should learn them.

In LiveScript, identifiers behave consistently. `a-b` is always `aB`, `a - b` is always `a - b`, a-b - c-d` is always `aB - cD`. Object grammars allow you to either use an identifier (using the rules previously mentioned), or a string, to provide a key for a pair.

If you think about it from the perspective of someone who only knows LiveScript, not turning `a-b: c` into `aB: c` would be the confusing thing. It would be "messing with code that *looks* correct".  There is no such thing as "intuitive". There is familiarity, which leads you to expect things to behave in certain ways. Most of the time, those expectations are wrong anyway.

**Comment by gabeio** [comment]
> There is no such thing as "intuitive".

For someone who knows multiple languages, and none of them having this issue, this is not intuitive and yes there is such thing as "intuitive". The exact definition of intuitive is: 
> perceiving directly by intuition without rational thought, as a person or the mind.

As such this is not intuitive for anyone who has coded before in other languages.

**Comment by vendethiel** [comment]
> In any case it was just an idea why did everyone freak out over it.

Probably because of your phrasing:

> This is seriously an irritating functionality to realize LiveScript has.


Anyways, this isn't changing. This has been discussed on some other issues already.

**Comment by gabeio** [comment]
> Probably because of your phrasing:

Oh oops I didn't mean that to be that strong :disappointed: sorry...

> which languages have it (like cobol, every lisp I know of, ...).

Cobol was before my time so I don't know it, and lisp I only know a little Racket which idk if it has it or not I didn't notice I haven't had the need to know lisp. So I didn't know lisp's have that...

**Comment by robotlolita** [comment]
Well, Lisps don't usually compile to dash-case to camel case, since they tend to be their own RT and stuff. I do suppose Lisps designed to be compile-to-JS could do to make FFI calls simpler (wisp probably does that?).

**Comment by vendethiel** [comment]
Yes, wisp compiles dashes to camelcase (and has a few other rules)
