### ISSUE TITLE
Value of last statement run in interpreter on livescript.net

### ISSUE THREAD

**Issue by tacomanator** [gkz/LiveScript#651]
May be misunderstanding, but it seems that the livescript.net interpreter does not output the correct value with this code:

````LiveScript
base =
  foo: \bar

doit = (obj) -> obj

doit base with do
  baz: \qux
````

My assumption is that the value of the last statement run is output. In this case, that should be an object with two properties, but [the output on the website](http://cl.ly/image/2y170E2X2h0g) has only one property (baz).

**Comment by ymeine** [comment]
Actually `with` creates a prototype cloning, so `base` becomes the prototype of the output object. What's displayed is the result of the serialization of the output object, which doesn't take into account the values from the prototype.

Try assigning the value of your last expression, and then accessing `foo`: it will display `bar`.

Indeed, technically the output is not an object with the two properties, it has only one (`baz`), and the others are reachable through the prototype chain.

You better do something like: 

```livescript
doit base <<< do
    baz: \qux
```
