### ISSUE TITLE
[idea] Comments to Documentation...? Like Coffeescript

### ISSUE THREAD

**Issue by gabeio** [gkz/LiveScript#653]
I really loved how coffeescript's runnable code could double as the documentation when run through their compiler and told such (w/ -l, --literate) or it has the extension of .litcoffee (Literate CoffeeScript). I found this to be a beautifully novel idea and totally forgot about it when messing with LiveScript for so long I was just wondering if LiveScript already has it or why it was never added? The parser basically only cared about the comments and made all of those into the docs(markdown) and the code wrapped around it went into the code blocks...

**Comment by igl** [comment]
What's wrong with `/* */`?
Delimited commenting has been done for a few decades in all languages (even natural language) and do not require additional IDE support.

**Comment by gabeio** [comment]
Those are fine, I mean take those comments and make send them through a parse to make them into a formatted markdown file for documentation purposes (makes documenting easier)

**Comment by quarterto** [comment]
@gabeio have a look at @robotlolita's [sug](https://github.com/robotlolita/sug)

**Comment by gabeio** [comment]
Ah never saw that before :+1:, still would be nice to have it natively supported but w/e :smile:

**Comment by caasi** [comment]
With something like `markdown-to-ast`, one can literate programming in almost any language: https://gist.github.com/caasi/2c172bacb31f884709f1

```livescript
#!/usr/bin/env lsc
require! {
  'fs'
  'markdown-to-ast'
  'prelude-ls': { concat-map, filter, id, join }
  'livescript': LiveScript
}
 
[,, ...files] = process.argv

const extract = ({ type, children = [], value = '' }) ->
  result = children |> concat-map extract |> filter id |> join "\n"
  switch
  | type is 'CodeBlock' => value + result
  | otherwise           => result
 
for filepath in files
  err, data <- fs.readFile filepath, encoding: \utf-8
  LiveScript.run extract markdown-to-ast.parse data
```

Even though I still want compiler and editor supports if we can really have `.lls`.

**Comment by phanimahesh** [comment]
Literate programming is more than a simple inversion of comments and code, as was originally described by Knuth.

Literate programming, as I understand it, is as follows. You describe the thought process and write relevant code in as many languages as you need/can, and use markers to link code sections. This file when processed provides documentation, and the code spread all over the place is stitched together to form an executable program.

Compared with that, CS's litcoffee is very simplistic, but still I liked it very much. Most code I wrote in CS was in that format.

I would really like to see more interest in literate programming, there is no decent ecosystem to support it well. However, for LS, I think it would add yet another feature that is not used often. The simple snippet by caasi does the trick, so it may be a good idea to keep it separate.
