### ISSUE TITLE
Partial application can't play with do block

### ISSUE THREAD

**Issue by fansgit** [gkz/LiveScript#654]
```livescript
(+) 1 do
  2
# result 3

(+) _, 2 do
  1 
# result [Function]
```

**Comment by quarterto** [comment]
The partialize operator just acts as a dummy argument, so the call still has the same precedence with respect to the `do` block. 

For now, use parentheses:

```livescript
((+) _, 1) do
  1
```

or a backpipe:

```livescript
(+) _, 1 <| do
  1
```

I suppose we could hack this into `Chain` like the `a |> f _ 1` optimisation, but is it worth it? @vendethiel

**Comment by vendethiel** [comment]
No, this is just an invalid assumption on how `do` works.

The first one is actually `(+) 1, 2`, not a call of `(+) 1`. This usage of do is the same as

```
myfn do
 1
 2
```

**Comment by fansgit** [comment]
Another one:

```LiveScript

f = (g, x) -> g x

x <- f do
  _
  1
x
# result 1

x <- (f _) do
  1
x
# [TypeError]
```
