### ISSUE TITLE
(discussion) Typechecking in function parameters

### ISSUE THREAD

**Issue by Haspaker** [gkz/LiveScript#661]
Types and typechecking is very useful. However, full compile-time typechecking à la TypeScript would require a massive overhaul of both the syntax and the compiler.

A compromise would be to allow optional runtime typechecking only for function parameters. It is easy to implement and does not conflict with the current syntax. 

I have coded a fully working (I hope) implementation of this in my repository https://github.com/Haspaker/LiveScript/tree/types, if anyone wants to check it out and play around with it.

##### TL;DR

In short, it would look like this: 
```livescript
add = ( Number x, Number y ) -> x + y
```
Calling this function with something that is not a Number causes a TypeError
```livescript
add 'a' 'b' #=> [TypeError: Expected Number but got String at argument 0]
```

For a more details you can read below or head over to my [repository](https://github.com/Haspaker/LiveScript/tree/types).

#### Syntax

Types can only be specified for function parameters, when declaring a function. Declaring types is completely optional. You specify the type by writing the type before the name of the parameter, followed by a space:

```livescript
f = ( Type x, Type y, Type z ) -> ...
```

Types can also be specified for destructured arguments: 

```livescript
f = ( Array [String a, String b, String c] ) -> ...
f = ( Object {Number x, Number y} ) -> ...
```

If multiple types are allowed, separate them by a vertical bar `|`.

```livescript
get_item = ( Number|String id ) -> ...
```

A parameter with a type cannot be Null or Undefined unless it has been explicitly allowed.

```livescript
f = ( Number x ) -> x
f! #=> [TypeError: Expected Number but got Undefined at argument 0]
f = ( Number|Undefined x ) -> x
f! #=> undefined
```

A shorthand for allowing a parameter to be undefined is to add a question mark `?` after its type. `Type?` is just syntactic sugar for `Type|Null|Undefined`. Think of it as the `Maybe` type in Haskell.

```livescript
f = ( Number x ) -> x
f! #=> [TypeError: Expected Number but got Undefined at argument 0]
f = ( Number? x ) -> x
f! #=> undefined
```

Sometimes, you just want to make sure that the parameter exists, but do not know or care about its type. In that case, you can use the `Any` type. `Any` matches all variables that are not `undefined`, `null` or `NaN`.

```livescript
f = ( Any x ) -> x
f 5 #=> 5
f! #=> [TypeError: Expected Any but got Undefined at argument 0]
```

#### Custom types

By default, you can use all the primitive, composite and special data types in JavaScript, as well as all built-in objects: `Null Undefined NaN Boolean Number String Function Object Array RegExp Error Set etc...`

Of course, you can also declare your own types by making new classes.

```livescript
class Monkey
	eat: (Fruit fruit) -> "The monkey has eaten a #{fruit.name}"

class Fruit

class Plum extends Fruit
	name: \plum

class Banana extends Fruit
	name: \banana

feed_monkey = (Monkey monkey, Fruit fruit) -> monkey.eat fruit

feed_monkey new Monkey(), new Banana() #=> The monkey has eaten a banana
feed_monkey new Monkey(), new Plum() #=> The monkey has eaten a plum
feed_monkey new Banana(), new Monkey() #=> [TypeError: Expected Monkey but got Banana at argument 0]
```

#### Implementation

Typechecks happen at the top of the function, but below any parameter assignments.

```livescript
f = (String x, Number y) -> x + y
```

compiles down to:

```javascript
  f = function(x, y){
    typecheck$(x, [String], ['String'], ['0']);
    typecheck$(y, [Number], ['Number'], ['1']);
    return x + y;
  };
```

where `typecheck$` is a function that looks mostly like this:

```javascript
function typecheck$(value, types, types_str, pos) {
    for(var i = 0, l = types.length; i < l; i++) {
      if( typeof value === 'object' && typeof types[i] === 'function' && value instanceof types[i] )  return true;
      if( {}.toString.call(value).slice(8, -1) === types_str[i] ) return true;
    }
    throw TypeError('Expected ' + types_str.join('|').replace(/\|Null\|Undefined$/, '?') + ' but got ' + value.constructor.name  + ' at argument ' + pos.join('.') );
}
```

The actual `typecheck$` function has a few more things thrown in to deal with `Null`, `NaN`, `Undefined` and `Any`. For more details see https://github.com/Haspaker/LiveScript/tree/types.

#### Pros
• Self documenting code!
• Backwards compatible (except for `?`, see below)
• Enforce the correct usage of functions
• Better error messages (`Expected Monkey but got Fruit at argument #i` is a lot more useful than the alternative `undefined is not a function`)
• Catch undefined parameters and NaN early on, before they spread and corrupt more values. It also makes it easier to find the cause of the error in complex systems.

#### Cons
• Somewhat slow, as runtime typechecking always is. However, for normal web development it should not be noticeable. And since it is completely optional, typechecks can be left out of performance critical code.
• The `( Type? x ) ->` syntax conflicts with the current `( value ? default ) ->` syntax. Maybe `Type?` could be replaced with some other kind of syntax?
• The `constructor.name` call in the error message should be replaced with some kind of toString and Regex solution, since IE does not support the `.name` property.

**Comment by vendethiel** [comment]
We already have a specific property for class names (that's not `.name` ;-).)
However, I'm not sure i see much of the point without any compile-time guarantees...

This is a big can of worms to open. People will want coercions. Typed arrays/hashes. Generics. Whatever else.

Fwiw, a project similar exists, called GorillaScript. It's dead now but existed as a coffee/ls-like with types (and macros). Never took off

**Comment by Haspaker** [comment]
> However, I'm not sure i see much of the point without any compile-time guarantees...

Yeah, compile-time guarantees would be the dream. But I wouldn't say run-time guarantees are useless.

It prevents stuff from silently failing, or failing three function calls later in a completely different file with some obscure error like `undefined is not a function`.  

It also serves as syntactic sugar which removes a lot of `typeof!` security checks when working with untrusted input. I would say a habit of typechecking increases security and decreases the chance of undiscovered bugs.

It is especially useful in LiveScript, which does not have source maps and generates a lot of anonymous functions. Navigating the compiled files to figure out *which* variable became corrupted *when* can really be a pain.

Typing the code also makes it a lot more easier to read and reason about. It is so much more easier to understand the purpose and structure of the function when it is `(String street, Number house, Array houses) ->` instead of just `(street, house, houses) ->`.

Of course one could just add comments like `# street = String, house = Number, houses = Array` above all functions, but I think that is a worse solution.

> We already have a specific property for class names (that's not .name ;-).)

Yeah, but `.displayname` will only work with livescript-created objects. `.name` (or some toString + RegEx alternative) is a more cross-compatible solution. :)

> This is a big can of worms to open. People will want coercions. Typed arrays/hashes. Generics. Whatever else.

People will always want new stuff, no matter what you do. You cannot prevent that. Wanting it does not guarantee they will get it though. :)

**Comment by ginus** [comment]
I think the better way is code tips when type code,not complie time or run time, because that time is the orign point. For that way comments as doc should be raised.

**Comment by vendethiel** [comment]
Ha, just wanted to point out than you can use flowtype with LS thanks to its `/** @flow */`-style syntax

**Comment by robotlolita** [comment]
Just to clarify: these are contracts, not types.

@vendethiel you can have higher-order contracts, but the overhead is just too much for collections and stuff.

**Comment by vendethiel** [comment]
Indeed, that's my point. Though the (some) racket guys are working on a compile-time contract parsing, as I've seen, it's currently a very limited subset of Racket... I'll try to find the link again. And that's not what we'd implement anyways.

I think most people will argue that there should be a way to "disable" guards for a "production env"...

**Comment by robotlolita** [comment]
There are some papers about partially evaluating contracts at compile time, which gets rid of some of the overhead, but still doesn't give you types :)

Also, if we were to implement contracts, higher-order ones with correct blame assignment would be interesting. Something like http://disnetdev.com/contracts.coffee/ for LS would be pretty cool

**Comment by vendethiel** [comment]
I was unclear, I think -- I agree this doesn't give you type. It's just that, hey, people have made progress on that front!

contracts.coffee seems really interesting.
