### ISSUE TITLE
(-> it ? ''), (-> it!)

### ISSUE THREAD

**Issue by askucher** [gkz/LiveScript#662]
Hi. 

We can write (.prop), (.prop.substr 3)

Is it possible to use another way of writing 
```Livescript
(-> it ? '') and (-> it!)
#too much space required
```

Something like 
```Livescript
(. ? '') and (.!)  
```

**Comment by vendethiel** [comment]
Has that really been an issue for you?

**Comment by askucher** [comment]
No. It is not really issue. But logically "." should be reference to object when (.prop) is working

**Comment by vendethiel** [comment]
no, really, that's going one step too far... YAGNI.
