### ISSUE TITLE
Can't publish new version of LS due to npm changes

### ISSUE THREAD

**Issue by gkz** [gkz/LiveScript#663]
npm doesn't allow upper case in package names anymore, and is preventing me from publishing a new version of LiveScript

I could change the name of the package to `livescript` and change all the docs to reflect that.

**Comment by vendethiel** [comment]
now that's a stupid rule. But yeah, there's no other solution left.

**Comment by gabeio** [comment]
@vendethiel it's probably because people are getting very annoyed that LiveScript is a completely different package from livescript...

**Comment by wryk** [comment]
No more "LiveScript", yeah !
Actual package name is really annoying :/

**Comment by ginus** [comment]
Why not "lovescript", love script love job, job with love,job around love.

**Comment by gabeio** [comment]
@ginus the point behind the name livescript is that it's the original name of javascript before they decided on javascript... [history](http://en.wikipedia.org/wiki/JavaScript#History)

**Comment by igl** [comment]
Bring it one step further from love: lubescript

**Comment by vendethiel** [comment]
Please.

**Comment by ozra** [comment]
This is good  - the package really should be "livescript" - lowercase and dashes is the package-name-norm...

**Comment by Dessix** [comment]
Watching this space...
https://www.npmjs.com/package/livescript

**Comment by heavyk** [comment]
also, as a side note, often times I write:
```
require! mynpmmodule: { func }
```
which works great, but if the module has a dash,
```
require! my-npm-module: { func }
```
tries to `require('myNpmModule')` which doesn't work well.
I can't think of a single use case where I would ever use a camelized name like that in a require statement. for now, I write, 
```
require! 'my-npm-module': { func }
```
which also works great, but if it's an easy thing to do, now having this no capital letters limitation, the second example's usage is much more attractive now, and I sincerely doubt anyone has used camelized package names like that.

**Comment by gkz** [comment]
I've changed the name in `package.json` to `livescript`, and 1.4 will be published under that name
