### ISSUE TITLE
Shift operator <<<, Syntax error: Unexpected 'IMPORT'

### ISSUE THREAD

**Issue by DanSnow** [gkz/LiveScript#664]
I'm using LiveScript 1.3.1

And I want to use unsigned left shift operator `<<<` in js.
As the document I should use dot to surround it, so it's `.<<<.`

Ex: `sth .<<<. 10`

But I got `Syntax error: Unexpected 'IMPORT'`
It seem recognize `.<<<.` as `<<<`

**Comment by quarterto** [comment]
There is no `<<<` shift operator in Javascript, only `<<`, `>>` and `>>>`.
