### ISSUE TITLE
acess orignal this object in bound functions

### ISSUE THREAD

**Issue by winterland1989** [gkz/LiveScript#668]
Suppose we are writing a event handler inside a class, (i personally do this a lot with mithril.js to create event handler), if we want the handler access class's data, then we can use bound functions like this:
```ls
...
      m 'span.sugItemPlayBtn',
            onclick: (e) ~>
                @onPlay id, type
...
```
and it perfectly compile ```@onPlay``` to ```this$.onPlay``` with ```this$``` pointing to outside class. but when i want to access the DOM element (aka. e.target, and this dom prop has some compatibility issue), it have to be written in this way:
```ls
...
      m 'span.sugItemPlayBtn',
            onclick: (e) ~>
                elem = ``this``
                elem.className = \sugItemStopBtn
                @onPlay id, type
...
```
IMO this is not a elegant way to do it, we should add some syntax sugar to access the orignal this object, what about ```@~``` or ```~@``` and it should be directly compiled to ```this.```

**Comment by vendethiel** [comment]
Put `self = this` in the outer scope.

**Comment by winterland1989** [comment]
you mean not to use bound function syntax at all? that is what i used to do in coffee... 
Every time i want to access the class prop, i have to write ```self.```, isnt it nice to have ```@``` bound while preserving original ```this``` access with similar syntax to deal with some special cases?

**Comment by vendethiel** [comment]
No it's not. Adding stuff like that you use once every full moon only makes the language harder.

**Comment by winterland1989** [comment]
I really cant agree with you about it's rarely used, because in React.js, mithirl.js or similar VDom MVC framework, it's very common to read or write both dom element's and model's data, and generally provide a semantic way to access original ```this``` object reference is not complexing the language, we need more voice on this IMO.

**Comment by blvz** [comment]
I use mithril and never had to use the original `this`. Try to explore deconstructors and `let` a little more and also write more functional code. Most of your bugs/problems will disappear.
