### ISSUE TITLE
Does backcall support generators?

### ISSUE THREAD

**Issue by fansgit** [gkz/LiveScript#670]
Neither <-* nor *<- works out.

**Comment by kay-is** [comment]
+1

Wanted to post the same issue lol.

Works:

      router.get "/#{resource-name}/:id" ->*
        @body = (model-name): yield @models[model-name].find @params.id
---
Doesn't work:

      *<- router.get "/#{resource-name}/:id"
      @body = (model-name): yield @models[model-name].find @params.id
