### ISSUE TITLE
`let` with generators

### ISSUE THREAD

**Issue by unclechu** [gkz/LiveScript#673]
This works fine:

``` LiveScript
g = ->*
  for item in [1 2]
    yield item

x = g!
console.log x.next!.value, x.next!.value
```

But with `let` we have `missing ; before statement`:

``` LiveScript
g = ->*
  for let item in [1 2]
    yield item

x = g!
console.log x.next!.value, x.next!.value
```

It happened because LS `let` isn't pure JS `let`, and LS `let` creates some function for let. Any ideas how we can deal with `let` and `yield`s in LS?

**Comment by ceremcem** [comment]
Any thoughts here - except for using pure javascript for this kind of blocks?

**Comment by pepkin88** [comment]
This is fixed now, can be closed.

**Comment by rhendric** [comment]
Thanks @pepkin88!
