### ISSUE TITLE
Can't use yield inside in a switch that assigns to a variable

### ISSUE THREAD

**Issue by raine** [gkz/LiveScript#678]
One might expect the following to work, however assigning to a variable
or returning a switch statement wraps the switch in a regular function
shadowing the outer generator.

``` ls
# ... ->*

build =
  | build-number?
    yield get-build job-name, build-number
  | otherwise
    yield get-last-build job-name
```

Which compiles to:

```js
// Generated by LiveScript 1.3.1
var build;
build = (function(){
  switch (false) {
  case typeof buildNumber == 'undefined' || buildNumber === null:
    return yield getBuild(jobName, buildNumber);
  default:
    return yield getLastBuild(jobName);
  }
}());
```

A workaround in this case is to yield the switch statement:

```ls
build = yield switch
  | build-number?
    get-build job-name, build-number
  | otherwise
    get-last-build job-name
```

---

Another example where returning a switch is the intuitive solution but can't
be used:

```ls
wait-for-build = async (...) ->*

  return switch # explicit return needed in generator fn
    | build.is-just
      yield Promise.resolve merge {job-name}, build.get!
    | otherwise
      yield Promise.delay POLL_DELAY_MS
      yield wait-for-build job-name, build-number # recur
```

To work around this you can return inside the switch:

```ls
switch
  | build.is-just
    return yield Promise.resolve merge {job-name}, build.get!
  | otherwise
    yield Promise.delay POLL_DELAY_MS
    return yield wait-for-build job-name, build-number # recur
```

Do you see a way how LiveScript could avoid this pitfall or should there be a
compile time warning informing the programmer?

**Comment by vendethiel** [comment]
it probably can generate a yielding anonymous function and yield from this  closure.

**Comment by vendethiel** [comment]
@gkz keep up the good work :) (I should've done that one already!)
