### ISSUE TITLE
Multiline strings issue with spaces

### ISSUE THREAD

**Issue by unclechu** [gkz/LiveScript#679]
We have an example on [LS documentation](http://livescript.net/#literals):

``` LiveScript
multiline = 'string can be multiline
            and go on and on
            beginning whitespace is
            ignored'
heredoc = '''
            string can be multiline
            with newlines
            and go on and on
            beginning whitespace is
            ignored
'''
```

That compiles to:

``` JavaScript
var multiline, heredoc;
multiline = 'string can be multiline and go on and on beginning whitespace is ignored';

heredoc = 'string can be multiline\nwith newlines\nand go on and on\nbeginning whitespace is\nignored';
```

And when we try to compile this example:

``` LiveScript
multiline = 'string can be multiline
            and go on and on
            beginning whitespace is
            ignored'
```

We get this:

``` JavaScript
// Generated by LiveScript 1.3.1
var multiline;
multiline = 'string can be multilineand go on and onbeginning whitespace isignored';
```

So we missed spaces.

**Comment by blvz** [comment]
You can add *trailing* whitespace or, when using text editors that remove those (like Atom), escape beginning whitespace:

```LiveScript
trailing = 'there\'s a trailing whitespace -> 
            right here.'

escaped = 'here\'s an escaped
         \ whitespace.'
```

**Comment by unclechu** [comment]
@blvz anyway, it's looks like a bug.

**Comment by blvz** [comment]
To me, it doesn't. But personally, I'd like it to respect indentation:

```LiveScript
# desired behavior
str = 'multiline string with
        leading whitespace.'

# would be
# var str = 'multiline string with leading whitespace.';
```

**Comment by unclechu** [comment]
@blvz "To me, it doesn't."
But why? We have example in official documentation and it doesn't works as it described. How it can be not a bug?
I think this example:
```LiveScript
str = 'multiline string with
        leading whitespace.'
```
is bad, because it's very unobvious, may be it's a 8 spaces identation? And what if we use different variable name?
```LiveScript
string = 'multiline string with
           leading whitespace.'
```

**Comment by blvz** [comment]
> We have example in official documentation and it doesn't works as it described. How it can be not a bug?

I've thought the code in the documentation had trailing whitespace, sorry for not checking it. Now I'm not sure if it's buggy or badly documented.

> I think this example is bad, because it's very unobvious

I somewhat agree. But I'd like the characters to be aligned. That's really just personal taste:

```LiveScript
# not actual LiveScript

str = 'multiline string with
        leading whitespace.'

# => 'multiline string with leading whitespace.'


string = 'multiline string with
        leading whitespace.'

# compile error


double = 'multiline string with
            double leading whitespace.' # clear to see, comparing with above line.

# => 'multiline string with  double leading whitespace.'
```

Also, there are cases which whitespace shouldn't be added at all:

```LiveScript
# actual LiveScript

hyphenated = 'words with the same three
            \ letters in a row, such as “fall-
              like”, should be hyphenated.'

# => 'words with the same three\ letters in a row, such as “fall-like”, should be hyphenated.'


pic = 'R0lGODlhIAAgAPMAAAgICBcXFyUlJTg4OEdHR1dXV2dnZ3h4eIeHh5iYm
       KioqLm5ucjIyNbW1ufn5/39/SH5BAAAAAAALAAAAAAgACAAAAT+8MlJq7
       1YurWUV1zIMY2TVQ0CdknitTByyMv5OEj9NMzYk4zegqGQmTALxK0HajQ
       Wx0evZFIcohRHwbRZOEu7CUOju14OiYlDURgQZo2Jk3PMWQ4CRSnBGAQA
       AS0FGgYBAgIGQQwFChQJBQ0KBgdDQwgpBAY3bSoMDp89kBoHDGgLCTMJK
       hpiShtWnZQSDQcNkAcFCCSfDgwJOjiXpx1OsjcGDQRWCouknwqqCFyIVc
       gLA3E3B9AbBCSZBS0Iv0EGCg5PAgMdmmLb2pkDegpvLZKURQVti1gPC1s
       7zLnJhKwBqgUEOqAhsG6QhVU7BlyhB0AAAYYFArQJ8GdduwrEWo7QGuOC
       DSAAKFMC8ObQQhIwDMYROFLAF4EEF/Fcaelym6IiCFQM8LXtogFkD3haY
       HB0hJcnMOx5yqb0wj9yHErw2LWDyscTa0x9caJIawmANsgEZcarrQmmaS
       08QZAJipoEBvrFpZBCnz5zezHozRL4gYuAgnE1qmCggIFHBQ7IMyCgwII
       A/wjYGmBAHr2vEiTqw/aGc4GbAQwQEHCAgF8VMy24MWDkAG0E+hDeYxpU
       xakLjKjciIPuk9kbbgcPLlwhAgA7'

# => 'R0lGODlhIAAgAPMAAAgICBcXFyUlJTg4OEdHR1dXV2dnZ3h4eIeHh5iYmKioqLm5ucjIyNbW1ufn5/39/SH5BAAAAAAALAAAAAAgACAAAAT+8MlJq71YurWUV1zIMY2TVQ0CdknitTByyMv5OEj9NMzYk4zegqGQmTALxK0HajQWx0evZFIcohRHwbRZOEu7CUOju14OiYlDURgQZo2Jk3PMWQ4CRSnBGAQAAS0FGgYBAgIGQQwFChQJBQ0KBgdDQwgpBAY3bSoMDp89kBoHDGgLCTMJKhpiShtWnZQSDQcNkAcFCCSfDgwJOjiXpx1OsjcGDQRWCouknwqqCFyIVcgLA3E3B9AbBCSZBS0Iv0EGCg5PAgMdmmLb2pkDegpvLZKURQVti1gPC1s7zLnJhKwBqgUEOqAhsG6QhVU7BlyhB0AAAYYFArQJ8GdduwrEWo7QGuOCDSAAKFMC8ObQQhIwDMYROFLAF4EEF/Fcaelym6IiCFQM8LXtogFkD3haYHB0hJcnMOx5yqb0wj9yHErw2LWDyscTa0x9caJIawmANsgEZcarrQmmaS08QZAJipoEBvrFpZBCnz5zezHozRL4gYuAgnE1qmCggIFHBQ7IMyCgwIIA/wjYGmBAHr2vEiTqw/aGc4GbAQwQEHCAgF8VMy24MWDkAG0E+hDeYxpUxakLjKjciIPuk9kbbgcPLlwhAgA7'
```

**Comment by gkz** [comment]
It's an issue either the documentation, it will be fixed.

**Comment by pepkin88** [comment]
Moreover, later the documentation says:
> If you have any multiline strings non triple quoted strings (using "string" or 'string'), eg.
> ```
> text = "hi
>         there"
> ```
> you will have to change them as in CoffeeScript this would be "hi         there" while LiveScript ignores indentation after newlines so it would be "hi there"

So it's doubling down on inserting spaces. And the thing is, CoffeeScript puts only one space, just like LiveScript should. I don't remember CoffeeScript ever behaving like described above.

Because multiline strings (unlike heredocs) are kinda broken, I choose not to use them. First, I would have to resort to weird hacks to insert those spaces, and second, if/when it get fixed to a normal/intuitive behavior, I don't want to have to search and change my code.

**Comment by rhendric** [comment]
There's definitely a documentation deficiency here. LiveScript offers non-hacky ways to get what you want, pretty much regardless of what you want.

You want spaces but no line breaks?
```ls
multiline = 'Here you \
             go, buddy!'
#=> 'Here you go, buddy!'
```
(The backslash is optional, but makes the trailing space more visible and more protected against overzealous text editors.)

You want no spaces either?
```ls
multiline = 'deadbeef
             deadbeef'
#=> 'deadbeefdeadbeef'
```

You want indentation?
```ls
multiline = '''
  for x in xs
    console.log x'''
#=> 'for x in xs\n  console.log x'
```

You want, for some reason, double spaces but no line breaks?
```ls
multiline = 'A little unusual  \
             but hey, no judgement.'
#=> 'A little unusual  but hey, no judgement.'
```

Yes, this is different from how CoffeeScript does strings, but I don't think LiveScript strings are broken. They definitely could be documented better—in January of 2015, a commit stripped trailing whitespace from those examples, making them incorrect as opposed to merely difficult to read. I plan on introducing trailing backslashes to prevent that from happening again.

**Comment by pepkin88** [comment]
OK, if that's indeed intended, so be it. I only remember myself trying those and expecting the CoffeeScript behavior once or twice. In that case, the documentation is indeed misleading.

**Comment by pepkin88** [comment]
To explain my thought process: I didn't event thought, that there (in the documentation example) could be trailing spaces.
Generally they are avoided, because it's not obvious they're there. When something is preceded with a white space, it's visible. But if a space is at the end of a line, most would assume it's not there. Hence various editors provide a feature to remove them (which I use myself).
Moreover, I assumed, that the algorithm consequently trims the white spaces from both sides, not just from left + the newline character. Personally, I would prefer if the backslash was mandatory, not optional, for inserting a space between the lines, of course with a proper example in the documentation.

**Comment by rhendric** [comment]
A clarifying example has been added to the [gh-pages-next](https://rawgit.com/gkz/LiveScript/gh-pages-next/index.html) staging branch, and the existing broken example was fixed with backslashes. It'll go live with the [1.6 release](https://github.com/gkz/LiveScript/issues/1016).
