### ISSUE TITLE
keyword with problem

### ISSUE THREAD

**Issue by winterland1989** [gkz/LiveScript#680]
the [with](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/with?redirectlocale=en-US&redirectslug=JavaScript%2FReference%2FStatements%2Fwith) keyword in javascript is not recommend but do have its usage, for now i have write awkward code like this:

```ls
``with(Math){``
x = cos 5
``}``
```
to get output like this:
```js
with(Math){
x = cos 5
}
```
I cant even indent here because it will make a unreferred cascadee, since LiveScript should at least be able to express javascript syntax, i expected something like this:
```ls
with Math do
  x = cos 5
```
to get output like this:
```js
with(Math){
  x = cos 5
}
```
is it trival to preserve keyword ```with``` orginal function?

**Comment by winterland1989** [comment]
Actually it can be more useful if a expression sugar added:
```ls
x = with Math do
  cos 5
  cos 4
console.log x
```
can be de-sugar into
```js
with(Math){
  var x$ = (function(){
    cos(5);
    return cos(4);
  })();
}
x = x$;
console.log(x);
```

**Comment by vendethiel** [comment]
"with" is a terrible feature you should never be using, so we're not adding.
Use `{cos} = Math` if the idea of typing "Math." all the time is unbearable.

**Comment by winterland1989** [comment]
```with``` is a terrible feature indeed, but it's the only dynamic way to change a function's scope chain. unlike destructive import, it can be used when you want to optimize some reference access,  just like many other js features, after some digging following syntax can be made avaliable by change ast.ls
```ls
do with Math
  cos 4
  sin 5
=>
```js
(function(){
  with(Math){
    cos(4);
    return sin(5);
  }
}).call(this);
```
it's even safer to use with inside a lambda function, would you kindly accept this feature?

**Comment by vendethiel** [comment]
No. It's not safe. It doesn't optimize anything. It just makes everything upredictable and has, at times, prevented browser vendors from implementing new specced features. Do not use it.


Also, it's "destructuring", not "destructive import" (I'm not adding anything to the global scope)

**Comment by unclechu** [comment]
Agreed to @vendethiel

**Comment by unclechu** [comment]
@winterland1989 try something like this:
```LiveScript
{sin, PI: pi} = Math
sin pi/2
```
