### ISSUE TITLE
Unnested callbacks and assignment

### ISSUE THREAD

**Issue by unclechu** [gkz/LiveScript#682]
```LiveScript
<- z =
x + y
```
is invalid LS code. There's any way to use unnested callbacks with assignments?

May like something like that?:
```LiveScript
module.exports = (x, y) <-
x + y
```

**Comment by unclechu** [comment]
```LiveScript
(x, y) <- (!-> module.exports = it)
x + y
```
Any other solutions?

**Comment by gkz** [comment]
I don't think callbacks should be used in this case (assignment), as the code becomes confusing.
