### ISSUE TITLE
Please add support of sql syntax: like '%user', not in 1,2,3, ...

### ISSUE THREAD

**Issue by askucher** [gkz/LiveScript#684]
```Livescript


if id like '%_serv'
  console.log \do


if id not in [1,2,3]
  console.log \do

```

**Comment by fjdumont** [comment]
`not in` already works for arrays, using the internal `in$` function.
If you really feel the need for `like`, use infix and regular expressions:

    like = (str, pat) -> pat.test str
    \foo_bar `like` /.*bar/

**Comment by vendethiel** [comment]
you can use `is` with regexps already.
