### ISSUE TITLE
lsc REPL needs improved tab completion

### ISSUE THREAD

**Issue by kflu** [gkz/LiveScript#687]
Both `node` and `coffee` REPLs have better tab completion than lsc. For example `glob[tab]` would be completed to `global`. `req[tab]` completes to `require`. I don't know how `coffee` implements its REPL but it feels as derived from `node`. Could `lsc` do something similar?

**Comment by chisui** [comment]
this would be really helpfull

**Comment by raine** [comment]
> I don't know how coffee implements its REPL but it feels as derived from node

I checked and it does it with the `use-global` option on repl.

We have the option turned off for some reason:

https://github.com/gkz/LiveScript/blob/abcb494a50fbcce258f34b59052455da42e8aa9f/src/command.ls#L276

Perhaps because variables autocomplete in camelcase?

```
ls> my-test-var = true
true
ls> myTestVar
```
