### ISSUE TITLE
Default parameter can't reuse name from outer scope

### ISSUE THREAD

**Issue by jampekka** [gkz/LiveScript#688]
If one uses a default parameter value that has a same name in inner and outer scopes, the result is that the value gets null by default. I think this definitely breaks the "rule" that parameters are in the inner scope and arguments (including defaults) in outer scope.

```
a = "Not undefined"
do (a=a) -> a
```

Compiles to
```
// Generated by LiveScript 1.3.1
var a;
a = "Not undefined";
(function(a){
  a == null && (a = a);
  return a;
})();
```
Which clearly doesn't use the default value from the outer scope. Coffeescript does the same thing, but it sort of makes sense with its mad scoping, and they hack around the do-case by passing defaults as arguments.

**Comment by vendethiel** [comment]
That's for the better.

**Comment by jampekka** [comment]
WTF?

**Comment by jampekka** [comment]
Is this really the state of LiveScript community and developers too? Could you honor me even with a line of explanation on why "That's for the better"?

**Comment by vendethiel** [comment]
We don't want coffee's confusing's scope things.
We don't want C/C++-style scoping rules (`int x = 1; { int x = x }`).

We don't want python-style "eager arguments".

And we want to be able to do `(x, y = x) ->`.

We could make this an error, but we need to check specifically for `let`

**Comment by jampekka** [comment]
I wasn't proposing any of those, as I do agree that they are bad and confusing and bug prone approaches.

But I think this corner case can be quite confusing, and at least for the trivial case (a=a) I think it should be an error. Not sure how to handle the let though.

I don't think it's semantically impossible to handle also the `(x, y=x) ->` case. The first x would just shadow the outer scope x here, which I find to be quite logical if the args are evaluated "left to right".

The implementation can be a bit tricky though, as I think JS doesn't "unshadowing" the variable (eg something like `var a = a`). So it would probably need to mangle all references to a in the inner scope.
