### ISSUE TITLE
sourcemap lost file property

### ISSUE THREAD

**Issue by yhsiang** [gkz/LiveScript#689]
When I made gulp-livescript support sourcemap, [vinyl-sourcemaps-apply]( https://github.com/floridoo/vinyl-sourcemaps-apply/blob/master/index.js) will check the file property. so I hack to add this property right now. 
https://github.com/yhsiang/gulp-livescript/blob/sourcemap/src/index.ls#L59

Is this should  generated from `sn` https://github.com/gkz/LiveScript/blob/master/src/ast.ls#L13-L20 ?

**Comment by Diggsey** [comment]
The file property is not required by the source-map spec, and is generally not very useful as it only gives the name of the generated file, not a path or URL with which is could be found.

This is a bug in vinyl-sourcemaps-apply, which should correctly handle source-maps which don't have the file property set.

**Comment by yhsiang** [comment]
ok, I will report to vinyl-sourcemaps-apply, thx!
