### ISSUE TITLE
Underscore to skip destructuring array elements

### ISSUE THREAD

**Issue by atifaziz** [gkz/LiveScript#692]
Consider allowing use of underscore to skip corresponding element when destructuring an array, as in:

    [x, _, y, _, z] = [1 2 3 4 5]

Today, it introduces underscore as a variable & assigns the corresponding element.

**Comment by raine** [comment]
You probably knew this but you can actually just omit the variable to skip it:

```ls
[x, , y, , z] = [1 2 3 4 5]
```

Not that it's particularly readable.

**Comment by vendethiel** [comment]
Or use `[]` or `null` if that's your thing. `_` is a valid identifier (sadly).
