### ISSUE TITLE
Livescript 2 dots notation

### ISSUE THREAD

**Issue by askucher** [gkz/LiveScript#693]
```Livescript

$scope
  ..prop = []
  ..prop2 = 2
```

Should be generated into 

```Javscript
  $scope.prop = []

  $scope.prop2 = 2
```

instead of 

```Javscript
  /* looks ugly, unlogical, with extra reference and people don't like it */
  var x$ = undefined
  x$ = $scope
  x$.prop = []
  x$.prop2 = 2
```

**Comment by vendethiel** [comment]
It might look illogical in this case, but if you have function calls inbetween, getters or long accessor chains (the usual time you use the cascade syntax), the extra reference helps with performance/helps to avoid multiple evaluation.

**Comment by askucher** [comment]
I think you shound solve "function calls inbetween" problem here. it is not obvious.

**Comment by vendethiel** [comment]
I'm not sure what you mean?

**Comment by askucher** [comment]
I mean it is hard to imagine case when you have " if you have function calls inbetween" here

**Comment by vendethiel** [comment]
There's basically no performance drop here. Only some kind of ugly code, which is 1) not that bad 2) pretty irrelevant considering we now have source maps.

I don't see how "complicating" the compiler to handle single-identifiers in cascades as a special case helps :).
