### ISSUE TITLE
can not work with mocha because of 'it'

### ISSUE THREAD

**Issue by ginus** [gkz/LiveScript#697]
when write mocha test code as below:
```
describe 'array.indexOf', ->
  it 'should return -1 when the value is not present', ->
    [1,2,3].indexOf(5).should.equal(-1)
    [1,2,3].indexOf(0).should.equal(-1)
```
lsc compile it to
```
describe('array.indexOf', function(it){
  return it('should return -1 when the value is not present', function(){
    [1, 2, 3].indexOf(5).should.equal(-1);
    return [1, 2, 3].indexOf(0).should.equal(-1);
  });
});
```
In first line the function has a param 'it', but we don't want that. it seems that livescript use 'it' as a internal keywords, so I hope change the internal 'it' to '$it', or else reason, I hope it works fine!

**Comment by ginus** [comment]
now I use this way to work
```
describe 'array.indexOf', (i)->
  it 'should return -1 when the value is not present', ->
    [1,2,3].indexOf(5).should.equal(-1)
    [1,2,3].indexOf(0).should.equal(-1)
```

**Comment by vendethiel** [comment]
Use `itt = it`, `(...) ->` to suppress any argument or `(,)` to have an unnamed one.

**Comment by igl** [comment]
another workaround: use ```mocha --ui tdd```
`The "TDD" interface provides suite(), test(), suiteSetup(), suiteTeardown(), setup(), and teardown().`

**Comment by vendethiel** [comment]
Ah, thanks, I was looking for the name.
