### ISSUE TITLE
LiveScript under Typescript

### ISSUE THREAD

**Issue by askucher** [gkz/LiveScript#698]
Hi. 

I would like to remind that livescript should be built under typescript instead of javascript. Because new angular 2.0 will use typescript. It means that LiveScript will loose all developers who will move to angular 2.0

**Comment by vendethiel** [comment]
?

**Comment by askucher** [comment]
I mean we will be not able to use livescript with angular 2.0

**Comment by askucher** [comment]
My client has concirns about livescript future because if it not support angular 2.0 it means livescript will not have a future

**Comment by vendethiel** [comment]
Angular 2 will **not** require typescript. You'll still be able to use JS, and thus LS, don't worry :-).

**Comment by vendethiel** [comment]
(also, javascript is a lot more than just angular)
