### ISSUE TITLE
String being parsed where it shouldn't

### ISSUE THREAD

**Issue by haskellcamargo** [gkz/LiveScript#703]
While using external libraries with JS, like jQuery and Handlebars, I realized that somethings don't work as expected, possibly by an error on parser.

Imagine the following situation:

```livescript
template = Handlebars.compile($ "#group-template" .html!)
```

What would you expect to be your output? Probably:

```javascript
template = Handlebars.compile($("#group-template").html());
```

But what you get?

```livescript
template = Handlebars.compile($(groupTemplate + "").html())
```

This wasn't supposet to happen, as much as "group-template" is a **string** and nothing else.

**Comment by vendethiel** [comment]
I don't understand the confusion, that's how interpolation works.

**Comment by haskellcamargo** [comment]
That's a new language feature, no? I need to re-re-re-read the docs again. :cry:

**Comment by robotlolita** [comment]
Interpolation can either use #<identifier> or '#{' <expression> }

**Comment by vendethiel** [comment]
New as in, different from coffeescript? yes.
New as in "new in LS"? It's been here before LS existed, in [coco 0.6.0](12bdb5538386800dec8fc54f63dc37c4ccf169d2)

**Comment by raine** [comment]
Solution is to use single quotes when you don't want string interpolation.

**Comment by igl** [comment]
or escape the hash `"\#foo"`

**Comment by gabeio** [comment]
@igl :+1: !

**Comment by gkz** [comment]
I should make this clear in the docs, but the general style is to always use single quotes unless you want to use interpolation, or you want to use single quotes in your string. Using this guideline avoids most issues.

**Comment by haskellcamargo** [comment]
Commonly, I use single quotes for chars and double quotes for lists of chars, like several programming languages do. A good concept to think about is string-interpolation, as much as it might cause problems in bad-designed languages, such as PHP. Swift has a nice way to work with interpolations.
