### ISSUE TITLE
value check space issue

### ISSUE THREAD

**Issue by gabeio** [gkz/LiveScript#708]
even though there is a space or not next to the `?` and the cookie is definitely a parameter I want the result to be checked for null not the parameter which I already know...

example of LiveScript:
```LiveScript
localStorage.getItem "cookie" ?
```

expected Javascript:
```Javascript
localStorage.getItem("cookie") != null
```

currently outputted Javascript:
```Javascript
localStorage.getItem("cookie" != null)
```

**Comment by vendethiel** [comment]
> localStorage.getItem "cookie" ?

that's not valid syntax

**Comment by gabeio** [comment]
the `?` is supposed to be like ruby's check this value if it exists. so I'd expect to be able to check:
```LiveScript
doSomething "to this" ?
```
which checks the result of doSomething with the parameter "to this" exists.
and I'd expect to be able to do:
```LiveScript
doSomething "to this"?
```
which checks if the value of "to this" exist then is a parameter of doSomething.

**Comment by vendethiel** [comment]
No, only dots close parenless calls.

**Comment by gabeio** [comment]
then is there a way that we could make ? be able to be like:
```LiveScript
doSomething "to this" .?
```
output
```Javascript
doSomething("to this")!= null
```

**Comment by vendethiel** [comment]
"Dot"s are for accessing properties :) you're not accessing anything here. This'd be inconsistent with the rest of our postfixes (like `!`)

**Comment by gabeio** [comment]
oh wait I can do this:
```LiveScript
doSomething "to this"
  ..?
```
does that sound like a bad idea? lol

**Comment by vendethiel** [comment]
I think the cure is worse than the disease (parentheses)

**Comment by igl** [comment]
`(doSomething "to this")?` makes a lot of sense to me when reading the code.
Embrace teh parentheses...

**Comment by gabeio** [comment]
@igl see that's different id use that and you're right that makes sense...
