### ISSUE TITLE
yield alone not working as expected

### ISSUE THREAD

**Issue by elclanrs** [gkz/LiveScript#713]
I reported [this bug](https://github.com/jashkenas/coffeescript/issues/3944) in CoffeeScript, and I found this issue in LiveScript as well:

This throws error:
```livescript
each = ->*
  f yield
```
This works:
```livescript
each = ->*
  x = yield undefined
  f x
```

**Comment by vendethiel** [comment]
was fixed in 96d4a9bca4f4111745b32c2243f083479fb3be6f

**Comment by elclanrs** [comment]
Ah, good to know. This is not on npm yet right?

**Comment by vendethiel** [comment]
right! 1.4 should come soon :).
