### ISSUE TITLE
Source map generation broken

### ISSUE THREAD

**Issue by raine** [gkz/LiveScript#714]
Broken in master, works before d8f3024188baf274274bad4878faf6a8f0ae6530

```sh
$ node_modules/.bin/lsc --map linked --compile --output lib src/index.ls
node_modules/livescript/lib/command.js:266
    js.setFile(sourceName);
```

**Comment by gkz** [comment]
@raine let me know if it's fixed for you

**Comment by raine** [comment]
I get no errors with `gkz/LiveScript` like previously, but from what I briefly tested with throwing an error, sourcemaps are not being used in the stacktrace. When I go back to `diggsey/LiveScript#sourcemaps` it works.

**Comment by raine** [comment]
Looks like `source-map-support` module is trying to read a source map from `lib/index.ls.map` while the correct one would be `lib/index.js.map`.

**Comment by darrrk** [comment]
Maybe close it

**Comment by vendethiel** [comment]
Is this confirmed to be fixed?

**Comment by darrrk** [comment]
Worked now

**Comment by vendethiel** [comment]
Thanks!
