### ISSUE TITLE
Ackowledge empty statement at end of function to "specify" void return type

### ISSUE THREAD

**Issue by ozra** [gkz/LiveScript#718]
To stop a function from returning implicitly, we can use 
```
some-fn = !->
    do-shit()
```
I think it would be very neat if we could also:
```
some-fn = ->
    do-shit()
    ;
```
The last semicolon should count as an empty statement, and therefor be 'undefined', and therefor return nothing.

**Comment by gkz** [comment]
You can use `void` for this purposr

**Comment by ozra** [comment]
That was indeed better :)
