### ISSUE TITLE
Update NPM documentation

### ISSUE THREAD

**Issue by furqanZafar** [gkz/LiveScript#719]
update the install instructions in the npm page (https://www.npmjs.com/package/livescript) from:
```
Have Node.js installed. sudo npm install -g LiveScript
```
to
``` 
Have Node.js installed. sudo npm install -g livescript
```

**Comment by impinball** [comment]
Just send a PR on the relevant readmes.

**Comment by gkz** [comment]
It's fixed, it will be updated on the next version
