### ISSUE TITLE
How can I use LiveScript across multiple files?

### ISSUE THREAD

**Issue by Lokkij** [gkz/LiveScript#724]
I have posted this question [on StackOverflow as well](http://stackoverflow.com/q/30241268/2428692). In short: how can I use LiveScript across mutliple `.ls` files? I've tried using `export` and `require`, but I can't get it to work.

It seems like such an obvious thing, but I haven't been able to find the solution.

**Comment by vendethiel** [comment]
If you're using nodejs: export and require will work.
If you want to use LS for client-side code, you'll need to setup something (gulp grunt browserify brunch broccoli dunno-what) to add the commonJS "header" (`common.define('module', function (..` or something) around each of your file (+ concatenating it).

There's no built-in mechanism to do that.
