### ISSUE TITLE
Move IRC to a slack channel

### ISSUE THREAD

**Issue by naturalethic** [gkz/LiveScript#730]
I think slack is becoming more prevalent that IRC.  As for myself, I use slack with a few organizations and always have it up on desktop and mobile.  What does everything think of moving discussion from the IRC channel to a livescript org slack channel?

**Comment by naturalethic** [comment]
Ok, per a discussion on the irc channel, there are some very strong opinions against a 'movement' of the discussion.  So let's adjust this to maybe making a parallel one and connecting them by gateway.  Anyway, any thoughts on this topic are appreciated.

**Comment by igl** [comment]
IRC is here to stay. Slack and alikes will come and go.

**Comment by vendethiel** [comment]
Also, useability/nonpresence of people aside, is it good to bet on closed source for open source projects?

**Comment by naturalethic** [comment]
@igl My concern is not whether slack or IRC are here to stay, but whether LiveScript is.  Whatever we can do to broaden it's reach is valuable to everyone who uses it.  I make my living with livescript and I'd prefer it didn't die in some obscure corner of the internet.

Anyway, I've revised my recommendation, not to replace the IRC channel, but to complement it.

@vendethiel That should address your concern, and if at least with slack all the logs & data can still be backed up somewhere, I'm not sure how much it matters if slack is closed source.

**Comment by igl** [comment]
How does sharing information behind a login help with popularity?
Slack does not fit in the os culture. There are other things that can be done to contribute.

Idea: Maybe @gkz or @vendethiel want to create some blank issues for things that need work and PR's are welcomed. Or a roadmap? Not sure if this was talked about before.

**Comment by cpursley** [comment]
[gitter](https://gitter.im) might make more sense than slack.

**Comment by gabeio** [comment]
:+1: to gitter or just keeping irc

**Comment by unclechu** [comment]
I vote to keep IRC. Slack is proprietary crap, isn't it?

**Comment by gabeio** [comment]
yes it is proprietary & the irc is only a gateway...

**Comment by hadriandeoliveira** [comment]
https://discordapp.com/ maybe?
@reactiflux (big community) moved from slack to there. Really nice app.

**Comment by furqanZafar** [comment]
:+1:  we have #livescript channel there too :)

**Comment by ozra** [comment]
@hadriandeoliveira - I saw no obvious mention of it being OS, maybe I missed that. Otherwise slack is just as good.

IRC: discussions has to be logged to be reached historically, often reachable via some webpage. What trouble is there backing up slack comments and extract to a web page? How many have hacked IRC recently? Does it matter that slack isn't OS? Does it matter that your processor or GFX-card is not OS?
Just some thoughts in general.
(I'm all super for OS in general)

**Comment by unclechu** [comment]
@ozra yes, it does, about GFX too, and we need to decrease it, but not add another thing that closed/proprietary/totally controlled and owned by corporation which follows their commercial interests. No, thanks.

**Comment by ozra** [comment]
@unclechu - well I'm with you on the general target - definitely. But also on that if a tool works great to further an OS project, that helps the movement. There's no black and white. I'm in the MIT-camp of licenses ;-) I'd prefer to see everything be OS in a perfect world. Anyway that was all my 2 mBTC.

**Comment by naturalethic** [comment]
@furqanZafar You have a livescript channel on discord?  Can you post an invite in here?

**Comment by naturalethic** [comment]
Anyone have any ideas on how to evangelize LiveScript a bit better?  Every one of us who use it would benefit from every new user.

**Comment by raine** [comment]
Other than active development, I don't really know.

**Comment by ozra** [comment]
I don't dev any JS related as of last year (sys dev), hence no LS, but I still mention it very often. As often as there's the slightest opportunity, haha - if people don't know about it - they can't fall in love with it :)

**Comment by furqanZafar** [comment]
@naturalethic https://discord.gg/0ZcbPKXt5bXiWbRE (expires in 24 hours) I tried to evangelize, but its more difficult than I thought :stuck_out_tongue:  
I created a few projects in livescript:
http://reactiflux.pipend.com/
http://furqanzafar.github.io/react-selectize/#/

There is a wiki somewhere with a list of new livescript projects too

**Comment by 2a2b** [comment]
You can make LiveScript anywere through http://sameroom.io/ . Not everyone likes to travel/moving all the time, so you can be there neighbor. 🤗
