### ISSUE TITLE
How to make livescript scripts immediately .go() on seen?

### ISSUE THREAD

**Issue by ceremcem** [gkz/LiveScript#731]
When I use LiveScript in an html file directly, I have no way to run livescript code immediately on seen. For example; 

```
...
<script src="livescript.js"></script>

<div class="my_target"></div>

<script type="text/ls">
# my livescript code will interact with div.my_target
</script>

<script>
/* a javascript code that will interact with div.my_target
</script>

<script type="text/ls">
# my livescript code does something else
</script>

<script>
    var LiveScript = require("LiveScript");
    LiveScript.go();
</script>
```

The LiveScript codes both will run, but the LiveScript code that interacts with `div.my_target` will interact with it **AFTER** the javascript code does, not **BEFORE**

If I define 

```
<script>
    var LiveScript = require("LiveScript");
    LiveScript.go();
</script>
```

part everytime right after a LiveScript code defined, then all LiveScript codes till this definition would run more than one time. 

```
### livescript code 1
### LiveScript.go()
...
### livescript code 2
### LiveScript.go()
...
### livescript code 3
### LiveScript.go()
...
```

When this code is executed:
- `livescript code 1` will run 3 times, first will run immediately after definition
- `livescript code 2` will run 2 times, first will run immediately after definition 
- `livescript code 3` will run 1 time,  this will runimmediately after definition

If it would be this way, LiveScript would be used in html **more easily** and would be used **like a native language of web development**

```
...
<script src="livescript.js"></script>
<script>
    var LiveScript = require("LiveScript");
    LiveScript.doSomeMagic_Kaboooommm();
</script>

...
<script type="text/ls">
# my livescript code
</script>

... more html

<script type="text/ls">
# my livescript code
</script>

...

<script type="text/ls">
# my livescript code
</script>
...
```

Is there anyway to do that?

**Comment by ceremcem** [comment]
The only way I could find is: 

```
<script>
    var LiveScript = require("LiveScript");
    var code = (function () {/*
      console.log "hello there!"
    */}).toString().match(/[^]*\/\*([^]*)\*\/\}$/)[1];

    LiveScript.stab(code,null,null);
</script>
```

**Comment by chisui** [comment]
Maybe you should consider moving your inline scripts to files and precompiling them.

I don't think it would be possible at all to intercept the loading of script tags. the `magic_go()` function would have to know what scripts come after it before they are even in the dom or stop javascript from executing when it hits the dom.

**Comment by impinball** [comment]
If your browser supports MutationObservers, you can include the [mutation-summary library](https://github.com/rafaelw/mutation-summary) and add this (untested) code before any LiveScript scripts:

```ls
# Obviously this needs transpiled

# Get the dependency (we need it synchronously)
document.head.appendChild <|
  (document.createElement 'script') <<<
    src: '//raw.githubusercontent.com/rafaelw/mutation-summary/master/src/mutation-summary.js'
    async: false

# Create the observer
new MutationSummary do
  queries: [element: 'script[type="text/ls"]']
  callback: (.0.added.forEach !-> LiveScript.run it.text)
```

Don't add `LiveScript.go()` to your page, or your scripts will run twice.

And FWIW, @chisui has a point in that it is probably better to precompile them.

**Comment by ceremcem** [comment]
I'm going to close this because I accepted the precompilation method is the appropriate way to go. Thanks.
