### ISSUE TITLE
a + b = 3 is interpreted as a + (b = 3) instead of emitting a syntax error

### ISSUE THREAD

**Issue by gkovacs** [gkz/LiveScript#736]
geza$ lsc
LiveScript 1.3.1 - use 'lsc --help' for more information
ls> a = 1
1
ls> b = 1
1
ls> a + b = 3
4

the issue is that it's turning it into a + (b = 3) whereas this should actually be a syntax error

**Comment by igl** [comment]
This is valid. The assignment operator can be used anywhere in a expression.

**Comment by vendethiel** [comment]
Yeah, it seems correct to me.
