### ISSUE TITLE
Error on parsing arguments

### ISSUE THREAD

**Issue by haskellcamargo** [gkz/LiveScript#737]
The new version of the compiler just have broken part of the parsing of arguments. In the previous version, I had a makefile to compile my application and I was able to use `lsc -cb ./src/main.ls -o ./bin` and have the expected result. In 1.4, The application tries to identify either `-o` or `--output` as files because of its position.

`lsc -cb ./src/main.ls -o ./bin` will throw `Can't find: -o.ls`, while `lsc -cb -o ./bin ./src/main.ls` works fine.

**Comment by gkz** [comment]
LS 1.4 fixed a regression introducted in 1.3.

See #610
