### ISSUE TITLE
Backcall constructors

### ISSUE THREAD

**Issue by schleumer** [gkz/LiveScript#738]
There's a way to use backcalls on constructors? e.g.:

```livescript
x, y <- new Foo
```

Becomes:

```javascript
(new Foo)(function(x, y){});
```

Which is kinda weird, because when i removed `new` it becomes:

```javascript
Foo(function(x, y){});
```

At the end my expectation was:

```javascript
new Foo(function(x, y){});
```

I think i'm doing something unexpected, but e.g. `Promise` object has a constructor that accepts a function as argument, and maybe backcalls could be useful for avoid cascadee. I don't think it's clear, my english is realy poor, but if needed i can give more examples and details :smile:

**Comment by AyaMorisawa** [comment]
How about using this LS code?
```ls
x, y <- new Foo!
```

**Comment by schleumer** [comment]
Wow! Worked like a charm, i think this one should be documented. There's lots of *hidden functionalities/features* that should too. Thanks!

**Comment by gabeio** [comment]
backcalls are documented & constructors are just javascript that passed through...
