### ISSUE TITLE
`export` keyword improvement proposal

### ISSUE THREAD

**Issue by ruby-random** [gkz/LiveScript#741]
For now, `export` assumes there is either `exports` variable, or `this` pointing to module's "exports table". In some cases this is indeed true. Consider this example:

    module.exports = -> ...
    export start = -> ...
    export stop = -> ...
    export status = -> ...

So, it is function exported with three additional properties. This example won't work in Livescript, because `module.exports` and `exports` are not synchronized in Node.js, and overwriting `module.exports` causes `exports` to point into orphaned namespace, and overwriting `module.exports` is extremely widespread in Node.js developer community. Of course, rewriting with cascades is possible:

    module.exports = tracker = -> ...
    tracker
        ..start = -> ...
        ..stop = -> ...
        ..status = -> ...

But it defeats the purpose of `export` keyword, as it can be no longer used, makes code unnecessarily verbose and self-repeating, and forces to export everything in the same place.

In order to address this issue, and to make code more uniform, I propose two changes:

1. As exporting stuff is rarely (never?) done in loops, and will only happen once when module is imported, `export` keyword can follow most recent `exports` reference. I propose to rewrite following Livescript code:

        export foo = -> 'something'
        export bar = -> 'something else'

    Into this equivalent Livescript code:

        get-export$ = ~>
            | module?.exports? => that
            | exports? => that
            | _ => @

        get-export$! .foo = foo = -> 'something'
        get-export$! .bar = bar = -> 'something else'

2. In order to make exporting named properties and exporting whole objects to be consistent, I propose to introduce banged version of `export`. It can be implemented as follows:

        export! -> 'me is root'

    Translate above code into this:

        set-export$ = ->
            if module?.exports?
                module.exports = it
                return
            get-export$! <<< it
    
        set-export$ -> 'me is root'

    As neither `this` or bare `exports` can be overwritten, we fallback to default `export` behaviour. When AMD/Require.js/etc will support generic exported objects, implementation can be tuned to reflect it accordingly.

Both changes preserve backwards compatibility.

**Comment by neersighted** [comment]
:+1: to this, trying to export a function (as the only export) is painful, as is `module.exports` clobbering.

**Comment by waynedpj** [comment]
:+1:

**Comment by igl** [comment]
The export keyword is a hack imo. LS really has no proper module syntax.
What's wrong with using plain old commonjs? It's certainly not a big change.

**Comment by vendethiel** [comment]
Moving to the other issues about adopting ES6 import/exports
