### ISSUE TITLE
Assignable `that` improvement proposal

### ISSUE THREAD

**Issue by ruby-random** [gkz/LiveScript#742]
Right now, `that` behaves just like an ordinary variable — it can be assigned to, and it exhibits no special properties, which can be confusing. I propose to make `that` a keyword, that proxies assignments to unwrapped condition value, if that is an `lvalue`.

Consider following example:

    set-export = !->
        that = it if module?.exports?

If this proposal was implemented, it would compile to

    var setExport;
    setExport = function(it){
        var that;
        if ((that = typeof module != 'undefined' && module !== null ? module.exports : void 8) != null) {
            module.exports = it;
        }
    };

If condition is not an `lvalue`:

    if 10 > 5
        that = \foo

It should throw a syntax error, because `(10 > 5) = 'foo'` makes no sense, and Livescript can determine that at compile time.

**Comment by vendethiel** [comment]
This is somewhat like coco's LEF (`<>`) feature. @gkz decided against adopting it, and I think I agree with him -- this'd make for a very complex, hard to understand thing more.
