### ISSUE TITLE
"Shared" statement to avoid the "call hell" with if / else / else if

### ISSUE THREAD

**Issue by nodecode** [gkz/LiveScript#744]
It would be great if there was a kind of <code>shared</code> statement for <code>if</code> / <code>else</code> / <code>else if</code> queries were, with which you can execute code for all control branches after asynchronous callbacks/backcalls.

For example, I have to write currently the following LiveScript code:

<pre>if mode == 1
    err, valid <- functionA
    return if !valid
    sharedFunction!
else if mode == 2
    err, result <- functionB
    err, result2 <- functionC result
    return if !result2.value
    sharedFunction!
else
    sharedFunction!

function sharedFunction
    doSomething!
    ...
</pre>

If there are complex nesting, this leads to countless nested functions and function calls, similar to the callback hell in JavaScript.

It would be great if you could simply write:

<pre>if x
    err, result <- functionA
    return if !valid
else
    err, result <- functionB
    err, result2 <- functionC result
    return if !result2.value
shared
    doSomething!
    ...</pre>

Or to stay in the same indent (like a backcall):

<pre><- shared
doSomething!
...</pre>

This could be realized relatively easily. With any "shared" statement, LiveScript must create a new function (eg <code>$lsSharedFunction1</code>), and call this at the end of the preceding <code>if</code> / <code>else</code> / <code>else if</code> statements.

I hope you understand what I mean.

**Comment by vendethiel** [comment]
What's the lexical scope? What's wrong with the function approach? Seems to me the "nest" doesn't change that much (one less level)

**Comment by nodecode** [comment]
In an online game, I use multiple asynchronous database queries to verify visitors by IP address and Session. There many nested callbacks (backcalls) with if / else / else if statements. After that specific actions are performed.

The code will be hard to handle for complex applications. In any multiply used code component with asynchronous database query, you must define a new function and call it at multiple places.

Even if you define all the functions on the same level, it's just not very intuitive always having to write a new function, if it can be done easily.

LiveScript was created for such simplifications, right?

**Comment by robotlolita** [comment]
@nodecode you can just use CPS or promise combinators instead. That would get rid of all complexity without needing to change the language.

Though for this case, you just need to split your functions a little more:

```ls
fn-a = (...) ->
  ...

fn-b = (..., cb) ->
  | mode == 1 => do-a ..., cb
  | mode == 2 => do-b ..., cb
  | otherwise => do-c ..., cb

do-a = (..., cb) ->
  blah
  bleh
  cb ...

do-b = (..., cb) ->
  cb ...

do-c = (..., cb) ->
  wow
  cb ...

a <- fn-b ...
b <- fn-a ...
...
```

**Comment by nodecode** [comment]
@robotlolita That would not make the case easier really.

Why not just implement a shared statement? That would make all callbacks with if / else statements as easy as normal backcalls.

**Comment by robotlolita** [comment]
@nodecode you have a problem of abstraction. Adding new really specific, complex and exotic control-flow statements isn't going to make the problem go away.

Extending the language is hard, because you need to consider how the feature interacts with all existing features in the language. LS has already too many specific features, and LS2 is going to remove many of them to reduce the language's complexity.

In the case of your proposed `shared` block, it means that whole block transformations must be done, which is neither trivial, nor easy to reason about (the resulting program). What's the semantic of `shared` in a general level? How does it interact with all other features? What happens if multiple `shared` blocks are given? What happens with nested blocks? With nested closures? With complex CPS functions? Those are all questions you need to ask yourself.

**Comment by gabeio** [comment]
I feel like I am missing something here... why are you not simply calling the sharedFunction after the if statement?
ie:
```LiveScript
if mode == 1
    err, valid <- functionA
    return if !valid
else if mode == 2
    err, result <- functionB
    err, result2 <- functionC result
    return if !result2.value
sharedFunction!

function sharedFunction
    doSomething!
    ...
```

**Comment by raine** [comment]
@gabeio I understood that @nodecode doesn't want to define the function every time.

**Comment by nodecode** [comment]
@gabeio Your first code would not execute the function after the backcalls, and also the return statement would therefore have no effect.

In JavaScript, it would simply generate:

```JavaScript
if (mode === 1) {
  functionA(function(err, valid){
    if (!valid) {
      return;
    }
  });
} else if (mode === 2) {
  functionB(function(err, result){
    return functionC(result, function(err, result2){
      if (!result2.value) {
        return;
      }
    });
  });
}
sharedFunction();
function sharedFunction(){
  doSomething();
  throw Error('unimplemented');
}
```

You could here omit the function <code>sharedFunction</code>, and directly run <code>doSomething! ...</code>, it would have exactly the same behavior:

```LiveScript
if mode == 1
    err, valid <- functionA
    return if !valid
else if mode == 2
    err, result <- functionB
    err, result2 <- functionC result
    return if !result2.value

doSomething!
...
```

The sense of the "shared" statement is that the code is called **after** the backcalls (without defining an extra function, and insert it manually at the end of all the if / else statements):

```LiveScript
if mode == 1
    err, valid <- functionA
    return if !valid
else if mode == 2
    err, result <- functionB
    err, result2 <- functionC result
    return if !result2.value
<- shared
doSomething!
...
```

This code should result in the following:

```JavaScript
if (mode === 1) {
  functionA(function(err, valid){
    if (!valid) {
      return;
    }
    return lsSharedFunction1();
  });
} else if (mode === 2) {
  functionB(function(err, result){
    return functionC(result, function(err, result2){
      if (!result2.value) {
        return;
      }
      return lsSharedFunction1();
    });
  });
}
function lsSharedFunction1(){
  doSomething();
  throw Error('unimplemented');
}
```

Your second code with <code>async.parallel</code> would make it even more complicated.

**Comment by phanimahesh** [comment]
We already have way too many features in LS and efforts are being made to remove everything that is not very widely used. I can relate to this use case, but am not convinced if adding a new keyword to the language would be the best way to handle this. Also, it is not immediately obvious what magic is happening here behind the scenes.

As @robotlolita said, extending the language is non trivial, so the benefits have to be weighed against the costs, keeping in mind the usage.

On a sidenote, @robotlolita can you please explain your code snippet? I don't get what you are trying to do there.

**Comment by robotlolita** [comment]
@phanimahesh just factoring out @nodecode's original code into separated asynchronous functions and combining/sequencing them using existing language constructs, rather than writing a big block of structured/procedural code.

**Comment by gabeio** [comment]
Refactor and/or use something like I suggested with the async library is all you need for this. Adding a flow control statement that is not in JS and is really not that hard to do on your own, I just think is a waste.

**Comment by nodecode** [comment]
What if we use a <code>sync if</code> statement instead. E.g:

```LiveScript
sync if process.env.NODE_ENV == 'production'
    err, transactionId <- bitcoin.sendFrom 'main', coins
socket.emit 'ready'
new db.Payout do
    hits: user.hits
    coins: jackpot.count
    address: user.address
    highscore: true
.save!
```

Notice: <code>socket.emit 'ready'</code> and <code>new db.Payout ... .save!</code> should not be executed before <code>bitcoin.sendFrom</code> is finished.

Which would be equal to:

```LiveScript
if process.env.NODE_ENV == 'production'
    err, transactionId <- bitcoin.sendFrom 'main', coins
    lsSyncIfFunction1!
else lsSyncIfFunction1!

function lsSyncIfFunction1
    socket.emit 'ready'
    new db.Payout do
        hits: user.hits
        coins: jackpot.count
        address: user.address
        highscore: true
    .save!
```

And would compile the following JavaScript code:

```JavaScript
if (process.env.NODE_ENV === 'production') {
  bitcoin.sendFrom('main', coins, function(err, transactionId){
    return lsSyncIfFunction1();
  });
} else {
  lsSyncIfFunction1();
}
function lsSyncIfFunction1(){
  socket.emit('ready');
  return new db.Payout({
    hits: user.hits,
    coins: jackpot.count,
    address: user.address,
    highscore: true
  }).save();
}
```

Because only one <code>if</code> statement would be available at the beginning, and only <code>else if</code> and <code>else</code> can be followed (but not another <code>if</code>), it would may be easier to implement.

If more <code>else if</code> statements follow, also here a call to lsSyncIfFunction1 is added.

**Comment by gabeio** [comment]
```
async.waterfall [
    (water)->
        bitcoin.sendForm 'main', coins, (err,transactionId)->
            water err,transactionId
    (water)->
        socket.emit 'ready'
        new db.Payout {
            hits: user.hits,
            coins: jackpot.count,
            address: user.address,
            highscore: true
        }
        .save!
]
```

**Comment by vendethiel** [comment]
This feature request is going to start like some weird complicated beast...

**Comment by gabeio** [comment]
All of the features suggested are not really anything big they are tiny snippets for them that are not going to be used by anyone else... They can fork LiveScript and make a version for themselves that incorporates these features and suggest a pull but I don't see value in either of these except for edge cases.

**Comment by robotlolita** [comment]
@nodecode `sync if` would be a misnomer, since it's impossible to do async→sync transformations in the general case without whole-program transformations (that involves recompiling all of the libraries you use, so not really practical).

Again, using CPS combinators or moving your code to promises fixes all of the problems you've pointed out. There's no need to change the language for any of them.

For example, here's how simple combinators and the right abstraction can reduce the complexity of complicated operations, like applying an operation to every file in a directory, recursively, or creating a path of directories:

https://github.com/sorellabs/ffs/blob/master/src/utils.ls#L47-L60
https://github.com/sorellabs/ffs/blob/master/src/attributes.ls#L112-L118
https://github.com/sorellabs/ffs/blob/master/src/directory.ls#L77-L90

**Comment by vendethiel** [comment]
I think all has been said.
