### ISSUE TITLE
Scope persistence inside loops?

### ISSUE THREAD

**Issue by kkirby** [gkz/LiveScript#747]
Hello,

I'm not sure if this is a feature request, or a question of how to do something.

Say I have this code:

    result = for a in [1,2,3]
        -> a * 2

    alert (result.map (.call()) |> JSON.stringify)

The expected result would be `[2,4,6]`, but instead the result is `[6,6,6]`. Is there a way to retain the scope of `a` since it's being used in a nested function declaration?

**Comment by vendethiel** [comment]
use `for let`
