### ISSUE TITLE
Concept of "breaker" token to fix cascades, backcalls and argument objects

### ISSUE THREAD

**Issue by ruby-random** [gkz/LiveScript#748]
There is known difficulty writing cascades referring to objects declared in multiple lines. Consider following code:

    new Client do
        user-name: 'foobar'
        password: 'meow-meow'
        ->
            oh-yeah!
        ..on \connected ->
            console.log 'Connected!'
        ..on \disconnected ->
            console.log 'Disconnected!'

While to programmer it's fairly clear that cascade is referring to newly created `Client(opts, cb)` instance, to parser this construction looks ambiguous, and `..on \event` constructs would be rejected with "stray reference" errors. Of course, it's possible to assign cascade item to variable beforehand, but that has two drawbacks — it litters scope with temporary variables, and it does the job instead of cascade.

In order to address this, and to remove ambiguity that may appear when using several nested cascades, I propose to introduce `~` — "breaker" token. It's purpose is to reset parser indentation tracking, so ambiguity using multilevel constructs is resolved. The code example above will then look as:

    Client do
        user-name: 'foobar'
        password: 'meow-meow'
        ->
            oh-yeah!
    ~
        ..on \connected ->
            console.log 'Connected!'
        ..on \disconnected ->
            console.log 'Disconnected!'

Also, consider this code. It should print messages from "First" to "Fifth" in order, based on for how long function execution was delayed.

    delay 2000 ->
        say "Second!"
        delay 2000 ->
            say "Fourth!"
            delay 1000 ->
                say "Fifth!"
        delay 1000 ->
            say "Third!"
    delay 1000 ->
        say "First!"

Backcalls were introduced to reduce indentation occurring from nested asynchronous calls. However, when multiple backcalls have to happen simulatenously, that doesn't add much to solving indentation problems:

    do
        <- delay 2000
        say "Second!"
        do
            <- delay 2000
            say "Fourth!"
            <- delay 1000
            say "Fifth!"
        do
            <- delay 1000
            say "Third!"
    do
        <- delay 1000
        say "First!"

Using breaker, this code can be made more clear

    <- delay 2000
    say "Second!"
    do
        <- delay 2000
        say "Fourth!"
        <- delay 1000
        say "Fifth!"
        ~
        <- delay 1000
        say "Third!"
    ~
    <- delay 1000
    say "First!"

Similarly, when there is the need to pass multiple separate objects as parameters, but LiveScript glues them without warning. So you have to write verbose constructs like this:

    Foo do
        {
            alpha: 123
            beta: 999
        }
        {
            alpha: 'foo'
            bar: 'bar'
        }

That could be written lot easier with the help of breaker:

    Foo do
        alpha: 123
        beta: 999
        ~
        alpha: 'foo'
        bar: 'bar'

**Comment by ozra** [comment]
Just for thought - using existing constructs (this is of the top of my head, and it was a while since I coded LS):

How about:
```livescript
(new Client do
    user-name: 'foobar'
    password: 'meow-meow'
    ->
        oh-yeah!
) 
    ..on \connected ->
        console.log 'Connected!'
    ..on \disconnected ->
        console.log 'Disconnected!'
```
Or better yet:
```livescript
new Client(
    user-name: 'foobar'
    password: 'meow-meow'
    ->
        oh-yeah!
) 
    ..on \connected ->
        console.log 'Connected!'
    ..on \disconnected ->
        console.log 'Disconnected!'
```

Same line count, much clearer intent.

```livescript
delay 2000 ->
    say "Second!"
    delay 2000 ->
        say "Fourth!"
        <- delay 1000
        say "Fifth!"
    delay 1000 ->
        say "Third!"
delay 1000 ->
    say "First!"
```
Looks clearer to me then going over the river for water. Parallelism is obvious, sequential async is obvious.

```livescript
Foo(
    alpha: 123
    beta: 999
,
    alpha: 'foo'
    bar: 'bar'
)
```
The above should work with do notation imo, but I don't think it does.

Parentheses are not the enemy - unclear intent and code is.

**Comment by vendethiel** [comment]
I think the last example can be made to work with `;`

**Comment by phanimahesh** [comment]
> Parentheses are not the enemy - unclear intent and code is.

:+1:

**Comment by vendethiel** [comment]
Closing as `;` to have an explicit dedent works, and the `-` special token is a bit too crazy to add.
