### ISSUE TITLE
yield inside a for let

### ISSUE THREAD

**Issue by kkirby** [gkz/LiveScript#749]
Hello,

Again, I'm not sure if this is a feature request, bug, or just me learning things.

How do I `yield` inside of a `for let` statement?

	->*
	    a = for let a in [1,2,3]
	        -> a
	        yield abc()

**Comment by vendethiel** [comment]
whoops... we don't generate the correct yield froms for closures yet.

**Comment by kkirby** [comment]
No worries. I'm just glad that I found an issue instead of failing to do proper research.
