### ISSUE TITLE
Curry named functions

### ISSUE THREAD

**Issue by kkirby** [gkz/LiveScript#751]
If you have a named function that curries (I think that's how you'd name it?), the function isn't scoped properly.

    :abc (x,y) --> x + y

Expected:

	var abc;
	abc = (curry$(function(x, y){
	  return x + y;
	}));

Actual:

	(curry$(function abc(x, y){
	  return x + y;
	}));

**Comment by vendethiel** [comment]
it's mostly because "labels" attach to "blocks", nothing else. (a for, a function, etc). You ought to use `a = -->` or

```livescript
~function a(b, c)
  b
```

for curried functions anyway ;-).

**Comment by kkirby** [comment]
I agree to use `a = -->`, but is this considered expected functionality? I was just reading the code and saw that you can name a function using the label syntax and saw that currying doesn't work with this. If this is expected, should the parser maybe throw an error when this is occurred?

**Comment by waynedpj** [comment]
also having an issue with creating a curried named function as suggested [above](https://github.com/gkz/LiveScript/issues/751#issuecomment-120096415) ala

```livescript
~function named (a, b)
  a + b
```
which compiles to a bound named function w/ 1.4.0 as expected

```javascript
var this$ = this;
function named(a, b){
  return a + b;
}
```
all the other combinations i have tried (e.g. `--function named`, `-function named`) are giving compilation errors or not currying the named function.

perhaps it is not possible to create a curried named function as they are constants?

thanks.

**Comment by igl** [comment]
The problem is that you can't.
Wrapping a function statement in Javascript will make it a function expression.
Same as:

    foo = :foo -->

The only fix i can think of would be to wrap the body of the function and not the declaration.
