### ISSUE TITLE
[Error: Parse error on line 1: Unexpected 'NEWLINE']

### ISSUE THREAD

**Issue by daveeel** [gkz/LiveScript#756]
I'm on latest Mac OS X and live script 1.4. Trying to follow the examples from official site. Got the following error. However the code has no problem in the official site code runner. Why?
~~~
ls> for k, v of {a: 1, b: 2}
[Error: Parse error on line 1: Unexpected 'NEWLINE']
~~~

**Comment by wolfflow** [comment]
Actually it fails also on site REPL.
You might use this one:
```livescript
for k, v of {a: 1, b: 2} then
```

**Comment by wolfflow** [comment]
And the example actually was like this
```livescript
for k, v of {a: 1, b: 2}
  "#k#v"
```

**Comment by vendethiel** [comment]
> However the code has no problem in the official site code runner. Why?

That code is invalid, and properly rejected by the site runner.

**Comment by daveeel** [comment]
Hi @vendethiel the issue is that I pressed enter after the first line and wanted to input the 2nd line in the interpreter. For other test that need 2nd line input, I don't see this kind of error ... so could that be a bug?

**Comment by daveeel** [comment]
@wolfflow , yes, it seems only putting the 2 lines in 1 line with "then" works

**Comment by vendethiel** [comment]
Ah! Okay. What you want is ctrl-j, multiline input

**Comment by daveeel** [comment]
oh, I see, what a catch! "if" statement don't need this and never need similar to take care multiline in other language interpreters for many years ... thanks anyway :)
