### ISSUE TITLE
Singleton Pattern

### ISSUE THREAD

**Issue by ceremcem** [gkz/LiveScript#760]
Hi, 

I wanted to implement Singleton Pattern via LiveScript. I made a few changes from this document: https://coffeescript-cookbook.github.io/chapters/design_patterns/singleton

```
# make a singleton
class ExampleSingleton
  instance = null

  class SingletonClass
    ~>
      console.log 'this is private singleton init!'
      @x = 'foo'

  get-singleton: ->
    instance ?:= new SingletonClass!


test = new ExampleSingleton! .get-singleton!
test2 = new ExampleSingleton! .get-singleton!

console.log 'test: ', test.x
console.log 'test2: ', test2.x

test.x = 'bar'

console.log 'test: ', test.x
console.log 'test2: ', test2.x
```

What I really wondered is, why I can not define the `ExampleSingleton` class and use it as follows: 

```
...
class ExampleSingleton
  instance = null

  ~>
    instance ?:= new SingletonClass!

  class SingletonClass
    ~>
      console.log 'this is private singleton init!'
      @x = 'foo'    


test = new ExampleSingleton!
...
```

**Comment by igl** [comment]
What does not work? I works for me as expected.
And what's the advantage over a simple object literal?

https://medium.com/javascript-scene/common-misconceptions-about-inheritance-in-javascript-d5d9bab29b0a

**Comment by ceremcem** [comment]
I expect both class definitions behave the same way with their own usages. They might work as you expect but what do you expect? 

First code outputs: 
```
this is private singleton init!
test: foo
test2: foo
test: bar
test2: bar
```

This is the only expected singleton pattern output. But second code: 

```
class ExampleSingleton
  instance = null
  ~>
    instance ?:= new SingletonClass!

  class SingletonClass
    ~>
      console.log 'this is private singleton init!'
      @x = 'foo'


test = new ExampleSingleton!
test2 = new ExampleSingleton!

console.log 'test: ', test.x
console.log 'test2: ', test2.x

test.x = 'bar'

console.log 'test: ', test.x
console.log 'test2: ', test2.x
```

outputs: 

```
test: undefined
test2: undefined
test: bar
test2: undefined
```

So this is not behaving like a singleton. 

#EDIT:

However, this code works as expected (outputs the same output with the first example): 
```
# make a singleton
class ExampleSingleton
  instance = null
  ~>
    instance ?:= new SingletonClass!
    return instance

  class SingletonClass
    ~>
      console.log 'this is private singleton init!'
      @x = 'foo'


test = new ExampleSingleton!
test2 = new ExampleSingleton!

console.log 'test: ', test.x
console.log 'test2: ', test2.x

test.x = 'bar'

console.log 'test: ', test.x
console.log 'test2: ', test2.x
```

**Comment by robotlolita** [comment]
@ceremcem why not use an object literal? That's exactly why they exist.

**Comment by vendethiel** [comment]
Constructors are, by default, hushed -- that's by design.

**Comment by ceremcem** [comment]
@robotlolita Because simply I don't know JavaScript (and LiveScript) well yet :) Now it's time to port our [DCS library](https://github.com/ceremcem/aktos-dcs) to LiveScript and I wrote [`Actor`, `ActorBase` and `ActorManager` classes](https://github.com/ceremcem/aktos-dcs/blob/master/aktos_dcs/gevent_actor.py#L159) that way, so I simply made an attempt to translate them from Python to LiveScript. That's why. But now I'm looking at object literal and see if it fits my case. Thank you.

**Comment by ceremcem** [comment]
@robotlolita By using a singleton class, I can benefit from "extends" facility of the language: 

```
class ActorBase
  ~>
    console.log "this is actor base!"
    @x = 'bar'
    @y = 'baz'

  test: ->
    return @x + @y


# make a singleton
class ActorManager
  instance = null
  ~>
    instance ?:= new SingletonClass!
    return instance

  class SingletonClass extends ActorBase
    ~>
      super ...
      console.log 'this is private singleton init!'
      @x = 'foo'


class Actor extends ActorBase
  ~>
    super ...
    console.log "this is actor!"



test = ActorManager!
console.log test.x, test.y, test.test!

test3 = Actor!
console.log test3.x, test3.test!


test4 = ActorBase!
console.log test4.x, test4.test!
```
