### ISSUE TITLE
Problem with the site CSS

### ISSUE THREAD

**Issue by ceremcem** [gkz/LiveScript#761]
There is a problem with the site CSS, that leads the compiler/REPL on the right side overlap long lines of middle column (the explanations column): 
![screenshot_2015-08-04_23-56-33](https://cloud.githubusercontent.com/assets/6639874/9072657/20f83224-3b05-11e5-80b6-14ae174d755d.png)

**Comment by pyros2097** [comment]
Yeah ... Needs to be fixed for some time now
