### ISSUE TITLE
Wrong extension of compiled file

### ISSUE THREAD

**Issue by mnn** [gkz/LiveScript#763]
`lsc --no-header --watch --compile YouTube_-_change_detector.user.ls` produces a file incorrectly named `YouTube_-_change_detector.user` (notice that there is missing the `js` extension).

**Comment by heavyk** [comment]
I like this feature :) I often times have `file.html.ls` -> `file.html`

just rename your file to `YouTube_-_change_detector.user.js.ls`

**Comment by mnn** [comment]
Oh, didn't know it's intended. Thank you for advice:). I'll close it.

**Comment by raine** [comment]
Not a bug?

**Comment by vendethiel** [comment]
Nope, working as intended, as other issues point out.
