### ISSUE TITLE
Programmatic API: Compile to .json option

### ISSUE THREAD

**Issue by daveeel** [gkz/LiveScript#767]
I'm checking the option to programatically compile .json.ls to .json. Basically looking for easier .json maintenance.

As I read from the official site, there are only 4 options for .compile(): bare, header, const, filename
Option { json: true } seems not available for .compile() 

Is there a way?

**Comment by vendethiel** [comment]
I'm afraid not, but there definitely should be.

**Comment by gkz** [comment]
using `json: true` works with `.compile` - I guess this is not documented on the website

**Comment by vendethiel** [comment]
Oh, i forgot this was changed. My bad!

**Comment by daveeel** [comment]
Yes, just tested and worked by {+json} option. It was other errors from my code but debug message misled to look like it's the compile error.

Thanks.

**Comment by rhendric** [comment]
Documentation for this option has been added to the [gh-pages-next](https://rawgit.com/gkz/LiveScript/gh-pages-next/index.html) staging branch. It'll go live with the [1.6 release](https://github.com/gkz/LiveScript/issues/1016).
