### ISSUE TITLE
`let` operator with `return`

### ISSUE THREAD

**Issue by unclechu** [gkz/LiveScript#768]
Here I want return `foobar` if it isn't `null` or `undefined` otherwise return `foobar*2`:
```livescript
f = (foobar) ->
	let x = foobar then return x if x?
	foobar*2
```
Looks correct, but it compiles to:
```javascript
var f;
f = function(foobar){
  (function(x){
    if (x != null) {
      return x;
    }
  }.call(this, foobar));
  return foobar * 2;
};
```
and it means that we doesn't return any value in `let` operator.

**Comment by igl** [comment]
> I want return foobar if it isn't null or undefined otherwise return foobar*2:

You probably mean: I want return foobar if it IS null or undefined otherwise return foobar * 2:

let is not a variable declaration like es6-let. To catch the return value of a let block:

    f = (foobar) ->
        y = let x = foobar
            return x if x?
        y * 2

and then: Why use let at all when you don't really need a private scope:

    function f foobar
        if foobar? then foobar * 2 else foobar

**Comment by vendethiel** [comment]
Right. It's a bit sad we don't mirror es6 here, but it's fairly well documented.
