### ISSUE TITLE
one liner empty function?

### ISSUE THREAD

**Issue by daveeel** [gkz/LiveScript#769]
I could get
~~~
function render(){}
~~~

by

~~~
function render
  return
~~~

Without 'return' there will be error. Is there a one-liner to get this kind of named empty function?

**Comment by heavyk** [comment]
`render = ->` will yield `var render = function() {};`

will that work?

**Comment by daveeel** [comment]
No.

render = function() {};

is NOT the same as in JS:

function render() {};

You may read the "Named Functions" part of LiveScript doc.

**Comment by vendethiel** [comment]
You can use the `=>`.

**Comment by daveeel** [comment]
Great. For my record here :)
function render =>
