### ISSUE TITLE
How to disable source maps in node?

### ISSUE THREAD

**Issue by AriaMinaei** [gkz/LiveScript#771]
My setup is something like this:
```javascript
require('livescript');
require('./src/server.ls');
```

So, LiveScript directly patches the node environment. Within this setup, how can I optionally disable source maps, so that stack traces point to the line numbers of the compiled javascript code (Hopefully with a hint to which LS file the JS code was generated from)?

**Comment by igl** [comment]
I am surprised that by just doing `require('livescript')` you already get source map support in node.
If you don't precompile where is the value of getting js line numbers when you don't get the js code?
Just precompile your code without sourcemaps.

**Comment by AriaMinaei** [comment]
Well now that you said that, I'm not sure :)

I assumed I'm getting source maps because the stack traces have `.ls` extensions and don't point to relevant lines when I look up the line numbers in a manually compiled js file.

But if you think source maps aren't actually enabled by default in node, then I should try to reproduce the bug.
