### ISSUE TITLE
Compiling file with dots

### ISSUE THREAD

**Issue by nazar-pc** [gkz/LiveScript#772]
`a0.config.ls` is eventually compiled to `a0.config` while I expected it to be `a0.config.js`

**Comment by heavyk** [comment]
lala.html.ls is compiled to lala.html

intended behaviour.

a0.config.js.ls is what you want

**Comment by nazar-pc** [comment]
Actually, I am using CoffeeScript, LESS, SCSS, HAML, Jade - all of them just replace own extension with JS/CSS/HTML, not droping it entirely.
Also IDE usually visually group such files as source and generated, which is not the case for LiveScript.

I can't say that when compiled LiveScript file becomes HTML file is expected behavior, it is not logical, LS > JS is logical.

So indeed, it was totally surprising behavior and hopefully it might be fixed to align with literally all similar tools.

Now I'm forced to do something weird like `lsc --print --compile a0.config.ls > a0.config.js` while other tools allow me to do it much simpler like `lsc --compile a0.config.ls`
