### ISSUE TITLE
How can I get all defined methods of a class? 

### ISSUE THREAD

**Issue by ceremcem** [gkz/LiveScript#773]
How can I get all defined methods of a class?

**Comment by vendethiel** [comment]
```livescript
meths = [key for key in Object.getOwnPropertyNames(obj) when typeof! obj[key] is 'Function']
```

probably?

**Comment by ceremcem** [comment]
Nope, it returns an empty list, but I got the idea. Let me read about this.

**Comment by igl** [comment]
Too bad JS will never address it's terminology issues. The question `how to get the defined methods of a class` should really be `how to get the property names of the prototype`.
Bringing the class keyword back will postpone the issue of confusion and misunderstanding another century. I will not shake hands with anyone on the TC. I am looking forward to the post-javascript era. Will i still be alive and coding? Do i have to teach javascript to my kids?

Anyway... here you go: `Object.getOwnPropertyNames(Array.prototype)`

**Comment by ceremcem** [comment]
Thank you for the proper keyword of this problem. 

Here is working one liner in my situation: 
```
[key for key of actor.__proto__ when typeof! actor[key] is 'Function']
```
where `actor` is the instance of `Actor` class. 

Thank you all.

**Comment by igl** [comment]
FYI: http://webreflection.blogspot.de/2013/03/5-reasons-you-should-avoid-proto.html

**Comment by ceremcem** [comment]
Is the following appropriate: 

```
methods = [key for key of Object.getPrototypeOf(actor) when typeof! actor[key] is 'Function']        
```

**Comment by igl** [comment]
:+1:
