### ISSUE TITLE
A pattern matching example must be put on main page

### ISSUE THREAD

**Issue by ceremcem** [gkz/LiveScript#774]
Such as: 

## Pattern Matching 

```
[a, b] = [1, 2]
# => a = 1, b = 2 

[a, ...b] = [1, 2, 3]
# => a = 1, b = [2, 3]

[a, ...b, [c, d]] = [1, 2, 3, [4, 5]]
# c = 4

some-complex-var = 
  * ['subject', ['key', 'value']]
  * ['subject2', ['key2', 'value2']]

for [s, [k, v]] in some-complex-var 
  if s is 'subject2'
    # do something with subject2's key
```

**Comment by vendethiel** [comment]
That's destructuring, not pattern matching, and I think we have it in our docs, right?

**Comment by ceremcem** [comment]
Ok, my fault. I learnt what pattern matching is from [elixir docs](http://elixir-lang.org/getting-started/pattern-matching.html) and they used the same operator both for pattern matching and destructing. But where is pattern matching examples by the way?
