### ISSUE TITLE
Back quote instead of back slash for one-word string literals would look way better

### ISSUE THREAD

**Issue by baturinsky** [gkz/LiveScript#775]
\There \is \too \much \noise \when \it \is \written \like \this
Javascript inline could use double single backquotes instead.

**Comment by igl** [comment]
This syntax is originally borrowed from lisp. In the coffee/ls world using backticks for something else than escaping might be a bit confusing though and harder to tokenize.

I personally don't use this feature at all. Because why.

**Comment by baturinsky** [comment]
For some spacious data structures, like CoffeeKup-like templates

**Comment by gabeio** [comment]
:-1: I never use the backslash. I've been burned too many times with it. Another character to do the same thing is double useless. Just use quote strings it can span multiple lines and ignores the `newline`.

**Comment by gkz** [comment]
Yeah, I'm not a fan either, but it's here for now

**Comment by waynedpj** [comment]
just throwing my :+1: for the backslash string, very handy when writing quick literals .. one of the many niceties of LS IMHO.

thanks.
