### ISSUE TITLE
Function application should have a higher precedence than function composition (<<)

### ISSUE THREAD

**Issue by esrch** [gkz/LiveScript#776]
When currying functions, applying functions before composing them usually results in cleaner code.

Here is a simple example of what I mean:

```livescript
o = {a: {b: {c: 4}}}

double = (* 2)
get-in = (keys, obj) -->
  if keys.length is 1
    then obj[keys[0]]
    else get-in keys.slice(1), obj[keys[0]]

double-c = double << get-in ['c'] << get-in ['a', 'b']   #=> Doesn't work
double-c = double << (get-in ['c']) << (get-in ['a', 'b'])   #=> Works, but not as readable

double-c o
```

I believe changing the precedence of the << and >> operators would improve the usefulness of currying and composition in writing cleaner code. It would also make it consistent with other languages (e.g., the dot operator in Haskell).

**Comment by vendethiel** [comment]
Alas, this'd break pretty much all LS code existing. There's another issue for this (well, more generally, binop closing impicit calls)
