### ISSUE TITLE
How to include prelude to run .ls file?

### ISSUE THREAD

**Issue by daveeel** [gkz/LiveScript#777]
Working on a command Iine util, I tried
~~~
lsc -wd my.ls
~~~
where I have a simple use of map. But I got:
~~~
ReferenceError: map is not defined
~~~

Using "lsc -d" interactively to test the code is all good. Also tried "--prelude", which makes no difference.

I also have "npm i -g prelude-ls" but always got "Error: Cannot find module 'prelude-ls'" when I tried to require it in node.

So, what's missing?

**Comment by daveeel** [comment]
Ok, turns out it's old issue #290 

So install prelude locally and require it inside my.ls is the way to go.

Does that mean we should have  -d --prelude really work for "lsc -d" to run .ls script ... missing feature ?

**Comment by vendethiel** [comment]
That's how node's require work: no globals
