### ISSUE TITLE
Math constant "Infinity" treated as function

### ISSUE THREAD

**Issue by yuri0** [gkz/LiveScript#779]
````Livescript
[Infinity Infinity]
````
compiles to
````Javascript
[Infinity(Infinity)];
````
when it should be
````Javascript
[Infinity, Infinity]
````

**Comment by vendethiel** [comment]
we have no info other than "it's not a keyword", which is why this happens.

**Comment by igl** [comment]
Interesting. The same happens with `[NaN NaN]`

**Comment by yuri0** [comment]
@vendethiel This is a bug report, not a question. You have the info that it is a numeric constant, and so cannot be a function etc.

**Comment by vendethiel** [comment]
No, I disagree. Ultimately, @gkz will decide, but I strongly think we should **not** have a long list of JS constants that we'd track by hand, to know how the parser should react.

You can even change it:

```
(function (Infinity) { return Infinity; })(3);
```

**Comment by yuri0** [comment]
Whoops, thought you couldn't use it as a variable name. Carry on then.
