### ISSUE TITLE
is jQuery.extend(true, ...) function planned to implement in prelude-ls?

### ISSUE THREAD

**Issue by ceremcem** [gkz/LiveScript#780]
`jQuery.extend` does a deep merge of two dictionaries and Livescript has really good human readable syntax of dictionaries/lists, which in turns a [More complex inheritance in YAML](http://stackoverflow.com/questions/14184971/more-complex-inheritance-in-yaml) is implemented already. 

Is there any plan to support this functionality in pure Livescript?

**Comment by igl** [comment]
Livescript has this functionality in the language: `{a:1} <<< {b:2}`

**Comment by vendethiel** [comment]
That's not a deep copy, though.

**Comment by vendethiel** [comment]
Anyway, this is the wrong issue tracker :-).

**Comment by raine** [comment]
`<<<` mutates and has no place in livescript imo

**Comment by vendethiel** [comment]
You can use our "cloneport" `with` :)

**Comment by igl** [comment]
since `with` extends the prototype, you can still mutate the original object on the second level and keys are no longer enumerable-own-properties!

are we having fun?

**Comment by ceremcem** [comment]
`<<<` does exactly `jQuery.extend(false, ...)` does. 

Question: How can we do the same thing: http://jsfiddle.net/2pKRk/87/

Question2: Why shouldn't we prefer

```
copy = (x) -> JSON.stringify x |> JSON.parse

x = (copy y) <<< z
```
over: 
```
x = y with z
```
since with first approach, x is Json serializable which is useful at least while debugging.

**Comment by igl** [comment]
https://github.com/jonschlinkert/assign-deep#related-projects

I tend to avoid nested data structures in the first place.

**Comment by ceremcem** [comment]
`assign-deep` is exactly what I'm talking about. So, wouldn't it be useful to have it in prelude-ls, or maybe in Livescript directly?

**Comment by vendethiel** [comment]
For prelude-ls, it'll have to be moved to the repo. For LiveScript itself -- please no, we have enough already :).

**Comment by igl** [comment]
Its unfortunate that immutability in javascript is wishy-washy. Even immutable.js is *not really* immutable. They do provide functions like mergeDeep, getIn, setIn, and updateIn to deal with nested structures.

Also how deep do you want to go?
What about `{ a: [{ b:[{ c: 'fu' }] }] }`?
What about circular dependencies?

**Comment by vendethiel** [comment]
I'll leave this open until someone opens one for prelude, I guess!

**Comment by ceremcem** [comment]
@igl I suppose merging only dictionaries would be enough, so if we want to merge  `{ a: [{ b:[{ c: 'fu' }] }] }` with `{a: [1, 2, 3]}`, result should be `{a: [1, 2, 3]}`, since value of `a` is not a dictionary. I didn't think of circular dependencies, but it wouldn't be an easy request: https://github.com/gkz/prelude-ls/issues/41

I opened a ticket in prelude repo [here](https://github.com/gkz/prelude-ls/issues/94) but as @vendethiel mentioned, yeah, we have enaugh :) 

Thank you guys, I'll use `assign-deep` module when I need.

**Comment by ceremcem** [comment]
FYI: As I stated [here](https://github.com/gkz/prelude-ls/issues/94#issuecomment-215945705), the following function does the same exactly with `jQuery.extend(true, ...)`: 
```
export function merge obj1, obj2           
  for p of obj2
    try
      if obj2[p].constructor ~= Object 
        obj1[p] = obj1[p] `merge` obj2[p]
      else 
        obj1[p] = obj2[p]
    catch 
      obj1[p] = obj2[p]
  obj1
```
