### ISSUE TITLE
Where can we find old documentation? 

### ISSUE THREAD

**Issue by ceremcem** [gkz/LiveScript#785]
I found a gist that might be useful in my case, but it is not compiled. When I searched for the erroneous keyword in the livescript.net, I realized the `where` keyword is depreciated. OK, now I want to update the code to the current version of livescript, but how can I find what where keyword does?

**Comment by gkz** [comment]
It's on the gh-pages branch on git, you can go back in the history

**Comment by ceremcem** [comment]
Thank you.
