### ISSUE TITLE
extending built in Map class requires 'new'

### ISSUE THREAD

**Issue by waynedpj** [gkz/LiveScript#789]
not sure why this is failing in Node.js 5.0.0:

```Livescript
class ReadOnlyMap extends Map
  /**
  constructor
  */
  (iterable) ->
    super ...

em = new ReadOnlyMap!
```
with error `[TypeError: Constructor Map requires 'new']`.  while what i consider the equivalent in JS works:
```Javascript
class ReadOnlyMap extends Map {
  constructor(iterable) {
    super(iterable);
  }
}

let em = new ReadOnlyMap!
```
i am obviously instantiating the subclass with new, but i assume the problem lies in the `super ...` call.  i am not quite following the generated JS code, but maybe this is a problem with using current LS with ES2015?

**Comment by vendethiel** [comment]
There's no "splatted new" in ES5, so we have to use .apply there, on the parent constructor. That's why it fails

**Comment by waynedpj** [comment]
thanks for the quick reply and explanation.  so if i am following correctly, currently the LS transpiler ends up generating the `function ReadOnlyMap(iterable){
    ReadOnlyMap.superclass.apply(this, arguments);
  }` call which causes the problem, even though i am running on Node 5.0.0 which is ES6/ES2015, because it still targets ES5?  and thus even changing `super ...` to `super iterable` in LS will still not work.  so the splatted new is not the only issue here?

however, is there a way to still subclass Map (and other built ins) entirely in LS?  i have tried various alternatives for that super call and i keep running into the same `[TypeError: Constructor Map requires 'new']` error.

thanks again.

**Comment by pepkin88** [comment]
I don't think there is a way for it, even Babel can't do it
http://stackoverflow.com/a/29436039/409149

The problem is having to rely on `call` or `apply` to pass the new instance of `ReadOnlyMap` to the `Map` constructor function, but apparently it's illegal by the ES2015 standard.

**Comment by heavyk** [comment]
it is possible if you use new Function - but it's way more trouble than it's worth

**Comment by zloirock** [comment]
```js
function SubMap(it){
  var that = new Map(it);
  that.__proto__ = SubMap.prototype.__proto__;
  return that;
}
SubMap.__proto__ = Map;
SubMap.prototype.__proto__ = Map.prototype;
```
bye bye IE10- %)

**Comment by vendethiel** [comment]
bye bye performance as well :/

**Comment by zloirock** [comment]
...and multilevel subclassing :)

**Comment by zloirock** [comment]
We have played with it in `babel` ~ `5.1`, I already don't remember why it was removed.

**Comment by pepkin88** [comment]
My bad, Babel leverages setting the prototype on the existing object (__proto__, setPrototypeOf) in the High Compliance mode.

**Comment by waynedpj** [comment]
thanks to everyone for all the insightful and nice ways of saying "wait until LS supports ES2015" ;)  seriously, it was educational, thanks again.
