### ISSUE TITLE
Making livescript lessons for russian, ukrainian people

### ISSUE THREAD

**Issue by askucher** [gkz/LiveScript#790]
Hi. 

I started to make livescript lessons for people because they really don't understand this language and there is no good explanation. 

```
https://www.youtube.com/playlist?list=PLS0swUfctwFFPgT4BSY7cnsHbWkRNUbiS
```

If you have any russian, ukrainian friends who has problems with livescript please recommend this link

I will add +1 video per day and answer questions

**Comment by gkz** [comment]
Very cool, thanks!

**Comment by Sky161** [comment]
Thank you so much!!!!!!!!

**Comment by raine** [comment]
Link: https://www.youtube.com/playlist?list=PLS0swUfctwFFPgT4BSY7cnsHbWkRNUbiS

**Comment by unclechu** [comment]
Good to know that someone do it.

You always used way to run your scripts by compiling it to `js` and then run it by `node`. Why you just weren't using `lsc` to run it directly? Like `lsc test`?

**Comment by askucher** [comment]
Wow! Thank you @unclechu
