### ISSUE TITLE
livescript gitter chanel

### ISSUE THREAD

**Issue by auvipy** [gkz/LiveScript#792]

**Comment by vendethiel** [comment]
?

**Comment by igl** [comment]
◔̯◔

**Comment by auvipy** [comment]
gitter.im channel for easy hang out :dancer:

**Comment by unclechu** [comment]
I think using this link is pretty easy:
https://webchat.freenode.net/?channels=#livescript

**Comment by vendethiel** [comment]
Right, it's been discussed before.
