### ISSUE TITLE
do syntax incorrectly recognises a method called `do`

### ISSUE THREAD

**Issue by pvdvreede** [gkz/LiveScript#793]
I am trying the rxjs stuff and they have a method called `do`: https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/do.md. When I use this method in live script, it transpiles it into `['do']` rather than leaving it as a method `do()`.

**Comment by vendethiel** [comment]
That's probably not needed, but that's not a bug either. It does the same.

**Comment by igl** [comment]
Javascript has a `do {} while ()` statement, therefor `do` is a language keyword, therefor it's not allowed as a object key in pre-es5 engines. :balloon: Legacy!
