### ISSUE TITLE
API call for (json:true) not working :(

### ISSUE THREAD

**Issue by JoyKrishnaMondal** [gkz/LiveScript#794]
hi ! 

I am trying to use the livescript API - but I think the option {json:true} is not working or I am using it wrong. 

![lscwatch](https://cloud.githubusercontent.com/assets/3383928/11904811/a007f34a-a5ba-11e5-84a5-45e224a40cc2.png)

**Comment by gkz** [comment]
Have you tried with the newest version of LiveScript? Install with `npm install livescript`

`lsc --version` should print out `LiveScript version 1.4.0`

**Comment by JoyKrishnaMondal** [comment]
Thanks !! It works. 

Did you just update livescript just now ?? I feel privileged :smiley:  Big Fan !
