### ISSUE TITLE
How would I go about creating a Domain Specific Extension for LiveScript

### ISSUE THREAD

**Issue by JoyKrishnaMondal** [gkz/LiveScript#797]
Sorry to raise this as an issue since I am not sure where else I can bring it up. 

I was interested in extending LiveScript: For example make it easy for people to do write numerical code. 

Like - instead of : 

```livescript

{pow} = Math

pow 2,2

```
I could write

```livescript

2**2 # = 4

```

I was thinking of using SweetJS but it only works for javascript :(

**Comment by gkz** [comment]
That already works

**Comment by vendethiel** [comment]
@gkz Yes, but I think the feature asked for here is "custom operators"?

**Comment by JoyKrishnaMondal** [comment]
Not so much as a feature - just how I could go about creating my own custom operators. 

I would like to do it for various Domain Specific Purposes. Adding Domain Specific shortcuts to LiveScript core would be terrible idea IMHO. 

LiveScript core is already really awesome !

**Comment by vendethiel** [comment]
I previously worked a bit on user-defined operators, but really, they'd be too ambiguous because of our already insane grammar... i.e `a@@@@b` is already defined. So really, we'd probably need to select a very limited subset, or to require dual spacing

**Comment by robotlolita** [comment]
@JoyKrishnaMondal probably the closest is abusing dynamic dispatch on objects:

```ls
point2d = do
  x: 0
  y: 0
  make: ({ x, y }) -> ^^this <<< { x, y }
  '+': (p) -> @make x: @x + p.x, y: @y + p.y


p1 = point2d.make x: 10, y: 20
p2 = point2d.make x: 5, y: 5
p3 = p1\+ p2
```

**Comment by JoyKrishnaMondal** [comment]
@robotlolita  I remember reading that you are using SweetJS mostly these days - what's your opinion on macros ? 

Dynamic Dispatch is cool but would you built libraries using it ? Let's say you want to write a library specific to a certain domain like differential equations. 

I do not think writing my own compiler on top of Livescript is a good idea :( I would like to write small modules that provide certain syntactic sugar to LiveScript. 

thanks a lot for this help !

**Comment by robotlolita** [comment]
@JoyKrishnaMondal macros are great, but Sweet.JS's ones also makes it hard to reason about your program (and there are some very annoying bugs in Sweet.JS too: https://github.com/siren-lang/siren/commit/88fb23e7b6d12283023439c404be2a3efd3c0f7f).

If you can control all of the objects in your library, then giving symbolic aliases for the methods is a pretty nice thing to do.

**Comment by JoyKrishnaMondal** [comment]
So essentially - no 

Is it best to just stick to functional abstraction then ? 

What happens when the stack level gets to high in functional programming ? Surely there is a limit to how many layers of functions you can load in your stack ?

**Comment by robotlolita** [comment]
@JoyKrishnaMondal there's a call stack limit right now, but ES6 mandates that all implementations implement proper tail calls, so once VMs implement that you get constant stack space for all tail calls, so:

```ls
f = f!
```

Would be strictly equivalent to:

```js
while(true);
```

**Comment by JoyKrishnaMondal** [comment]
@robotlolita  That is awesome !
