### ISSUE TITLE
standalone compiler

### ISSUE THREAD

**Issue by lzubiaur** [gkz/LiveScript#798]
Hi, CoffeeScript provides its [core compiler](http://coffeescript.org/extras/coffee-script.js) as a standalone script so it can be used in any javascript engine. Is it possible to run the LiveScript compiler outside node.js as well? I tried the compiled livescript.js (which I guess is only intended for browsers) but couldn't make it work (I use the [duktape](http://duktape.org/) engine).

**Comment by vendethiel** [comment]
[this](https://github.com/gkz/LiveScript/tree/master/browser) is exactly equivalent to the CoffeeScript version.

**Comment by lzubiaur** [comment]
Thanks for your answer.
With the CoffeeScript version I can simply do something like: 
```
var coffee = require('lib/coffee-script').CoffeeScript;
var script = readfile('js/test.coffee');
eval(coffee.compile(script))
``` 
But doesn't work with the LiveScript version. I must be missing something.

**Comment by vendethiel** [comment]
Here's such an example in one of my projects: https://github.com/vendethiel/wowboardhelpers/blob/master/Slakefile (see `ls-parse`, `src` is the source code).
Maybe you have an error, what "does not work"?

**Comment by lzubiaur** [comment]
Thank you for the info. If I try the following I get a `TypeError: not callable` error because the `compile` method is `undefined`.  
```
var LiveScript = require('livescript.js');
LiveScript.compile(src)
```
It seems that `require('livescript.js')` returns an "empty object" (no properties/methods).

Duktape has its own [module loading system](https://github.com/svaarala/duktape/blob/master/doc/modules.rst) based on CommonJS and with support for module.exports. Although it works for CoffeeScript, Duktape module loading may not work  with LiveScript somehow.

**Comment by vendethiel** [comment]
You're not supposed to load "livescript.js". But anyway, I think this is an issue with how duktape does its stuff. It definitely works in nodejs, so this is not a bug of ours.
