### ISSUE TITLE
Nice to have

### ISSUE THREAD

**Issue by askucher** [gkz/LiveScript#801]
### 1. recursion

```livescript

sum = (h:tail)-> h + sum tail

```

### 2. function with properties 

```livescript
func =  
   -> console.log it
   ..prop-of-func = 2

console.log func 1  #=> 1
console.log func.prop-of-func #=>2
```

### 3. inline context

```livescript
[1 to 10] |> p.map (.prop1 = .prop2 + 2)
```

### 4. syntax sugar for https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Promise

```livescript
func-promise ||> func-promise2
```

### 5. prop access

```livescript

user = 
  \prop-2 :2

#how to access how

user[\prop-2]  #uglyyyyy

#should be

user@prop-2

#or something like that

```

**Comment by raine** [comment]
```ls
user.\prop-2
user\prop-2 # or
```

**Comment by vendethiel** [comment]
1) `([a, ...b]) -> b` works already
2) make a class, really (and use explicit return in your ctor)
3) not sure what you mean?

**Comment by igl** [comment]
3: Did you mean `||>` as a alias for `.then`?
4: `user.'prop-2'` works as well.

I think LS has enough property access syntax

**Comment by askucher** [comment]
@vendethiel 
3) not sure what you mean?

```Livescript
arr = [1 to 10] |> p.map (-> prop: 2, prop2: it)
```


###case 1

```Livescript
arr |> p.map (-> it.prop)
```
equivalent is

```Livescript
arr |> p.map (.prop)
```

###case 2

```Livescript
arr |> p.map (-> it.prop + it.prop2)
```
what is equivalent ???

```Livescript
arr |> p.map (.prop2 + ????)
```

**Comment by askucher** [comment]
@igl

Yes. I think .then is already well know pattern.

**Comment by robotlolita** [comment]
How is:

```ls
a ||> b
```

Different from:

```ls
a.then b
```

What in particular does it benefit people with, in exchange for making LS's grammar even more complicated and ambiguous?

**Comment by vendethiel** [comment]
@askucher I think you got the answers you wanted :-). I'm gonna go ahead and close this one. Thanks everyone for chiming in!

**Comment by askucher** [comment]
Yes @vendethiel
