### ISSUE TITLE
Operators as Functions vs. `this`

### ISSUE THREAD

**Issue by summivox** [gkz/LiveScript#805]
```livescript
o = a: 1, b: 2, f: -> <[a b]> .map (@.)
o.f!
```
currently compiles to:
```javascript
var o;
o = {a: 1,b: 2, f: function(){
  return ['a', 'b'].map(function(it){
    return this[it];
  });
}};
o.f();
```

I believe a more useful semantics would be to implicitly bind `this`, as if I wrote:
```livescript
o = a: 1, b: 2, f: -> <[a b]> .map ~> @[it]
o.f!
```
which compiles to:
```javascript
var o;
o = {a: 1,b: 2, f: function(){
  var this$ = this;
  return ['a', 'b'].map(function(it){
    return this$[it];
  });
}};
o.f();
```

IIRC there are other situations where some expression has this implicit `this` binding semantics -- it felt so natural I forgot which ;)

**Comment by summivox** [comment]
Ah I recalled. A list comprehension has implicit `this` binding.
```livescript
a = [this.f .. for arr] .filter g
```
compiles to:
```javascript
var a;
a = (function(){
  var i$, x$, ref$, len$, results$ = [];
  for (i$ = 0, len$ = (ref$ = arr).length; i$ < len$; ++i$) {
    x$ = ref$[i$];
    results$.push(this.f(x$));
  }
  return results$;
}.call(this)).filter(g);
```

**Comment by vendethiel** [comment]
That's really not the same, because the closure we're generating is really an implementation detail.

**Comment by summivox** [comment]
> That's really not the same

True.

Back on operators as functions: I can imagine code relying on unbound `this`, so a breaking change would likely be impossible. Alternatively, is it possible to have a bound version?

**Comment by vendethiel** [comment]
Let's move this to #634 :-).
