### ISSUE TITLE
I was inspired by preludels and created nixar. Nixar got 609,781 total downloads in 2 months. 

### ISSUE THREAD

**Issue by askucher** [gkz/LiveScript#807]
Hi. Just want to introduce my projects nixar. 

I love pipings and preludels and decided to extend this experience to bash command line. 

This project was born out because of the livescript and preludels

The website 

[Nixar website](http://nixar.work)

**Comment by unclechu** [comment]
@askucher pretty cool thing! I'll certainly try to use it soon. But what we need to do with this issue? What do you propose? May be maintainers should add link to <b>nixar</b> to livescript.net page in new section with name like <i>'Projects inspired by LiveScript'</i>?

**Comment by gkz** [comment]
Cool project!
