### ISSUE TITLE
budget for livescript interfaces

### ISSUE THREAD

**Issue by askucher** [gkz/LiveScript#810]
Hi All

I am following your changes and not sure that you are going to create interfaces.

People around me has concern about it and do not use livescript

How many money needs to implement it?

Maybe the livescript community include me can help with it?

By the way, I had trouble with gravipay. It doesn't allow my cards

**Comment by gkz** [comment]
What do you mean by interfaces?

**Comment by askucher** [comment]
Like this http://blogs.msdn.com/b/typescript/archive/2013/01/24/interfaces-walkthrough.aspx
