### ISSUE TITLE
Escape identifier confused for keyword

### ISSUE THREAD

**Issue by atifaziz** [gkz/LiveScript#816]
The following:

```
pt = x: 123, y: 456
from = 'x'
to = 'y'
from: pt.[from], to: pt.[to]
```

should yield:

    {"from":123,"to":456}

but instead gives:

    {"from":123,"to":[]}

Looking at AST for the last object literal, it seems that `[to]` is being confused for slicing:

```
  Obj
    Prop
      Key from
      Chain
        Var pt
        Index .
          Parens
            Var from
    Prop
      Key to
      Slice to
        Chain
          Var pt
        Literal
```

Is there a way to escape `to` so it's not confused for the keyword `to`? I couldn't find anything in [the documentation](http://livescript.net/).

**Comment by vendethiel** [comment]
Not really. Don't use `to` as a variable name is the usual advice. `array[optFrom to optTo]` is already something in LS :).

**Comment by pepkin88** [comment]
You could write:
`from: pt.(from), to: pt.(to)`

**Comment by vendethiel** [comment]
Yeah, or `arr"#to"`

**Comment by atifaziz** [comment]
@pepkin88 Thanks, that seems like the best workaround & which will help if & when #818 gets addressed.
