### ISSUE TITLE
Web typo

### ISSUE THREAD

**Issue by ycheng** [gkz/LiveScript#819]
On the web page is said:

    var LiveScript = require("livescript");

It should be

    var LiveScript = require("LiveScript");

**Comment by igl** [comment]
nope. `npm install LiveScript` you will get an old version. npm packages must be lower case now.

**Comment by ycheng** [comment]
The test failed is confirmed again is against either livescript.js or livescript-min.js in the browser director of

gkz-LiveScript-1.4.0-0-g3f95366.tar.gz

Mind confirm again ? The test html code to reproduce the failure is

<html><head>
<script src="livescript.js"></script>
<script type="text/ls">
    console.log "boom #{window.location}"
</script>
<script>
    var LiveScript = require("livescript");
    LiveScript.go();
</script>
</head></body>
hello !
</body></html>

**Comment by igl** [comment]
This actually is a problem :) #826 re-reported it.
Sorry for being ignorant @ycheng

**Comment by vendethiel** [comment]
Indeed, I hadn't realized it was about the "web" package
