### ISSUE TITLE
One item Array syntax is broken

### ISSUE THREAD

**Issue by smokku** [gkz/LiveScript#825]
This
```
foo =
  * \One
  * \Two
```
looks like an Array of two items, and indeed is.

This
```
bar =
  * \Uno
```
looks like an Array of one item, smells like an Array of one item, but... it isn't! It is a String. 8-O

This syntax is inconsistent, counter-intuitive and misleading. This is an accident waiting to happen.
And in fact, I am here because it just happened to me.

I know that you can force it to be an Array using a splat
```
bar =
  * \Uno
  ...
```
but this is just an ugly workaround for a bug in design IMO.

_Please_ fix this. _Do not let more accidents happen._ :-)

**Comment by vendethiel** [comment]
We already have an issue about that, and another one to track it

**Comment by smokku** [comment]
Could you please point me to that issue?
I tried searching for one before reporting this.
