### ISSUE TITLE
something unexpected happened in the part of Access/Call Function Shorthand

### ISSUE THREAD

**Issue by Levstyle** [gkz/LiveScript#829]
map (.length), <[ hello there you ]>
#=> [5,5,3]

map(function(it){
  return it.length;
}, ['hello', 'there', 'you']);

Array.prototype.map(function(it){
  return it.length;
}, ['hello', 'there', 'you']);

when i run the js code in chrome 48, its results are not [5,5,3], it's []

the second para of map function is used to change context! so it don't change it!

Am I wrong?

**Comment by vendethiel** [comment]
It'd need to be `Array.prototype.map.call`... But I'm not sure how this is a LS bug?

**Comment by Levstyle** [comment]
@vendethiel I'm sorry! the map function is defined in prelude.ls It's not the one defined in Array::

**Comment by Levstyle** [comment]
@vendethiel It's my fault

**Comment by vendethiel** [comment]
Okay -- can I close this issue, then? :)

**Comment by Levstyle** [comment]
@vendethiel  of course! Thanks
