### ISSUE TITLE
Any interest in a "soaking pipe" operator?

### ISSUE THREAD

**Issue by summivox** [gkz/LiveScript#838]
```livescript
a ?|> b ?|> c
```
compiles to
```javascript
typeof a != 'undefined' && a != null ? (ref$ = b(a)) != null ? c(ref$) : void 8 : void 8
```

**Comment by vendethiel** [comment]
I feel this is where we should draw the line... Just write your own function and compose it in, imho.

**Comment by summivox** [comment]
Hmm alright :neutral_face:

**Comment by summivox** [comment]
...I realized that this is not trivial to implement in functions because soaking operators take shortcuts. It's strange we can do `a ?.m1 b ?.m2 c ?.m3 d` but not this.

Leaving this open for input.

**Comment by rhendric** [comment]
It would be nice in my opinion to have the soaking prefix be available universally for all operators, for the shortcut functionality reason @summivox raises. Even/especially things like ``a ?`infixFn` b``. The lexer already separates `?` and `|>` in `?|>` so it should just be grammar and AST work to make this happen.

**Comment by unclechu** [comment]
Agree with @rhendric it would be nice and consistent, like we can use any operator with `=` (`|>=`, `?=`, `.=`, etc.).

**Comment by alephyud** [comment]
Would support this. There are many so many use cases for `?|>` and it cannot be easily replaced with a function.

**Comment by igl** [comment]
I would remove `?` in the first place. I've seen many bugs and unreasonably complicated code produced by it.

Saving characters isn't a issue that LS is in great need of.
Promoting silently stopping/failing execution and complicated code does not look like a big win for me.

**Comment by summivox** [comment]
@igl : I beg to differ. If you believe that shortcutting operator has no use ("silently stopping/failing execution and complicated code") then by same reasoning we should not have shortcutting logical `and` operator. Soaking `?` is fundamentally no different from it, only that it discriminates on null vs non-null, instead of falsey vs truthy.

**Comment by summivox** [comment]
@rhendric : Would you mind opening a new issue and further explain your idea? I'll close mine and leave a xref. I feel your approach (also regarding spreading #831) favorable as it promotes rules instead of exceptions, which is what I believe LiveScript needs the most.

**Comment by vendethiel** [comment]
Well said ;)

**Comment by pepkin88** [comment]
> Even/especially things like ``a ?`infixFn` b``.
Slightly off topic, but I would also add ``a `infixFn`= b``. Predictable and consistent.

**Comment by rhendric** [comment]
@pepkin88 yesss... yeeeeeessssss... (#555)
