### ISSUE TITLE
Dead code in `lexer.ls`?

### ISSUE THREAD

**Issue by summivox** [gkz/LiveScript#840]
https://github.com/gkz/LiveScript/blob/master/src/lexer.ls#L627
https://github.com/gkz/LiveScript/blob/master/src/lexer.ls#L645

**Comment by vendethiel** [comment]
The second seems to come from coco's cascade, mh. good catch...

**Comment by vendethiel** [comment]
indeed: 1aa4ea5ceded09d5db4c87d751e36747a1edfd77
