### ISSUE TITLE
Implicit array in arglist vs. `*` vs. arg splatting

### ISSUE THREAD

**Issue by summivox** [gkz/LiveScript#843]
```livescript
f do
  * 1, 2
  * ...a
  * 3
```
It currently compiles to:
```javascript
f([1, 2], slice$.call(a), 3);
```
I was expecting:
```javascript
f.apply(null, [[1, 2]].concat(slice$.call(a), [3]));
```

---

Even more minimal(istic) example:
```livescript
f do
  * ...a
```
compiles differently from
```livescript
f do
  ...a
```

---

Sure I'm stretching a little bit, but I somehow feel that the `*` before `...a` should indicate new entry in arglist, not array. Thoughts?

**Comment by heavyk** [comment]
I like the way it compiles right now is really handy. imagine you have a lot of arguments to pass to a function. that's a super clean way of calling the function.

wow, I wish I had of known about that. I'm gonna change some code that uses backslash for multiple args now  :)

**Comment by pepkin88** [comment]
Yes, splat should spread an array to arglist. After all, if you want to make an array of it, you would wrap it in brackets, like `* [...a]`.

**Comment by summivox** [comment]
@heavyk : what it compiles to now is probably **not** what you expect?

**Comment by rhendric** [comment]
:-1: The current behavior is consistent with the documented meaning of `*`:

> When implicitly listing, you can use an asterisk `*` to disambiguate implicit structures such as implicit objects and implicit lists. **The asterisk does not denote an item of the list**, but merely sets aside an implicit structure so that it is not muddled with the other ones being listed.

IMO the intent is clear: `*` means new structure, so that the brackets that @pepkin88 describes aren't necessary. Within that assumption, the splat is behaving as I would expect—it's splatting within the new implicit list created by the asterisk, as opposed to within the arglist as it does when you omit the asterisks.

**Comment by summivox** [comment]
@rhendric : I believe I understand the (general/intended) semantics of `*` as "implicit list breaker". The crux: the `*` I wrote is in an arglist, not in an array.

Compare to:
```livescript
a =
  * 1, 2
  * ...b, ...c
```
This compiles to what I expect.

**Comment by rhendric** [comment]
I don't understand the point you're making; why do you expect (if you do?) `*` to behave differently in an arglist from its behavior in an array? It seems that you're okay with

```ls
a =
  * 1, 2
  * ...b, ...c
```
meaning something different than
```ls
a =
  * 1, 2
  ...b, ...c
```
(as it does), but you want
```ls
f do
  * 1, 2
  * ...a
```
to mean what
```ls
f do
  * 1, 2
  ...a
```
currently compiles to? Or have I misunderstood?

**Comment by pepkin88** [comment]
OK, after thinking about it for a while
```
f do
  * 1, 2
  ...a
  * 3
```
Would be a better depiction of the intent.

**Comment by summivox** [comment]
@rhendric @pepkin88  right, didn't realize that removing `*` works as intended. My bad.
