### ISSUE TITLE
Improve unary cast to boolean (!!) behavior

### ISSUE THREAD

**Issue by focused** [gkz/LiveScript#850]
Unary !! should correctly make any variable into `true/false`

This is not real cast to boolean:
```livescript
y = "false"
!! = y # => true
```
It also happens with function parameters: `f = (!!x) -> x`

Now correct behavior could be implemented this way (except `null` or `undefined`):
```livescript
y = "false"
y = not (y is "false") # => false
```

**Comment by vendethiel** [comment]
This is definitely real cast to boolean. "false" is a truthy value.
