### ISSUE TITLE
Inconsistent array casting

### ISSUE THREAD

**Issue by Announcement** [gkz/LiveScript#854]
# Short arrays aren't enough to loop

`[to 10]` does what expected and so does `[.. for [0 to 10]]`

## But in contrast...

`[.. for [to 10]]`  throws 
> Parse error on line 1: Unexpected 'FROM'

**Comment by summivox** [comment]
Just FYI: `[.. for to 10]` now works thanks to #859

**Comment by rhendric** [comment]
`[.. for to 10]` works, but `[.. for [to 10]]` still doesn't; shouldn't this remain open?

**Comment by summivox** [comment]
Lexer is to blame.

**Comment by summivox** [comment]
I am going to patch this temporarily with a grammar fix.
