### ISSUE TITLE
Proposal: export default

### ISSUE THREAD

**Issue by alexlur** [gkz/LiveScript#855]
Let LiveScript support `export default` syntax in addition to the current `export` keyword. For example,

```livescript
export default class ChatLog
   ->
     # Init codes
```

will compile into

```javascript
var out$ = typeof module !== 'undefined' && module.exports;
if (out$) {
   Object.defineProperty(out$, '__esModule', { value: true });
} else {
   // Possibly throw error here because `export default` doesn't make sense here
}
out$['default'] = ChatLog
module.exports = out$['default']
```

**Comment by vendethiel** [comment]
what is this `__esModule` thing?

The reason we don't have such a thing is because `module.exports =` is no code duplication (compared to `exports.a = a` etc)

**Comment by alexlur** [comment]
`__esModule` is used for compatibility with Babel, TypeScript, and Traceur compiler, who use this value as a CommonJS flag.

**Comment by vendethiel** [comment]
I've always used `module.exports` and it worked fine. I'm going to clause this, as I've never needed anything like that, and I use modules all the time.

**Comment by heavyk** [comment]
this is for compliance with babel transpiler - but I think that it would be betterr if LS is transpiled to vanilla es6, maintaining the `export default` syntax. if further compat is needed, then run that code through babel and let babel add the `__esModule` stuff.

**Comment by vendethiel** [comment]
that's another issue :)
