### ISSUE TITLE
Better handling of splat func arguments

### ISSUE THREAD

**Issue by summivox** [gkz/LiveScript#857]
[According to Petka](https://github.com/petkaantonov/bluebird/wiki/Optimization-killers#32-leaking-arguments), calling `slice$` on `arguments` kills v8 optimization. He suggested to do a naive indexed for loop on `arguments` instead.

Currently:
```livescript
f = (a, ...b, c) ->
```
compiles to:
```javascript
f = function(a){
  var i$, b, c;
  b = 1 < (i$ = arguments.length - 1) ? slice$.call(arguments, 1, i$) : (i$ = 1, []), c = arguments[i$];
};
```

**Comment by summivox** [comment]
I did a patch (summivox/LiveScript@e6591cf) but it currently relies on #859 being merged. It can be done without #859 but I'm too lazy :wink:

This patch itself does not change any semantics -- the only change is inlining slicing of `arguments`. Therefore I did not add/change any tests.

**Comment by isiahmeadows** [comment]
Ping @gkz (Babel and TypeScript do this by default, and [CoffeeScript has been annoying people with the slow progress](https://github.com/jashkenas/coffeescript/issues/3274).

**Comment by summivox** [comment]
@isiahmeadows : currently @vendethiel  is in charge (and yes he did comment on that issue too).

BTW: #859 has been merged, so I can actually make a pull request now.

**Comment by isiahmeadows** [comment]
@summivox Okay. I didn't know this.

(I don't keep up with this as much as I used to. LS 2.0 does seem pretty interesting, though.)
