### ISSUE TITLE
Inconsistent empty splat assignment

### ISSUE THREAD

**Issue by summivox** [gkz/LiveScript#858]
```livescript
[..., a, b] = [1]
[...x, y, z] = [1]
a is void and b is 1 and
x.length is 0 and y is 1 and z is void
```

Since line 2 is widely accepted as the correct behavior (i.e. splat cannot "unconsume") I don't see why line 1 shouldn't.

**Comment by vendethiel** [comment]
Seems correct. Also a breaking change.

**Comment by summivox** [comment]
> Also a breaking change

Maybe label this for 2.0 and forget about it for now :wink:

**Comment by vendethiel** [comment]
Yes, probably.
