### ISSUE TITLE
Feature Request: more flag options

### ISSUE THREAD

**Issue by Announcement** [gkz/LiveScript#864]
# command.ls

Was working on some CLI scripts today.
Was going to implement myself, but quite frankly - your code is horrendous. 
I would like a `-k, --colored` for colored output and `-x` that could stand for `--no-header` and possibly

But honestly, the main point of this is to please fix your absolutely *terrible* code in the near future.

**Comment by vendethiel** [comment]
Hi,

Thanks for your constructive feedback! As always in open source projects: "well volunteered".

**Comment by rightfold** [comment]
> Announcement changed the title from **Featu** to **Feature Request: more flag options**

lol

**Comment by heavyk** [comment]
> But honestly, the main point of this is to please fix your absolutely terrible code in the near future.

??? - coloured output wouldn't be such a big thing probably, if you didn't think the code was horrendous :) it really isn't horrendous at all!... maybe you meant unconventional? either way, lol

**Comment by Announcement** [comment]
bumping because you can't currently combine -e, -c, and -p, to compile a one liner without saving it first.
