### ISSUE TITLE
Is there a way to use LiveScript compiler in Python?

### ISSUE THREAD

**Issue by ceremcem** [gkz/LiveScript#867]
I love LiveScript (https://github.com/aktos-io/aktos-scada), but I use Python mostly (https://github.com/aktos-io/aktos-dcs***). 

Is there a way to benefit from LiveScript compiler to compile a Livescript-like code into Python code?

**Comment by vendethiel** [comment]
No, there's no such thing that I'm aware of. I know of some other packages which add somewhat-related features (like macro), but nothing LS-style.

**Comment by heavyk** [comment]
if you just want to output python-like code, you could go through ast.ls and change the compile functions to output python code. I don't know python so I cannot comment on what that would look like.

I have done similar things to output other languages.

**Comment by ceremcem** [comment]
Well, that's a starting point!
