### ISSUE TITLE
Why is "static" "method" is used in Livescript? 

### ISSUE THREAD

**Issue by ceremcem** [gkz/LiveScript#871]
Hi, 

Today I started switching from Hapi.js to Express.js and I followed [this](https://gist.github.com/dbainbridge/2424055#file-app-js-L18) gist. There is a `express.static()` function used in the example. So I typed the following Livescript code: 

```
express.static "my-dir"
```

which compiled to 

```
express["static"]("my-dir")
```

where I expected the following: 

```
express.static("my-dir")
```

How can I make that code compiled into the expected one?

**Comment by vendethiel** [comment]
It's expected (ES3 strict parsers) and does **exactly** what you want.
