### ISSUE TITLE
livescript ast doesn't store full information about code

### ISSUE THREAD

**Issue by askucher** [gkz/LiveScript#872]
Hi. I found that AST doesn't store the information about PIPING so it is not possible to convert back from ast to livescript code without loosing of quality of the code

```livescript
"" |> convert 2
```
will be

```livescript
convert 2,""
```

but it is not possible to understand is convert function carried or not.

**Comment by vendethiel** [comment]
Right, that's why it's an *abstract* syntax tree, instead of a concrete one :).

**Comment by vendethiel** [comment]
(In general, this is not feasible for us to expose, due to how much rewrites the lexer does)
