### ISSUE TITLE
anonymous back-calls ? 

### ISSUE THREAD

**Issue by JoyKrishnaMondal** [gkz/LiveScript#876]
hey, is it possible to do something like this:

![backcalls](https://cloud.githubusercontent.com/assets/3383928/14381647/bec6f444-fd7f-11e5-9d2d-4f0b7c414f60.jpg)

**Comment by JoyKrishnaMondal** [comment]
forget it, its just simpler to use inline function. 

Anyway, its still a curious case of what happens to backcalls when there are no functions attached to it on the right ?

**Comment by vendethiel** [comment]
it just won't parse

**Comment by JoyKrishnaMondal** [comment]
yeah, it makes little sense to do it like that.

**Comment by homam** [comment]
I always use `x <- id`

Some examples:

[http://rf.pipend.com/branches/prMlql1/](http://rf.pipend.com/branches/prMlql1/)

Or [Reader monad](http://rf.pipend.com/branches/pHNMRA4) a good example of abusing this!
```
class Reader
    (@f) ->
    
    run: (e) -> 
        @f e
    
    bind: (f) -> 
        new Reader (e) ~> (f @run e).run e
    
    @pure = (a) -> new Reader (-> a)

ask = new Reader id


# comp1 :: Reader {my-num :: Int} Int
comp1 = do ->
    {my-num} <- ask.bind
    r <- comp2.bind # 50
    comp3 my-num + r * 3 # comp3 (5 + 50 * 3)

# comp2 :: Reader Int Int
comp2 = do ->
    {my-num} <- ask.bind # 5
    Reader.pure 10 * my-num # 50
    
# comp3 :: Int -> Reader Int Int
comp3 = (v) ->
    {my-num} <- ask.bind # 5
    Reader.pure my-num * v # 5 * 155
    
comp1.run {my-num: 5}
```

**Comment by JoyKrishnaMondal** [comment]
@homam - I never understood .bind and .return :(

Is there a simple example out there using livescript and showing its usecase ? 

btw - nice to see some U.A.E developers, Jebel Ali is my hood :)
