### ISSUE TITLE
Allow mutable variables when compiling with --const

### ISSUE THREAD

**Issue by dluciv** [gkz/LiveScript#877]
`--const` switch is definitely very good thing, but then there is no way to enforce some names to be mutable. E.g. I think having `--const` making everything const by default, but allowing to declare something as explicitly mutable will make `--const` feature much more usable.

**Comment by vendethiel** [comment]
Prefix `__` allows for mutability with that variable.

**Comment by dluciv** [comment]
Then it is good thing to be documented, isn't it?
