### ISSUE TITLE
Can we define preprocessed keywords?

### ISSUE THREAD

**Issue by ceremcem** [gkz/LiveScript#881]
Hi, 

We had been heavily using Python and now we are switching to Livescript. Sometimes we need some specific libraries which can be found or written before by us in Python but not exist in Javascript, so we translate them by ourselves from Python to Livescript.

Most of the times, code is found in a sequential form. That's why it's hard to translate them quickly. I asked [such a question](https://github.com/gkz/LiveScript/issues/875) before and the closest code for the same job is as follows: 

Python: 
```
do_something()
while True:
    x = do_something_else()
    if x == 0: 
        break
    sleep(0.1)   # wait 100ms 
do_another_thing()
```
As we currently don't have a `yield`-like keyword available in Espruino (a Javascript interpreter runs on embedded devices), this is the closest possible approach I can think of in Livescript: 

```
# use this function from library
sleep = (ms, func) -> set-timeout func, ms 

do-something!
<- :loop_ (next_) ->
  x = do-something-else!
  if x is 0
    next_!;return  # works like `break` 
  <- sleep 100ms
  loop_ next_
do-another-thing!
```

Do we have an option to define a "decorator function" that directly translates: 

```
do-something!
sync_loop
  x = do-something-else!
  if x is 0
    sync_break 
  <- sleep 1000ms
  sync_end
do-another-thing!
```

Which will directly find and replace 
*  `sync_loop` with `<- :loop_ (next_) ->`
*  `sync_break` with `next_!;return`
*  `sync_end` with `loop_ next_`

**Comment by vendethiel** [comment]
No, LS ("sadly") doesn't have macros.
