### ISSUE TITLE
running with node require does not parse json.ls

### ISSUE THREAD

**Issue by nekdolan** [gkz/LiveScript#882]
Hi

When we try something like `node --require livescript/lib/index.js myscript.ls` the json.ls files will not be parsed correctly. I prefer this way of loading livescript since I am using webstorm on Windows and `lsc` is just not the same.
One way to solve this issue would be to change node.ls and add something like (for json.ls files only)
```livescript
json = LiveScript.compile (fs.read-file-sync filename, 'utf8'), {filename, +json}
module._compile "module.exports = #{json}", filename
```
For now I will just use regular json files

**Comment by vendethiel** [comment]
Weren't there issues with multi-tiered extensions in require calls in node?

**Comment by nekdolan** [comment]
@vendethiel Not sure but this hack did work for me. The compiler will try to parse both .ls and .json.ls files. We just need to parse json.ls files differently. Tested it with node 5.1 on Xubuntu.

**Comment by nekdolan** [comment]
You can check the implementation here: https://github.com/nekdolan/LiveScript/blob/master/src/node.ls
With this if you run lsc you can require json files that are really json.ls files

**Comment by pepkin88** [comment]
I agree that this should be added, but for now you can use my [livescript-cache](https://www.npmjs.com/package/livescript-cache) module, which also provides hooks for the [source-map-support](https://www.npmjs.com/package/source-map-support) module.

**Comment by nekdolan** [comment]
https://github.com/gkz/LiveScript/commit/2f7876bc7ef622740497cf4ed595c38fc6e68273
