### ISSUE TITLE
backcalls in map and loops

### ISSUE THREAD

**Issue by JoyKrishnaMondal** [gkz/LiveScript#887]
Is it possible to optimize backcalls to lift anon functions. 

for example - this is fine.  

```livescript
x <- _.map [1,2,3,4,5] 
console.log x
 ```

but for something like this :

```livescript
x <- _.map [[1,2,3,4,5],[1,2,3,4,5]] 
y <- _.map x
console.log y
 ```

the performance penalty for this is quite high. 

for now I just use inner for loops but would really love to use backcalls if the compiler could optimize for and lift the inner function - essentially all backcalled functions get lifted to the top scope.

It seems quite a complicate thing to ask - I would love some direction as to how I could do the optimization myself. 

cheers.

**Comment by vendethiel** [comment]
you mean, generate a `for (;;)` instead of `.map`? This is not possible for us. We don't know whether or not `Array.map` was overriden or not, we can't very well replicate the closure semantics (new scope), etc.

**Comment by JoyKrishnaMondal** [comment]
not for map. 

for example I have a script that does something like this using a maybe monad. 

```livescript

re1 = /foobar1/

re2 = /foobar2/

text <- map list-of-text

regrex-check1 = text.match re1

values <- maybe regrex-check1

regrex-check2 =  values[1].match re2

values <- maybe regrex-check2 

# . . . .

# . . . .

# . . . .

# . . . . 



```

**Comment by vendethiel** [comment]
Again, we can't inline stuff. This is not lsc's role, either...

**Comment by WreckedAvent** [comment]
If you want "do"-style syntax, your best bet is going to be to use generators.
