### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by alexlur** [gkz/LiveScript#889]
It's more than a year since the last release of LiveScript. Any update on the project status?

**Comment by gkz** [comment]
I'm starting to work on merging in many pull requests. After that, there will be a release. Unfortunately some of the pull requests require manual merges.

**Comment by gkz** [comment]
I published 1.5.0, please check it out and see if there are any bugs. If so, I can publish 1.5.1 soon after

**Comment by pmros** [comment]
LiveScript 1.5! :tada: 
I'm looking forward to read updated changelog!

**Comment by alexlur** [comment]
@gkz Thanks a lot for the update! I am now waiting for the changelog.

**Comment by Announcement** [comment]
same, but is there any possiblity of a future 'acorn' support or whatever, like how we can do `pm2 espress.coffee` i want `pm2 bel.ls` or whatever, there's several other modules that have a `--interpreter` functionality...

**Comment by rhendric** [comment]
I'm going to close this to clean up issues; the missing changelog is tracked in #907, and if @Announcement still cares about acorn support, please open a new issue for that.
