### ISSUE TITLE
Unary spread delete stopped working in 1.5.0

### ISSUE THREAD

**Issue by smokku** [gkz/LiveScript#891]
What is documented in 1.4.0

```
Unary spread - when the operand is a list literal, apply the unary op to each item:
...
delete list[1, 2, 3]
```

compiles and works fine in 1.4.0:

```
$ echo 'delete list[1, 2, 3]' | node_modules/livescript/bin/lsc -scbp
// Generated by LiveScript 1.4.0
delete list[1], delete list[2], delete list[3];
```

but fails in 1.5.0:

```
$ echo 'delete list[1, 2, 3]' | node_modules/livescript-loader/node_modules/livescript/bin/lsc -scbp
[SyntaxError: invalid delete on line 1]
```

**Comment by vendethiel** [comment]
Syntax changed. @gkz released a bit fast, I think.

**Comment by gkz** [comment]
We don't have tests for this? Odd. I wonder what changed between versions

**Comment by rhendric** [comment]
#863 is what changed. See also #866.

**Comment by vendethiel** [comment]
@gkz uhm, as my message said, the syntax changed - forgot to create an issue WRT docs.

**Comment by gkz** [comment]
Ah ok cool, didn't see that change

**Comment by summivox** [comment]
Many changes post-1.4.0 were intended for 2.0.0 (i.e. breaking).
IMHO 1.5.0 should be deprecated on NPM... People not pinning version are bound to get in trouble.

**Comment by vendethiel** [comment]
btw that's #866.
