### ISSUE TITLE
Optional argument parsing is incorrect.

### ISSUE THREAD

**Issue by Announcement** [gkz/LiveScript#892]
# optional argument parsing

Using optional arguments that aren't the last argument fails... ~~weirdly at that.~~

Take this function for example...
## example function

``` livescript
example = (optional = @config, required) ->
  {optional, required}
```
## testcase

``` livescript
[
  example.call {config: 'works'}, \provided, \argument
  example.call {config: 'broken'}, \missing
]
```
## various outputs

> What actually happens.
> 
> ``` json
> [{"optional":"provided","required":"arg"},{"optional":"missing"}]
> ```
> 
> What is expected to happen
> 
> ``` json
> [{"optional":"provided","required":"arg"},{"optional":"broken", "required":"missing"}]
> ```
## why we need this fixed (and alternatives/workaround)

Calling methods with functions before parameters is _very_ awkward in bracketless languages, unless you name them first of course.
Things such as `set-interval(function, timer)` are just... no.
### [prelude-ls](//www.preludels.com/)

This library which is mentioned by @gkz on the [livescript](//livescript.net) page is very helpful in times like this, check out something called `flip` which re-orders the first and second argument, I suppose if need be you can curry it and use it repeatedly on built in javascript functions... (please don't)
## other information

Other compiled langauges similarly compiled on a naïve basis, such as [coffeescript](http://coffeescript.org/).

**Comment by rhendric** [comment]
It's not broken exactly; it's a perfectly consistent behavior that just doesn't happen to be what you expect. The resolutions of #312 and #873 make me think that this is unlikely to change, but you never know! It might help if you think of them as ‘defaults’ rather than as ‘optional’.

For `set-interval` and similar, you might also like this pattern which I often use:
```ls
set-interval _, 500 <| !->
  console.log 'hey there'
```

or this one which I only occasionally use:
```ls
<-! set-interval _, 500
console.log 'wooo backcalls'
```

both of which compile to the simplest possible JavaScript, unlike using `flip`.

**Comment by vendethiel** [comment]
Few languages behave like you describe (Ruby does). I don't see a compelling reason to change this, as the main reason non-tail argument are allowed to have default values is for explicit null calling

**Comment by pepkin88** [comment]
Default value for param:
`fn = (a = 5, b) ->`

Optional param (which was bugged in 1.4, but works fine in 1.5):
`fn = (...[a = 5], b) ->`

**Comment by Industrial** [comment]
@pepkin88 that gives me a `Error: SyntaxError: invalid assign`

**Comment by pepkin88** [comment]
@Industrial Like I said, it works in version 1.5, you can check it on [livescript.net](livescript.net). In earlier versions it wasn't working.
