### ISSUE TITLE
new keyword with 2 arguments errors.

### ISSUE THREAD

**Issue by JoyKrishnaMondal** [gkz/LiveScript#893]
```livescript
	blob = new Blob ([(fn.toString!)],(type:'application/javascript'))
```

I am getting an error for comma, can't you pass two arguments for new constructor ?

```
> lsc -cw work.ls
Failed at: work.ls
Error: Parse error on line 21: Unexpected ','
```

**Comment by naturalethic** [comment]
You need to omit the space between the Constructor and the first parent of the argument list, otherwise it looks like you're trying to create a tuple, which isn't supported (a, b)

**Comment by JoyKrishnaMondal** [comment]
Ahh that worked -  thanks @naturalethic  :) 

wait, tuples are not valid java-script or live-script types ? when I do 

```livescript
(1,2) # throws an error
```

**Comment by vendethiel** [comment]
In Js, `,` is the sequencing operator (same as C), so `(1, 2)` evaluates 1, discards it, and returns 2.
