### ISSUE TITLE
`a.map (* '') * ''` makes compiler crash

### ISSUE THREAD

**Issue by summivox** [gkz/LiveScript#905]
Although I quickly realized that I wanted to write:

``` livescript
(a.map (* '')) * ''
```

Compiler should emit error not crash.

Parser did not crash so it has to be `compile` of (overloaded behavior of) binary operator `*`.

IIRC we are going to get rid of this overloaded behavior sooner or later so feel free to ignore this.

**Comment by foxbunny** [comment]
Not sure if it's related, but I also noticed frequent compiler crashes on invalid syntax when using `-w` and `-c` together.

For example, trying to compile this code:

```
`test`
```

results in this traceback:

```
C:\Users\hajim\AppData\Roaming\nvm\v4.6.0\node_modules\livescript\lib\command.js:260
            warn(e + '\x07');
                   ^

TypeError: Function.prototype.toString is not generic
    at Function.toString (native)
    at compileScript (C:\Users\hajim\AppData\Roaming\nvm\v4.6.0\node_modules\livescript\lib\command.js:260:20)
    at C:\Users\hajim\AppData\Roaming\nvm\v4.6.0\node_modules\livescript\lib\command.js:152:11
    at C:\Users\hajim\AppData\Roaming\nvm\v4.6.0\node_modules\livescript\lib\command.js:142:7
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```

Tested with LiveScript 1.5.0 on both Node 4.6.0 and 6.8.0 under Windows.

**Comment by rhendric** [comment]
That looks like a separate issue to me, @foxbunny.

**Comment by vendethiel** [comment]
This doesn't crash the compiler (anymore?)

`Parse error on line 1: Unexpected \')CALL\'`

**Comment by rhendric** [comment]
Confirmed, not a crash anymore.
