### ISSUE TITLE
Show v1.5.0 and its changelog on livescript.net

### ISSUE THREAD

**Issue by bianjp** [gkz/LiveScript#907]
Version 1.5.0 was released on May 16, but [livescript.net](http://livescript.net) still shows 1.4.0 as latest version. And there is no changelog for 1.5.0 anywhere.

In my opinion, official site is the most important way for people to check new versions, so please keep it up to date.

**Comment by summivox** [comment]
IMHO we pushed out 1.5.0 too early; also due to a breaking change it should actually be 2.0.0 if we respect semver...

**Comment by wolfflow** [comment]
But question was about what the real changes were (especially breaking ones), it takes very long time to read all the diffs.

**Comment by gkz** [comment]
I'll get to it - updating the site, adding a changelog, etc. all take a lot of time.

As you see I've updated the text and download links and sidebar compiler to use 1.5

**Comment by unclechu** [comment]
How about changelog?

**Comment by dluciv** [comment]
Nevertheless it will be helpful to list changes (both compatible and non-compatible) at least here...

**Comment by daveeel** [comment]
While the official site is not up to date with 1.5, how could I look up the changes (especially breaking) in the source code?

**Comment by dluciv** [comment]
@daveeel I double this

**Comment by rhendric** [comment]
You're welcome to peruse [GitHub's diff](https://github.com/gkz/LiveScript/compare/1.4.0...1.5.0); by looking at the files changed under `test` you should hopefully get a reasonably complete sense of what functionality was added/changed. (I think I was adequately conscientious about tests in my commits but I can't vouch for anyone else's.)

**Comment by laurentpayot** [comment]
Thanks @rhendric I didn't know GitHub's diff, what a convenient feature.
Thanks to it I could finally see how to enable history :)

**Comment by nazar-pc** [comment]
1.5.0 was released almost 4 months now, can anyone who knows exact changes update changelog on website? I've tried to read tests, but since I'm not using 100% of the syntax it is quite difficult to read for me and even more difficult to understand what the actual changes are. Changelog would be very helpful for migration.

**Comment by JTallis** [comment]
1.5.0 was released 6 months ago. I too was looking for the changelog but nada. I don't even see a single blog post.

**Comment by nazar-pc** [comment]
I'm still using 1.4 because of this, any ETA?

**Comment by rhendric** [comment]
So needy! :grin: Here, since @gkz doesn't seem to be working on this, I started [this wiki page](/gkz/LiveScript/wiki/Unofficial-changelog) so we can track changes ourselves. Go nuts.
