### ISSUE TITLE
How to force LiveScript in order not to separate utility functions?

### ISSUE THREAD

**Issue by ceremcem** [gkz/LiveScript#913]
Hi, 

I need to create a `_design` document (for CouchDB) and I want to write it in LiveScript, like so: 

``` ls
views: 
    get-admins: (doc) ->
        if '_admin' in doc._id
            emit doc._id, 1

```

If the compiler would output something like

```
({
  views: {
    getAdmins: function(doc){
function in$(x, xs){
  var i = -1, l = xs.length >>> 0;
  while (++i < l) if (x === xs[i]) return true;
  return false;
}
      if (in$('_admin', doc._id)) {
        return emit(doc._id, 1);
      }
    }
  }
});
```

Then it will be all good. But instead `lsc` generates utility functions (`in$()` in this case) separately (which is for performance reasons, obviously). How can I force LiveScript put the utility functions nearby?

**Comment by summivox** [comment]
What's your compiler version?
on <http://livescript.net/> output is as expected: the shim appears at the tail.

```javascript
({
  views: {
    getAdmins: function(doc){
      if (in$('_admin', doc._id)) {
        return emit(doc._id, 1);
      }
    }
  }
});
function in$(x, xs){
  var i = -1, l = xs.length >>> 0;
  while (++i < l) if (x === xs[i]) return true;
  return false;
}
```

**Comment by ceremcem** [comment]
Hi @summivox; 

What I need is just the opposite of your example, because in _design documents, all functions MUST be in your view function, not outside.

**Comment by gkz** [comment]
Perhaps consider using `xs.indexOf(x) > -1` rather than `in` for your use-case.

**Comment by summivox** [comment]
Sorry I misread your question.

Just out of curiousity, is this requirement because your function is serialized (i.e. `Function#toString`)?
This has been a problem since Coffee times, and yea, you'll have to either embed the runtime into the serialized code or avoid using the runtime at all.
