### ISSUE TITLE
`with` operator

### ISSUE THREAD

**Issue by roosephu** [gkz/LiveScript#914]
Hi,

It seems that `with` operator is broken in LS 1.5.0. Here is the example code (the one in the official website):

``` livescript
girl = {name: \hanna, age: 22}
guy  = girl with name: \john
guy  #=> {name: 'john',  age: 22}
# the above result include the object's prsototype
# in the result - the actual JSON: {name: 'john'}
girl #=> {name: 'hanna', age: 22}
```

When I run it online, in the end `guy` equals to `{"name":"john"}` instead of `{name: 'john',  age: 22}`. 

Thanks for maintaining such a wonderful language!

**Comment by rhendric** [comment]
It's not broken; you can test by checking that `guy.age` is in fact 22. The online REPL's default way of showing objects only shows properties defined directly on the object, and not properties inherited from the object's prototype, which is what those comments in the code you quoted are trying to convey.
