### ISSUE TITLE
Backcalls

### ISSUE THREAD

**Issue by celicoo** [gkz/LiveScript#917]
Is it possible to reproduce the following code with `backcalls`:

```
resolve files.map (file) -> 
   { 
     original-path: file
     full-path path.resolve file
  }
```
?

Thanks in advance.

**Comment by bumxu** [comment]
First **`do`** put backcall as argument in next lines, second **`do`** delimits the backcall.
So... maybe it's a bit uglier you expected. 😋 

```livescript
resolve do
  do
    file <- files.map
    {  
      original-path: file
      full-path: path.resolve file
    }
```

A more condensed version:

```livescript
resolve do
  do
    file <- files.map
    original-path: file
    full-path: path.resolve file
```

:wave:

**Comment by celicoo** [comment]
Thanks @bumxu!!
