### ISSUE TITLE
Has LS deprecated JS "with" statement thus discarded it altogether?

### ISSUE THREAD

**Issue by fansgit** [gkz/LiveScript#921]
There were some arguments I found [here](http://www.2ality.com/2011/06/with-statement.html#comment-701207086).

**Comment by summivox** [comment]
You can use:
```livescript
``with x {``
```
anyway.

`with` is not even in ES5 strict so I don't think anyone would miss it.

OTOH LiveScript's prefix (explicit cascade) and infix (prototype cloneport) `with`s are both extremely handy.
