### ISSUE TITLE
Unreachable break in switch

### ISSUE THREAD

**Issue by smokku** [gkz/LiveScript#931]
The following snippets generate unreachable code (`break;`) in switch:
JS linter running on compiled code is complaining on these.

1.

``` ls
foo = switch bar
| \a =>
  if baz then 1 else 2
| \b => 3
```

``` js
var foo;
foo = (function(){
  switch (bar) {
  case 'a':
    if (baz) {
      return 1;
    } else {
      return 2;
    }
    break;    // <-- HERE
  case 'b':
    return 3;
  }
}());
```

2.

``` ls
foo = switch bar
| \a =>
  switch baz
  | \1 => 1
  | \2 => 2
| \b => 3
```

``` js
var foo;
foo = (function(){
  switch (bar) {
  case 'a':
    switch (baz) {
    case '1':
      return 1;
    case '2':
      return 2;
    }
    break;    // <-- HERE
  case 'b':
    return 3;
  }
}());
```

**Comment by determin1st** [comment]
Well, it's more like a style problem, not the code. It only affects the size of bytes transmitted and not the speed of processing resulting JS. LiveScript, i believe, is a "filter" which produces nice JS code already with no need in additional lint.

**Comment by smokku** [comment]
My point is that this produced code could be nicer.

And you would be surprised how many programming errors can eslint catch on LiveScript generated code. I sure was.

**Comment by rhendric** [comment]
Isn't your linter wrong about the second example? If `baz` takes a value other than `'1'` or `'2'`, the `break` is reached, right?
