### ISSUE TITLE
Information about LiveScript early development history and motivation behind it?

### ISSUE THREAD

**Issue by norbertfuhs** [gkz/LiveScript#935]
Hi, I recently discovered this language and would like to know more about how this whole project started and if the early development of the the lexer and the parser is documented somewhere.

Best,

Norbert

**Comment by gkz** [comment]
I think satyr forked CoffeeScript, making coco, and I forked that making LiveScript

**Comment by norbertfuhs** [comment]
Thank you that clears things up about the history and how the project started.
I'm just curious it always fascinates me when programmers start their own language, 
again thanks for your kind reply.

Best, 
Norbert
