### ISSUE TITLE
documentation for keyword "it"?

### ISSUE THREAD

**Issue by quinn** [gkz/LiveScript#939]
I noticed while trying to integrate with mocha that if "it" is used as a function name it changes the js output. I understand that livescript uses "it" in it's compiled output, but this is different. There is no arg in the function until it is named "it", and then "it" gets added as an arg.. is there any doc for what  this behavior is for?

**Comment by quinn** [comment]
also, i did try to find a doc, but it's likely that I could have missed it because "it" isn't exactly easy to search for.

**Comment by foxbunny** [comment]
You can reassign it before you write your tests. E.g.:

```
that = it

describe 'some concept', ->
  that 'should do something awesome', ->
     ...
```

As for documentation, I don't think there is anything about it (pun intentional). I found the clue on StackOverflow.

**Comment by quinn** [comment]
thanks, yeah, i found that as well. i was mainly curious about what the behavior of "it" is. Like i said, it's only a problem in the output * after * it is used. Before that, the compiled function does not have an arg called "it".

**Comment by foxbunny** [comment]
Haha, it's difficult even just talking about it. :D

**Comment by foxbunny** [comment]
wait, "this"? I thought we were talking about "it"?

**Comment by quinn** [comment]
"say it with code":

```
$ cat test1.ls
thisFunc ->
  anotherFunc ->
    console.log 'hey-o!'

$ lsc -c -p test1.ls
// Generated by LiveScript 1.5.0
(function(){
  thisFunc(function(){
    return anotherFunc(function(){
      return console.log('hey-o!');
    });
  });
}).call(this);

$ cat test2.ls
thisFunc ->
  it ->
    console.log 'hey-o!'

$ lsc -c -p test2.ls
// Generated by LiveScript 1.5.0
(function(){
  thisFunc(function(it){
    return it(function(){
      return console.log('hey-o!');
    });
  });
}).call(this);
```

the culprit is `thisFunc(function(it){`. whats the deal, why does that get inserted magically?

**Comment by rhendric** [comment]
The documentation you're looking for is in [this section](http://livescript.net/#functions-arguments)!

In LiveScript, it's best to consider `it` as a reserved keyword (even though it technically isn't). If you need to use a literal JavaScript function or variable named `it`, surround it with double backticks like this:

```ls
-> console.log ``it``
```

**Comment by quinn** [comment]
@rhendric awesome thanks. that's what i was looking for :)

**Comment by foxbunny** [comment]
It could be additionally clarified that `it` is not a thing outside of a function.
