### ISSUE TITLE
Multiline "if" expressions

### ISSUE THREAD

**Issue by corwin-of-amber** [gkz/LiveScript#945]
This code:
```LiveScript
          positioning = if ev.altKey then 'above'
                        else if annot.some (-> it is /above/) then 'above'
                        else if annot.some (-> it is /below/) then 'below'
```

Compiles neatly into ```?:``` like this:
```javascript
          positioning = ev.altKey
            ? 'above'
            : annot.some(function(it){
              return /above/.exec(it);
            })
              ? 'above'
              : annot.some(function(it){
                return /below/.exec(it);
              }) ? 'below' : void 8;
```

However this slightly modified version:
```livescript
          positioning = if ev.altKey then 'above' else
                        if annot.some (-> it is /above/) then 'above' else
                        if annot.some (-> it is /below/) then 'below'
```

Produces a somewhat unexpected result.
```javascript
          positioning = ev.altKey
            ? 'above'
            : (annot.some(function(it){
              return /above/.exec(it);
            }) ? 'above' : void 8, annot.some(function(it){
              return /below/.exec(it);
            }) ? 'below' : void 8);
```

Notice the two ```void 8```s and the comma. Honestly I was expecting the latter to not even compile, but since it does, the result looks very unexpected. It seems like empty ```else``` clauses at the end of the line are treated as returning ```void```. Imho they should either be rejected as a syntax error or the expression should be expected to appear on the next line.

**Comment by dk00** [comment]
After rewriting spaces/indents, the modified version looks like this:

```ls
positioning = if ev.altKey
  'above'
else
  if annot.some (-> it is /above/)
    'above'
  else
  if annot.some (-> it is /below/)
    'below'
```

The second and third `if` are treated as different statement since they are at the same indent level, this is valid and compiles to expected result.

`switch` looks better than `if` / `else` in this case, you can also try this:
```ls
positioning =
  | ev.altKey || annot.some (is /above/) => \abobe
  | annot.some (is /below/) => \below
```

**Comment by corwin-of-amber** [comment]
I see; it's not really clear from the docs what the indentation rules are, but your snippet at least explains how the elses became empty. The switch version definitely looks very compact.
