### ISSUE TITLE
how is this test passing?

### ISSUE THREAD

**Issue by patrickkettner** [gkz/LiveScript#946]
Feel like I am missing something obvious, but [this line](https://github.com/gkz/LiveScript/blob/master/test/regex.ls#L99) compiles to 

```js
eq('\\' + '\\/', RegExp('\\' + '\\/').source);
```

where eq is a reference to node assert's strictlyEqual (right?). So it could be rewritten as 

```js
'\\' + '\\/' === RegExp('\\' + '\\/').source
```

and when simplified further

```js
"\\/" === "\\\/"
```

which very clearly is not the same thing. Having gone back through older versions, since 0.9.0 when the test was added, it has always resulted in the same not-equal value. 

So... how is that test suite passing?

**Comment by rhendric** [comment]
They are in fact the same thing! `\\` is an escape sequence that produces the character `\`, and both `\/` (escaped) and `/` (not escaped) produce the character `/`.

**Comment by patrickkettner** [comment]
hmm. but strictEqual doesn't have any logic for interpreting the strings in order to get the escaped value, right? We are just comparing two strings which, as you can see have, different lengths.

Throwing this together on the live compiler shows the error I am talking about

![image](https://cloud.githubusercontent.com/assets/465414/22272452/f2b602cc-e24e-11e6-84a0-36766d75e111.png)

**Comment by rhendric** [comment]
Oh my bad, I looked at the last line and assumed we were talking about that literal JavaScript expression being true (it is).

The actual answer to your question is that Node 0.10 (the engine on which the Travis CI builds are run) claims that the string value `\\/` is the value of `new RegExp('\\\\/').source`, but later versions and most other JavaScript engines seem to disagree and claim it is the string value `\\\/`.

**Comment by rhendric** [comment]
This is a mess. Does anyone even use the `$` regex flag feature? LiveScript seems to have inherited it from Coco, I don't think it's documented on livescript.net, and it seems objectively bad to have an implementation that no longer agrees with (what I think is?) the latest EcmaScript standard. I would vote for removing it altogether.

**Comment by patrickkettner** [comment]
ah, I didn't check the node version - thanks so much for the explanation :D

two follow ups

1. would you like a PR that removes that test since it seems flawed (or updates to the passing value)?
2. would you like a PR that updates your travis config to use node versions that are still supported?

**Comment by rhendric** [comment]
I personally (as a totally unofficial guy who submits PRs sometimes) would like to see this entire `$` flag feature removed (which includes the offending test). I'm planning to submit a PR that does just that. Which Node versions LiveScript ought to support is a Question of Policy, so I have no advice other than submit a PR and see if our sporadically-present BDFL smiles upon it? (If I had to guess, I think he probably will, eventually.)

**Comment by rhendric** [comment]
Okay, I've learned some new things: I see that the `$` flag feature is used to decent effect in `src/mode-ls.ls`, and while the test causing problems here is an instance of `re$ != re.source`, at least it doesn't violate `new RegExp(re$).source == re.source`, which seems like the more important invariant. This upgrades the feature in my mind from ‘useless and broken’ to ‘undocumented power feature and slightly confusing on modern platforms’. I'm going to research what EcmaScript actually specifies and see if it's not too much work to nudge this to ‘undocumented power feature that is consistent with modern standards’.
