### ISSUE TITLE
*it* disappears when chaining functors 

### ISSUE THREAD

**Issue by popkinj** [gkz/LiveScript#951]
Not sure what's going on here.... But I've noticed the following

```livescript
fixThese = file.records
  .filter -> !it.status
  .map -> {it.created_at, it.created_by_idk, it.status}
```

Which produces this

```javascript
var fixThese;
fixThese = file.records.filter(function(it){
  return !it.status;
}).map(function(){
  return {
    created_at: it.created_at,
    created_by_idk: it.created_by_idk,
    status: it.status
  };
});
```

Notice how the second functor *map* doesn't get passed the *it* variable.

**Comment by rhendric** [comment]
Looks like a duplicate of #899. It's fixed on master, but not released yet.

**Comment by popkinj** [comment]
Cool. Thanks @rhendric .

**Comment by dk00** [comment]
It can also be rewritten with [substructuring](livescript.net/#assignment-substructuring):

```ls
  .map -> it{created_at, created_by_idk, status}
```
This does the same, and avoids repeating `it`.

**Comment by popkinj** [comment]
Nice one @dk00 ... Livescript is awesome!!

**Comment by askucher** [comment]
livescript is awesome but it is hard to convince people. it is even hard to find job when I say "I use livescript"

**Comment by popkinj** [comment]
I see your point @askucher ... And feel your pain.
My experience is people are more likely to warm up to Coffeescript. So I just tell them that the creator of Coffeescript went on to create something even better.... Livescript. Seems to work. ha ha... Not always though.
