### ISSUE TITLE
Use Array.from instead of [].slice

### ISSUE THREAD

**Issue by KSXGitHub** [gkz/LiveScript#963]
### Example code

```livescript
function * gen ()
  yield 123
  yield 456
  yield 789

console.log [...gen()]
```

### Expected JavaScript

```javascript
function* gen(){
  (yield 123);
  (yield 456);
  return (yield 789);
}
console.log(Array.from(gen())); // This would print [123, 456, 789]
```

### Current JavaScript
```javascript
var slice$ = [].slice;
function* gen(){
  (yield 123);
  (yield 456);
  return (yield 789);
}
console.log(slice$.call(gen())); // This would print an empty array
```

**Comment by dk00** [comment]
[`Array.from`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from) requires ES6 support, and if a JS engine knows `Array.from`, it should also know  [spread](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator)(`...expression`)

If we decide to output ES6, we can use spread here, spread can be used with any iterables(including generators) like `Array.from`.

```ls
splat-in-array = [a, ...b, c, ...gen!]
splat-in-object = {a, ...b, c, ...d}
call-with-splat-parameters = fn a, ...b, c, ...d
```

```js
var splatInArray, splatInObject, callWithSplatParameters
splatInArray = [a, ...b, c, ...gen()];
splatInObject = {
  a,
  ...b,
  c,
  ...d
};
callWithSplatParameters = fn(a, ...b, c, ...d);
```

**Comment by rhendric** [comment]
Targeting ES6 has been discussed elsewhere, I believe, and if it's worth doing, it's worth doing in the context of a broader review of the backend, such as #862. In the meantime, this can certainly be addressed in an ES3-compatible way, which is my intent.

**Comment by KSXGitHub** [comment]
@dk00 We can use [polyfill](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/from?v=control#Polyfill)

**Comment by vendethiel** [comment]
@rhendric congrats on the badge!

**Comment by determin1st** [comment]
thanks 8)
