### ISSUE TITLE
Livescript Extension for React + Pug

### ISSUE THREAD

**Issue by askucher** [gkz/LiveScript#970]
Hi Everyone.

I figured out that people love React (and we love) but Livescript does not support it. 
We are going to build a company (today we gonna have first round funds) and definitely want to use livescript and react
So decided to implement the library `reactify-ls`

`notice! it uses pug syntax for html tree`

How to install
```
npm i lsxc -g
```

Here is example of todo list

```Livescript
# todo.ls
require! {
  \mobx-react : { observer }
  \mobx : { observable }
  \react-dom : { render }
  \react
}

btn = ({click, text})->
    style =
        color: \red
        padding-left: \5px
    a.vv.btn(target='blank' on-click=click style=style) #{text} 

input = ({store})->
  handle-enter-click = (event) -> 
    return if event.key-code isnt 13 
    store.todos.push text: event.target.value
    event.target.value = ''
  input.vv(on-key-down=handle-enter-click)  

Main = observer ({store})->
  remove = (todo, _)-->
      index = store.todos.index-of todo
      return if index < 0
      store.todos.splice 1, index
  .vv
    h3.vv Tasks
    for todo in store.todos
      .vv 
        span.vv #{todo.text}
        span.vv
          btn {text: 'Remove', click: remove todo}
    input {store}
    hr.vv 
    

window.onload = ->
  store = observable do
      todos:
        * text: 'Do dishes'
        ...
  render do
    Main.vv(store=store)
    document.body.append-child document.create-element \app
```

Compile 

```Bash
lsxc -hbc todo
#created index.html -> just open it :)
```

We would like to propose to add such syntax into the livescript but for now you can use our library and collaborate. 

In September we are going to raise 2 million dollars and then will hire first people from collaborators.

**Comment by vendethiel** [comment]
relevant: https://github.com/jashkenas/coffeescript/pull/4553

**Comment by vendethiel** [comment]
If you actually plan to do it, definitely go for HAML.

**Comment by askucher** [comment]
It is already done. But we will add sass + dynamic classes support later

**Comment by vendethiel** [comment]
Except your converter has ambiguities.

```livescript
  remove = (todo, _)-->
      index = store.todos.index-of todo
      return if index < 0
      store.todos.splice 1, index
  .vv
```

is already valid LS code

just like

```
a.vv.btn() text
```

also is valid.

I know where you're coming from with this – [I made the exact same tool in 2013](https://github.com/vendethiel/nephrite). Doesn't work at bigger scale.

**Comment by vendethiel** [comment]
or do you mean you always need to see `.vv` to detect a line? That's still regex-based matching, alas. Why not use `%` and not be ambiguous? (much less)

**Comment by askucher** [comment]
Yesh. I just parse line.match(/\.vv/) and convert it into the react.createElement. Still brainstorming about best decision. 
The idea was to make livescript + react code compatible with jade/pug. Because a lot of code is already written there and actually pug is consistent with saas

**Comment by askucher** [comment]
@vendethiel will try

**Comment by vendethiel** [comment]
I think it's best if you manage to adapt the HAML PR still. No need for regex hacks, so you have better luck to make everything work.

**Comment by askucher** [comment]
Little update. We added support of `sass` as well. And renamed `.vv` to `.pug` to better reading.
We did not consider `%` because it is invalid selector when `pug` is valid selector

```Livescript
require! {
  \mobx-react : { observer }
  \mobx : { observable }
  \react-dom : { render }
  \react
}

btn:sass =
  color: red
  padding-left: 5px
  &:hover
    color: orange


btn = ({click, text})->
    a.pug.btn(target='blank' on-click=click) #{text} 

input = ({store})->
  handle-enter-click = (event) -> 
    return if event.key-code isnt 13 
    store.todos.push text: event.target.value
    event.target.value = ''
  input.pug(on-key-down=handle-enter-click)  

Main = observer ({store})->
  remove = (todo, _)-->
      index = store.todos.index-of todo
      return if index < 0
      store.todos.splice 1, index
  .pug
    h3.pug Tasks
    for todo in store.todos
      .pug 
        span.pug #{todo.text}
        span.pug
          btn {text: 'Remove', click: remove todo}
    input {store}
    hr.pug 
    

window.onload = ->
  store = observable do
      todos:
        * text: 'Do dishes'
        ...
  render do
    Main.pug(store=store)
    document.body.append-child document.create-element \app
```

**Comment by askucher** [comment]
https://gitter.im/lsxc/Lobby# Who would like ask me questions. Please do
