### ISSUE TITLE
How to inspect Node.js applications

### ISSUE THREAD

**Issue by ceremcem** [gkz/LiveScript#972]
In browser, we have sourcemaps to debug Livescript. How do we debug in server side, with breakpoints?

**Comment by rhendric** [comment]
You might be interested in the [source-map-support](https://github.com/evanw/node-source-map-support) package and/or the [Node.js debugger documentation](https://nodejs.org/api/debugger.html).

**Comment by ceremcem** [comment]
For future readers: see https://github.com/ceremcem/debugging-livescript

**Comment by ceremcem** [comment]
@rhendric How do you generate your server side bundles with source maps for debugging? Please see: https://stackoverflow.com/q/63614309/1952991

**Comment by rhendric** [comment]
I personally run `lsc` to generate intermediate files and then bundle those with whatever bundler happens to be my favorite at the time (currently, it's Parcel). Most bundlers handle embedded source maps just fine.

Your issue looks like it might be caused by a limitation of the browserify-livescript project.

**Comment by ceremcem** [comment]
I finally managed to get the "debugger" working: https://github.com/ceremcem/debug-ls/tree/1.0.0

 I didn't quite get the problem with browserify. I also tried Parcel.js but it didn't work for me either. 

At the moment, running a LiveScript file via `debug-ls` works just fine:

![image](https://user-images.githubusercontent.com/6639874/92029989-0f2d4800-ed6f-11ea-9d16-503114ef400f.png)

**Comment by determin1st** [comment]
check out a `NiM` extension: https://chrome.google.com/webstore/detail/nodejs-inspector-manager/bnmjajghllhhhgiaeipaibfmnjnponhd

shortened me a debug cycle last time i used it..

**Comment by ceremcem** [comment]
[`debug-ls`](https://github.com/ceremcem/debug-ls) is stable and works for any code that `require`s any external libraries except for dynamic imports. So, I'm not looking for anything new, but thanks for introducing NiM anyway :)

The solution of NiM isn't quite related with this topic because the main problem I had was that we can not debug a LiveScript code with any debugger that inspects simply a `.js` file: 

![image](https://user-images.githubusercontent.com/6639874/93005997-b07e8000-f55f-11ea-9a59-60c8ee447682.png)

Problem: How can we see the original source code while debugging the `.js` file that is generated from `.ls` file? It turns out the solution requires the following steps: 

1. Compile all LiveScript scripts that your script would possibly `require`s (or `import`s)
2. Include source maps so that debugger could translate the `.js` code back into `.ls` code when hit to a breakpoint.

That looks simple as that. However setting up a "bundling command" for step 1 was a little bit tricky for me for a long long time.

**Comment by ceremcem** [comment]
@determin1st I just understood the value of NiM. When your source file changed, you have to: 

1. Re-bundle your application. 
2. Kill the current `node` process and restart it. 
3. Close your debugger
4. Go to chrome://inspect/#devices
5. Find your application 
6. Click "inspect" button. 

NIM simply automates the steps 3, 4. 5, 6 and simply (re)opens the debugger window for you whenever a `node` process is started with `--inspect` parameter, thereby greatly speeds up the debugging cycles.

Thanks again.
