### ISSUE TITLE
how to compile complex folders

### ISSUE THREAD

**Issue by willin** [gkz/LiveScript#976]
https://github.com/gkz/LiveScript/blob/master/Makefile#L16

like:

```bash
src/
    lib/
       xxx.js # files and sub folders 
    models/
    routers/
```

**Comment by rhendric** [comment]
@willin, `lsc` by itself is one file in, one file out. Handling multiple files is up to some other tool—in the line you linked, it's `make` that is running `lsc` for each file in `src`. Adapting the Makefile to handle deeper folder structures is (A) not difficult and (B) a make question, not a LiveScript question.
