### ISSUE TITLE
Where is macros documentation? 

### ISSUE THREAD

**Issue by askucher** [gkz/LiveScript#981]
I cannot find it on the livescript.net

**Comment by vendethiel** [comment]
There are no macros in livescript. If you're talking about compiler hooks, they're totally different.

**Comment by askucher** [comment]
Are you going to develop this language?

**Comment by vendethiel** [comment]
Who, me? I left the team last year

**Comment by rhendric** [comment]
What ven said. As for improving the language, I will happily review well-tested pull requests that don't disrupt existing users, although I would want some community consensus before merging a major feature such as macros. But you should probably be prepared for the evolution of LiveScript to be slow, given recent activity. Personally, I don't intend to develop more features for LiveScript (though I may come in and fix a bug now and again), and I'm not aware of anyone else who does.
