### ISSUE TITLE
ES6 Classes

### ISSUE THREAD

**Issue by activestylus** [gkz/LiveScript#989]
Right now I can type:

```Livescript
class Person
  say -> consol.log 'hi'
```

But this still yields old syntax:

```
(function(){
  var Person;
  Person = (function(){
    Person.displayName = 'Person';
    var prototype = Person.prototype, constructor = Person;
    say(function(){
      return consol.log('hi');
    });
    function Person(){}
    return Person;
  }());
}).call(this);
```

Ideally Livescript classes would map to ES6 syntax  instead - but I figure that could be a breaking change.  Any ideas?

**Comment by rhendric** [comment]
You might try checking in at [livescript-next](/dk00/livescript-next). I think this along with all other ES6+ output features (there have [been](/gkz/LiveScript/issues/490) a [number](/gkz/LiveScript/issues/667) of [requests](/gkz/LiveScript/issues/705) for them) should ideally happen through that project, or something similar if it stalls out.

**Comment by vendethiel** [comment]
Changing that behavior means 1) breaking executed class bodies 2) adding yet another syntax

**Comment by activestylus** [comment]
@rhendric  I had no idea about LS next - you have no idea how glad I am that I can stay in livescript land (I feel personally oppressed by ES6 syntax, lol) @vendethiel I suspected as much and will close this issue given that this is definitely out of scope for this particular version
