### ISSUE TITLE
livescript tmlanguage

### ISSUE THREAD

**Issue by askucher** [gkz/LiveScript#990]
Guys.

We are using `https://www.npmjs.com/package/lsxc` for our project. it is livescript + sass + pug combined for react apps. 

I need to extend a syntax. Can you show me where is ls source of `/var/www/c9sdk/node_modules/ace/lib/ace/mode/livescript.js`  located?

**Comment by gkz** [comment]
make `lang-ls` or `mode-ls` in https://github.com/gkz/LiveScript/tree/master/src ?

**Comment by askucher** [comment]
Thank you
