### ISSUE TITLE
priority issue

### ISSUE THREAD

**Issue by askucher** [gkz/LiveScript#991]
```livescript
div = (/)
```
problem: 
```livescript
68253000000 `div` 10^8 # mul first then ^
```
ok: 
```livescript
68253000000 `div` (10^8) # ^ then mul
```

**Comment by rhendric** [comment]
I don't see a bug here. Backticks were designed to have [higher precedence](https://github.com/gkz/LiveScript/blob/68a6d215e790eccb1047af0b7c91f9b695adadc6/src/grammar.ls#L461-L481) than any other operator.
